### ISSUE TITLE
tvshow.nfo format causes database mixups: separate, unrelated shows are merged

### ISSUE THREAD

**Issue by domschl** [mediathekview/plugin.video.mediathekview#10]
The current format of tvshow.nfo created by mediathekview plugin function 'Download' triggers incorrect behaviour of scraper on import into TV-Shows.

If downloaded mediathek-shows are imported as TV-Shows, they are sometimes randomly mixed with different shows that also use NFOs. Die mediathek Show download then suddenly contains random episodes from totally unrelated shows, including wrong poster- and fanart. The record for the other show vanishes...

Investigation into what exactly triggers this is ongoing...

**Comment by domschl** [comment]
Kodi's NFS scraper randomly mixes shows, if, and only if `tvshow.nfo` has to <id> tag.
A tag
`<id></id>`
seems mandatory. it doesn't matter if the tag is empty. It just needs to be there.

**Comment by tuxpoldo** [comment]
AGH!!!!

**Comment by domschl** [comment]
Retest: new NFO files with inserted of `<id></id>` now work as expected! Fixed.
