### ISSUE TITLE
Plugin vergisst gelegentlich Einstellungen

### ISSUE THREAD

**Issue by fefrei** [mediathekview/plugin.video.mediathekview#104]
Ich nutze das Plugin in LibreELEC mit einer externen Datenbank. Das funktioniert auch wunderbar, gelegentlich vergisst das Plugin aber seine Einstellungen und beginnt dann wieder, seine lokale Datenbank aufzubauen. Auch in der `settings.xml` sind die Verbindungsparameter dann weg.

**Comment by tuxpoldo** [comment]
Das ist aber spannend. Das Problem an der Sache ist, dass ein Plugin eigentlich gar nicht die Einstellungen vergessen kann, denn diese werden von Kodi verwaltet. Bei jedem Aufruf holt sich das Plugin die Einstellungen von Kodi. Auch die Verwaltung der Einstellungen wird nicht vom Plugin gemacht, sondern von Kodi. Die entsprechenden Masken baut Kodi auf, basierend auf den Feldern in der Datei `settings.xml` in `resources` Verzeichnis des Plugins und der Sprachstrings in den entsprechenden `strings.po` Dateien in den Sprachvereichnissen. Zu keiner Zeit fasst der Code im Plugin die `settings.xml` im Daten-Verzeichnis des Plugins selber an. Es steht also zu befürchten, dass es sich hier um andere Probleme handeln muss...

**Comment by fefrei** [comment]
Hm, interessant! Ich schaue mal, ob ich irgendwie eingrenzen kann, wann genau das passiert. Danke für die Hilfe!
