### ISSUE TITLE
Feature request: Nur .strm Datei und NFO anlegen

### ISSUE THREAD

**Issue by Shensen** [mediathekview/plugin.video.mediathekview#105]
Ist es möglich das man die Serien und Filme nicht herunterladen muss aber sie trotzdem sauber in die Bibliothek einbinden kann?

Ich habe es schon mit Osmosis versucht aber aufgrund der fehlenden Metadaten bei den scrapern tauchen sie schlicht nicht in der Bibliothek auf.

**Comment by Shensen** [comment]
Ich habe mir nochmal ein paar Gedanken dazu gemacht. Was bei der Umsetzung wichtig wäre ist, das die Dateien nach Möglichkeit automatisch generiert, und bei Entfernung aus der Mediathek wieder gelöscht werden.

Aufgrund der vielen Einträge in der DB würden dadurch natürlich nochmal sehr viele Daten anfallen und ein großer load entstehen wenn man diese Option als default setzt. Könnte man die Option vielleicht explizit an den Ordnern anheften um diese in die Bibliothek einscannen zu lassen?

**Comment by tuxpoldo** [comment]
Ich verstehe nicht, wozu das gut sein soll. In der Bibliothek von Kodi befinden sich Einträge zu Medien die man besitzt. Dies bedeutet: eine Mediendatei - z.B. `wav`, `mp3`, `mkv`, `mp4`, `avi` oder ähnlich - befindet sich im direkten Zugriff von Kodi - d.h. sie liegt auf einem Datenträger an dem Kodi ran kommt. Damit dies der Fall ist *muss* man sie aus den Mediatheken herunterladen.
