### ISSUE TITLE
DB-Update/Import ab bestimmten Datum

### ISSUE THREAD

**Issue by tikron** [mediathekview/plugin.video.mediathekview#106]
Hi! 

Freue mich auch über dieses tolle AddOn. Nun habe allerdings auch ich Probleme mit der Laufzeit des mvupdate. Dies läuft auf einer Synology DS212+ mit MariaDB 10 mehrere Stunden. Ich habe die Issues zu diesem Thema größtenteils gelesen. GIbt es zu dem Problem schon eine Lösung?

Vorschlag: Ich würde mir einen Parameter wünschen, über den ich ein Datum angeben kann, ab dem mvupdate überhaupt Sendungen importiert. Denn mich interessieren eigentlich kaum Sendungen, die vor mehr als 1 Monat ausgestrahlt (aired) wurden. Geschweige denn alle 260.000.

**Comment by alex1702** [comment]
Die updates sollen durch eine andere Methode beschleunigt werden. Tuxpoldo hatte da schon eine Idee. 
Mehrere Stunden import auf einem synology NAS finde ich jetzt nicht problematisch. 

Dein Wunsch klingt simpel ist es aber nicht unbedingt. Klar man kann das so machen. Dürfte auch Zeit sparen. Aber es gibt Sendungen welche wiederholt werden und da gibt es nur das erstausstrahlungsdatum. Diese Sendungen würden bei dir gnadenlos raus fliegen, auch wenn online der Film grade erst raus gekommen ist.

Das hat Gründe aus dem Desktop Client, weswegen die Filmliste so strukturiert wurde.

Ich hoffe es geht bald weiter mit dem Kodi AddOn, nur hatte tuxpoldo viel um die Ohren in letzter Zeit und er ist aktuell der einzige, welcher sich um dieses kümmert.

**Comment by tuxpoldo** [comment]
Wir verfolgen gerade verschiedene Ansätze um das Datenbank-Update-Problem zu lösen. Da es sich hier wirklich nur um einen Workaround für dieses Problem handelt, der unter anderem auch recht schwer zu implementieren wäre, und ansonsten keinen wirklichen Nutzen bringt, sehe ich im Moment keinen Grund das zu implementieren. In kürze werden wir das erste Update rausbringen, welches das Problem für SQLite endgültig lösen dürfte. Hiermit ist dann der Leidensdruck erst mal raus.
