### ISSUE TITLE
Initial DB setup does not work

### ISSUE THREAD

**Issue by flexguse** [mediathekview/plugin.video.mediathekview#122]
Hi,

yesterday I tried to configure the MediathekView Kodi addon in my LibreElec 9.0.1 to use a external MariaDB / MySQL Database which did not work. The addon seems not to create the Database-Tables.
I tried to use in my Docker setup:
- latest MariaDB
- MariaDB 5
- latest MySQL
- latest MySQL 5

With a database tool I was able to create database-tables in every case, so my DB setup seems to be correct.
Unfortunately I did not found any logfile with relevant information so I have no clue what does not work. Maybe it is uncommon I use passwords containing of 20 characters.

The internal SQLLite database works, but is not very performant on a RaspberryPi 2.

Any ideas?

Thank you in advance,
Christoph

**Comment by tuxpoldo** [comment]
Can you please try to get the Kodi log file? Any debug information should be contained there. Usually the Kodi-Addon should automatically create the Database AND the Tables. Please keep in mind that the user that you specify for MySQL must have the right to create the database AND the tables AND the stored procedures.

To make sure everything works, you may configure your addon to use the `root` user for the first launch. After the Database has been created, you can change the user to a less privileged user that has only rights on the database.

**Comment by tuxpoldo** [comment]
Since there are no news here, I will close this issue.
