### ISSUE TITLE
Favoriten in Kodi verschoben

### ISSUE THREAD

**Issue by imolb** [mediathekview/plugin.video.mediathekview#125]
Das Speichern von Kategorien in den Favoriten von Kodi liefert nach einiger Zeit nicht mehr die gewünschten Inhalte. Stattdessen wird in den Favoriten der Inhalt einer anderen Kategorie/Show angezeigt.

Vermutung: Beim Speichern einer Kategorie (in der DB als Show) in den Favoriten von Kodi wird die URL hinterlegt, etwa in der Form:
`<favourite name="Tatort" thumb="special://home/addons/plugin.video.mediathekview/resources/icons/ard-m.png">ActivateWindow(10025,&quot;plugin://plugin.video.mediathekview/?mode=films&amp;show=939&quot;,return)</favourite>`
Diese Show-ID (hier 939) aus der Datenbank scheint aber vermutlich bei einem DB-Update nicht erhalten zu bleiben und verschiebt sich, wenn eine weitere Kategorie in der DB davor ergänzt/gelöscht wird.

Andere Addons hinterlegen in den Favoriten-URLs eher den Namen und keine ID.

Ideen:
a) In der Datenbank eine ID generieren, die auch bei Updates erhalten bleibt.
b) Ähnlich wie anderen Addons keine ID, sondern eher den Titel in der URL hinterlegen.

Hängt evtl. auch mit #123 zusammen.
Mediathekview: 0.6.2
Kodi: 17.6

**Comment by tanrak** [comment]
Habe das Problem auch beobachtet. Ist aber in den Einstellungen die schnelle Datenbankaktualisierung ausgeschalten dann taucht Fass Problem nicht auf!

**Comment by tuxpoldo** [comment]
Hallo zusammen,

das Problem ist bekannt. Ich arbeite derzeit an einer Lösung (feste eindeutige ID pro Sendung benutzen - die müssen aber generiert werden). Es gibt einen kurzfristigen Workaround: der wäre das schnelle Update abzuschalten - aber das will vermutlich keiner ;-)

**Comment by codingPF** [comment]
Duplilcate #123
