### ISSUE TITLE
Film Beschreibung wird nicht angezeigt

### ISSUE THREAD

**Issue by imolb** [mediathekview/plugin.video.mediathekview#126]
Die Filmbeschreibung wird bei mir leider nicht angezeigt, wie sie links unten angezeigt wird (siehe Screenshot, den ich im Internet gefunden habe).

![image](https://user-images.githubusercontent.com/49784529/56422991-6fbb0280-62aa-11e9-95b5-220a23694ac6.png)

Mediathekview: 0.6.2
Kodi: 17.6

**Comment by codingPF** [comment]
Ich habe mir eine Kodi 17.6 Version fertig gemacht um das ganze einmal zu sehen...aber bei mir klappt das ohne Probleme. Am besten mal ein neunes Beipiel...

**Comment by codingPF** [comment]
Aged and drop

**Comment by imolb** [comment]
Danke für die neue v0.6.4! Allerdings besteht das Problem noch.

Hier der Screenshot davon: Es wird keine Filmbeschreibung angezeigt.
Kannst Du das Issue nochmal reopen, oder sollte ich ein neues anlegen?

Getestet mit:
osmc 2020.03-1
Kodi 18.6
Mediathekview 0.6.4

![mediathekview_keine_filmbeschreibung](https://user-images.githubusercontent.com/49784529/83336244-18130700-a2b2-11ea-88e6-e3db5d391458.jpg)

**Comment by codingPF** [comment]
Ich denke das liegt an deinem Skin...wie heißt es?

**Comment by imolb** [comment]
Du hast recht, es liegt an meinem Skin "OSMC Skin" (default bei OSMC). Wechsle ich auf den Skin Estuary wird die Filmbeschreibung und auch die Erstausstrahlung (#127 ) korrekt angezeigt. Entschuldige die Umstände und danke für Deinen Einsatz!

**Comment by Ch1llb0** [comment]
Auch hier ist die Antwort, dass der content type nicht gesetzt wird und somit nicht die Ansicht für Filme oder Serienepisoden genutzt wird/verfügbar ist.

**Comment by codingPF** [comment]
Das umsetzen des contentType hat leider auf meinen Skin einige Nebenwirkungen die ich im ersten Moment nicht gut finde...
Da muss ich mal etwas länger drüber nachdenken....

**Comment by Ch1llb0** [comment]
Ohne content Typ kann halt nichts explizit an Inhalt angepasst werden. Somit wird hier die einfachste Ansicht oben spezifische Informationen angezeigt. Wenn ich ehrlich bin, sollte der content type entsprechend des Inhalts gesetzt sein und skins müssen damit dann entsprechend umgehen können.

**Comment by Ch1llb0** [comment]
Der Content Type muss laut Kodi Add-on-Regeln gesetzt sein und korrekt sein... Das Mediathekview-Addon setzt weiterhin gar keinen Content: https://kodi.wiki/view/Add-on_rules#Requirements_for_scripts_and_plugins

`They should set the correct media content from which the correct skin view type is automatically provided.`

Den OSMC Skin habe ich nun angepasst, sodass der für [Video Add-ons vorgesehene](https://github.com/xbmc/xbmc/commit/e436266e4b82da84a4463eead0db829acefe3aa3) Content Type "Videos" beachtet wird und damit auch die Anzeige von Beschreibungstext ermöglicht wird.

Bitte den Content Type in einer zukünftigen Version korrekt wie von Kodi vorgesehen setzen. 👍
