### ISSUE TITLE
Anzeige der Erstausstrahlung in Liste

### ISSUE THREAD

**Issue by imolb** [mediathekview/plugin.video.mediathekview#127]
Das Addon "Das Erste Mediathek" zeigt beim aktuell ausgewählten Element in der Liste das Erstaustrahlungsdatum an. Dies wäre für Mediathekview auch wünschenswert.
![image](https://user-images.githubusercontent.com/49784529/56476148-d0f1fa00-6493-11e9-9553-0ed5ae16754c.png)

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4

**Comment by imolb** [comment]
Gerade mit der v0.6.4 probiert, allerdings kann ich da kein Erstausstrahlungs-Datum sehen. Ist dies noch separat zu aktivieren oder nur in speziellen Skins sichtbar?

**Comment by imolb** [comment]
Problem liegt am Skin "OSMC Skin". Beim Skin Estuary wird die Erstausstrahlung angezeigt. Problem liegt also am Skin

**Comment by Ch1llb0** [comment]
Der Skinner des OSMC Skin hier... Es liegt daran, dass das Add-on keinen content type setzt, sondern ihn bei "Files" belässt. Für diesen Fall nutzt unser Skin eine andere Liste, die engere Abstände und kein zweites Label anzeigt. Würde das Add-on einen content type "Episode" setzen, dann wäre es sichtbar.

**Comment by codingPF** [comment]
Also ich tue mich schwer damit den Content zu setzen da dann im standart Skin die Aufzählungszeichen keine Bilder sondern nur noch Punkte sind.
Ich habe verschieden Skins getestet und den Code umgestellt aber keine gute Lösung gefunden.

Ich habe jetzt den Content Type als Setting hinzugefügt (default none - wie vorher) und gebe somit die Entscheidung an den User.

Ich habe dir eine Testversion hier angehämgt (Änderungen sind noch nicht gepusht). Versuch doch mal ob das für dich Sinn macht und dann könnte man das in die nächste Version aufnehmen,
[plugin.video.mediathekview-0.6.5.zip](https://github.com/mediathekview/plugin.video.mediathekview/files/4739922/plugin.video.mediathekview-0.6.5.zip)

**Comment by Ch1llb0** [comment]
Schaue mir das mal an. Vielen Dank!

**Comment by imolb** [comment]
Mit der 0.6.5 wird bei mir im OSMC Skin nun _das Jahr_ der Erstausstrahlung mit angezeigt, sofern die Einstellung Content-Type nicht auf none steht. Somit Problem mit diesem Fix für mich gelöst. (Wobei ich persönlich nun eh auf einen unterstützten Skin gewechselt bin).
Tag und Monat werden allerdings nicht angezeigt.

**Comment by Ch1llb0** [comment]
In der Tat kann dieses Vorgehen es lösen - zumindest haben damit Nutzer die volle Flexibilität für alle Skins. 👍 

Mir ist etwas anderes aufgefallen: Einzeilige Localizes von Addons sollten niemals Zeilenumbrüche und insbesondere Farben enthalten. In Skins kann das zu sehr unschönen Effekten führen wie auf Controls herauswanderndem oder nicht lesbarem Text. Bitte entfernt zumindest die vorgegebene Farbe aus Localize 30990 (`Airdate: [COLOR chartreuse]{0:s}[/COLOR][CR][CR]`)

**Comment by codingPF** [comment]
An der Farbe hänge ich erstmal nicht...das geht für mich auch so
Ist jetzt im Dev-branch

**Comment by Ch1llb0** [comment]
> In der Tat kann dieses Vorgehen es lösen - zumindest haben damit Nutzer die volle Flexibilität für alle Skins. 👍

Auch hier kurz ein Update... Der Content Type darf laut Kodi-Regeln nicht von einem Video Add-on anders als auf "Videos" gesetzt werden. Der OSMC Skin kann dies zukünftig mit dem Erstaustrahlungsdatum anzeigen. Dafür muss allerdings wie vorgesehen ein Content Type fest gesetzt werden.

**Comment by codingPF** [comment]
Kodi Repo Check-in: Version 0.6.6 ist live

**Comment by Ch1llb0** [comment]
Die Option, den Content-Type anzupassen, ist nun im neusten Release angekommen, allerdings setzt das Addon, wie von Kodi vorgeschrieben, weiterhin standardmäßig keinen Content-Type (siehe meine Ausführungen hier: https://github.com/mediathekview/plugin.video.mediathekview/issues/126) - der Content-Type "Videos" muss gesetzt sein und es dürfen keine anderen laut Kodi angeboten werden.

Es wäre schön, "Videos" könnte zukünftig standardmäßig nach den Vorgaben gesetzt werden! 👍🏻

**Comment by codingPF** [comment]
Hi @Ch1llb0 
ich verstehe, dass dies für dich nicht die optimiale Lösung ist.
Aber bitte versteh auch, dass ich das aktuelle Look & Feel nicht verändern möchte.
Sorry und Gruß

**Comment by Ch1llb0** [comment]
Es geht nicht darum, was ich möchte, sondern eine Kodi-Vorgabe... Just my 2cts. Ein Addon, das im Gegensatz zu allen anderen Video-Addons im Kodi-Repo den Content type nicht setzt, ist für Skins, die diese Content types beachten, sehr unschön.
