### ISSUE TITLE
Übersetzungen der Benutzeroberfläche funktionieren nicht

### ISSUE THREAD

**Issue by tuxpoldo** [mediathekview/plugin.video.mediathekview#13]
Das war bedauerlicherweise nie aufgefallen, weil sowohl @domschl als auch ich Kodi immer auf Englisch benutzen und wohl keiner sich aus dem Forum gemeldet hat. Leider ist es aber so:

Es funktioniert weder die Deutsche noch die Italienische Benutzeroberfläche.

**Comment by tuxpoldo** [comment]
Geplantes Release: 0.3.4

**Comment by vitusson** [comment]
Hätte ich nicht bemerkt, obwohl mein Kodi auf Deutsch gestellt ist. 
Aber da die meisten Addons Englisch sind und ich auch sonst im RL den ganzen Tag zwischen den beiden Sprachen switche fällt mir sowas nicht auf. ;-)
