### ISSUE TITLE
PVR, EPG

### ISSUE THREAD

**Issue by Sythelux** [mediathekview/plugin.video.mediathekview#133]
Denkt ihr es wäre möglich, dass das Plugin sich als PVR + EPG Dienst im Kodi registriert und damit als "Live-TV" an der Seite mit erscheint? Oder ist das schon drin und ich bin Blind.

**Comment by alex1702** [comment]
Man könnte das höchstens für die Livestreams machen. Für Mediathekinhalte geht sowas garnicht.
Eventuell hilft dir das hier https://www.kodi-tipps.de/kodi-iptv-einrichten-live-tv-mit-kodi-anschauen/ weiter.
