### ISSUE TITLE
Frage zur MySQL-Datenbankgröße

### ISSUE THREAD

**Issue by Uatschitchun** [mediathekview/plugin.video.mediathekview#137]
Hi. Ist es richtig, dass die Datenbank so groß wird?!
Das initiale Update der Mysql-DB ist zu 90% durch (was auch recht lang dauert!?) und die DB hat bereits jetzt gute 300MB!?

Ist es richtig, dass nach dem initialen Einrichten der DB, die weiteren Updates nur noch "Häppchen" sind?

**Comment by alex1702** [comment]
Die Größe ist normal, da es gut über 300.000 Filme sind. Dazu werden noch versucht Shows zu ermitteln, weswegen die Datenbank noch größer wird.

Theoretisch werden nur noch Diff's geladen. Da es aber fatal ist, wenn mal ein Diff, weswegen auch immer, ausgelassen wird. Wird glaub ich nach ner Zeit auch noch mal eine vollständige Liste geladen und in die Datenbank einsortiert.

**Comment by Uatschitchun** [comment]
Ok, danke für die Rückmeldung!
