### ISSUE TITLE
Thumbnail icons für sendungen

### ISSUE THREAD

**Issue by jokober** [mediathekview/plugin.video.mediathekview#141]
Es wäre schön, wenn für jede Sendung ein thumbnail icon bzw Vorschau Bild angezeigt werden würde. In dem Mediathek Add-on ist das beispielsweise möglich.

**Comment by Ch1llb0** [comment]
Der Übersichtlichkeit und der Optik wäre dies in der Tat dienlich. +1 von mir.

**Comment by vitusson** [comment]
Die üblichen Mediathek-Addons greifen direkt auf die Webseite der Mediathek zu und können deswegen die dortigen Vorschaubilder anzeigen.
Das MV-Plugin bezieht seine Daten aber aus der vom MV-Crawler erzeugten Filmliste und die beinhaltet keine URL zu den Thumbnails. 
Nun, man könnte theoretisch die Thumbnails-URL in der Filmliste mit speichern, aber da MV keine Funktionalität hat um Bilder anzuzeigen und ich davon ausgehe das dies erstmal so bleibt, wird auch das Plugin weiterhin nur die Senderlogos zeigen.

**Comment by codingPF** [comment]
Das ist leider ein Thema für den CRAWLER in MVSERVER
