### ISSUE TITLE
Database Problem on FireTVStick 4K .... Kodi 18.5 and Mediathekvew 0.6.2

### ISSUE THREAD

**Issue by MartinHH76** [mediathekview/plugin.video.mediathekview#143]
Hello everybody.
I do not know when this happened exactly the first time, but formerly I had Kodi 18.2 with Mediathekview 0.xx . Firstly, the update did not work, but finally, after I had copied the filmliste-v2.db into the correct folder on the Stick everything seems to work fine from there on.

Now since a couple of days I decided to update Kodi to the latest recommend Version (18.5) and installed Mediathekview 0.6.2 there. I did so, because mediathekview seems not to update any more and in the Blogs is told that all works(ed) fine and were fixed! Damn it. I experienced something else and do not know how to downgrade or fix. It seems that the DB update is really broken.  The functionality of mysql-server does not work either. No wonder since the plug-in needs to download the normal database file first.

It would be good if one had the ability to change the location of mediathekview database to download and to change the type of file. 

I am a bit helpless in this case and appreciate some help what to do ?

**Comment by MartinHH76** [comment]
Ah, okay nun auf Deutsch ....
Also ich denke, das Problem liegt in dem Link zum Server denn der aktuelle aktive link zur mediathek filmliste ist wie folgt ...
Datei ./resources/lib/storesqlite.py
DATABASE_URL = 'https://liste.mediathekview.de/filmliste-v2.db.xz'
jedoch ist dieser link tot

hier sollte ein update erfolgen ... und wenn wie in der Zeile davor 
DATABASE_URL = 'https://mvupdate.yeasoft.com/filmliste-v2.db.xz'

Workaround ....
1. download via file 'https://mvupdate.yeasoft.com/filmliste-v2.db.xz' z.B. mit wget 
command: wget  https://mvupdate.yeasoft.com/filmliste-v2.db.xz
2. entpacken im entspr. Archiver (tar funktioniert hier leider auch nicht  - eigentlich tar xvJf *.xz )
3. kopieren in das Verzeichnis 
<Interal Storage>/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.mediathekview/

Auf meinem FireTV4K Stick ist 
Interal Storage = /storage/emulated/0

Aber das kann ja keine gewünschte Dauerlösung sein.

**Comment by MartinHH76** [comment]
wie das aber mit der Variente MySQL Server funktioniert ist mir noch etwas schleierhaft. 
Muss man dafür etwa auch erst einmal die SQLlite Datenbankdatei filmliste-v2.db 
entpackt vorliegen, um sie dann in den Server hochzuladen ?

Ich danke schon einmal im Voraus die Antwort.

**Comment by DaDirnbocher** [comment]
> DATABASE_URL = 'https://liste.mediathekview.de/filmliste-v2.db.xz'
> jedoch ist dieser link tot

Vielleicht gab es ja ein temporäres Problem, jedenfalls bekam ich gerade von dem Link ein knapp 60 MB grosses *.xz, also tot scheint der link nicht zu sein.

**Comment by MartinHH76** [comment]
Stimmt, nun funktioniert der link wieder. Jedoch kommt gleich beim Start von Kodi immer noch die Meldung "Mediathekview error : view log". Das log ist hier auch nicht sehr hilfreich.  Es wird versucht auf /tmp, bzw. /usr/tmp zuzugreifen, was so gar nicht existiert und ein Update wird der SqliteDB wird auch nicht durchgeführt.

**Comment by DaDirnbocher** [comment]
> Irgendwelche Ideen ? Danke im voraus.

ijson in der Version 2.5? Wenn ja, dann hilft ein Downgrade:

https://forum.mediathekview.de/post/18722

**Comment by codingPF** [comment]
Hi @MartinHH76,

ich habe für dieses Thema eine fix erstellt der ganz ohne ijson auskommt. Das scheint mir auch der richtige Weg zu sein um Komplexität da raus zu nehmen.
Leider habe ich keine FireTVStick.
Hast du Interesse daran hier zu unterstützen?

**Comment by Marmos76** [comment]
Das wäre super. Kann ich gern ausprobieren. Wo hast Du es ? Local oder bereits committed ?
Viele Grüße,
M.

**Comment by codingPF** [comment]
Super, schau mal hier in den Anhang...geht das so?
[plugin.video.mediathekview-0.6.5.zip](https://github.com/mediathekview/plugin.video.mediathekview/files/4552746/plugin.video.mediathekview-0.6.5.zip)

**Comment by Marmos76** [comment]
Yeahhhhhhh!
Works fine a amazon K4 Stick !! Das ist das was ich benötigt habe!!
 Wie hast Du das hinbekommen ? Ich hatte in den Source Code geschaut und habe den Code komplett nicht verstanden wie die Sqlite Datei heruntergeladen wird ... also den Speicherort. 

Dankeschön !!

**Comment by codingPF** [comment]
Sehr schön...
Ne, dafür musste schon etwas mehr umgebaut werden.
Es wäre schön wenn du noch einen ein paar mal schaust, dass auch neue Sendungen sauber in die Liste aufgenommen werden - also ob der (delta)Updater korrekt funktioniert.

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4
