### ISSUE TITLE
Search for words with dash (e.g. 'Stil-Epochen') doesn't work

### ISSUE THREAD

**Issue by domschl** [mediathekview/plugin.video.mediathekview#15]
It's currently not possible to look for dashed words.

**Comment by tuxpoldo** [comment]
OK - Das Problem ist ein anderes aber hier gibt es trotzdem Potential für Verbesserungen: _"Search in Title"_ sucht im Filmtitel und _"Search in Title and Content"_

Leider hat keiner der Filme der Sendung "Stil-Epochen" den Sendungsnamen im Titel - deshalb wird es auch nicht gefunden.

Es ist aber sinnvoll, dass in beiden Suchen auch im Sendungstitel gesucht wird (Show).

**Comment by tuxpoldo** [comment]
Geplantes Release: 0.3.4

**Comment by domschl** [comment]
Search in 'Title' still doesn't find show names. That can be confusing to users who might identify title and showname.
