### ISSUE TITLE
Not compatible with Kodi 19 (Matrix)

### ISSUE THREAD

**Issue by BugDeliverer** [mediathekview/plugin.video.mediathekview#152]
Kodi 19 (Matrix) has dropped Python v2.x (EOL) and uses Python 3.
The plugin requires Python 2 as a dependency.

**Comment by codingPF** [comment]
Yes, I have been working on Kodi 19 branch and will pushlish it soon.

**Comment by codingPF** [comment]
Merge Kodi19 changes. At the moment we have two addon.xml files which will be used for the different Kodi Repos.

**Comment by BugDeliverer** [comment]
It seems that only the beta repo works with Python 3.
The alpha repo still demands Python 2.
Took some time to figure out but now it's working on latest Libreelec (Milhouse) dev build :)

**Comment by codingPF** [comment]
Kodi 19 requires a different addon.xml (with different version requirements).
There is no way to use the same addon.xml for both.
The code in Beta Repo for beta and alpha is identical beside the addon.xml.

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4
