### ISSUE TITLE
standalone mvupdate+mysql-connector 8.0.15: Database error: -1

### ISSUE THREAD

**Issue by TpmKranz** [mediathekview/plugin.video.mediathekview#157]
Hi, ich versuche, auf einem Ubuntu-19.10-System eine externe Datenbank für das MediathekView-Plugin zu erstellen.

Die Python-Abhängigkeiten habe ich aus den Ubuntu-Repos installiert:
```
python-defusedxml/eoan,eoan,now 0.5.0-1ubuntu1 all [installed]
python-ijson/eoan,eoan,now 2.3-2 all [installed]
python-mysql.connector/eoan,eoan,now 8.0.15-1 all [installed]
python3-defusedxml/eoan,eoan,now 0.5.0-1ubuntu1 all [installed]
python3-ijson/eoan,eoan,now 2.3-2 all [installed]
python3-mysql.connector/eoan,eoan,now 8.0.15-1 all [installed]
```

Das Ausführen von mvupdate mit dem Standardinterpreter (Python 2.7.17) resultiert zunächst einmal in folgender Ausgabe und einem Abbruch: 
[mvupdate.log](https://github.com/mediathekview/plugin.video.mediathekview/files/4558252/mvupdate.log).
Da die letzten Fehler auf Unicode-Probleme hinwiesen, habe ich es mit Python 3.7.5 probiert und es kommt zumindest schon einmal zu keinem Abbruch. Allerdings gehen hier die Probleme erst richtig los: 
[mvupdate3.log](https://github.com/mediathekview/plugin.video.mediathekview/files/4558267/mvupdate3.log).
Nach ein paar Minuten habe ich das dann abgebrochen und die Datenbank sieht eher mau aus: 
[mvupdate3.sql.txt](https://github.com/mediathekview/plugin.video.mediathekview/files/4558278/mvupdate3.sql.txt)

Ist das so gewollt und sollen die vielen Fehlermeldungen ignoriert werden oder mache ich etwas falsch, vielleicht schon beim Installieren der Abhängigkeiten? Vielen Dank für die Aufmerksamkeit und für die Mühen, die in dieses Programm fließen!

**Comment by codingPF** [comment]
Ich hatte ein vergleichbares setup for ein paar Tage aufgesetzt aber den entsprechenden 2.x MySql connector verwendet. Damit ging das auch...den 8.x habe ich noch nicht versucht.

**Comment by TpmKranz** [comment]
Nach `pip3 install --user mysql-connector==2.1.7` (die im README angegebene Version gibt es im PyPI nicht mehr…) füllt sich die Datenbank ohne Probleme, vielen Dank!

In #135 wird Version 8.0.18 benutzt und es scheint, dass die Version von mysql-connector nicht das Problem war. Vielleicht gibt es in 8.0.15 einen Bug, der in 8.0.18 behoben wurde. Nachdem das Update durch ist, werde ich es mal mit `pip3 install --user mysql-connector==8.0.18` versuchen und schauen, ob das was ändert.

**Comment by Marmos76** [comment]
Moin zusmammen, ich habe einmal eine generelle Frage zu der MySQL Variante ....
a) wie wird diese initialisiert ? Wird darauf geachtet, dass wenn die Tabelle nicht vorhanden sind, die erstellt und  dann aktualisiert werden ?
b) was ist wenn sich eine Tabelle ändert ?
c) Was passiert mit der heruntergeladenen sqlitedb Datei (filmliste-v2.db.xz) ? Wird diese nach der synchronizierung gelöscht? 
d) Wie passiert die syschronisierung? Ist das ein Dump ?

Hintergrund ist der dass die Variante mit dem MySQL Server ganz chick finde. Ich habe entspr. Webspace und würde dort gern die MySQL DB Variante nutzen. Macht aber eigenltich nur Sinn, wenn die Datei auch gelöscht werden würde um so Speicherplatz zu sparen. (Gerade auf dem Amazon Fire Stick) 

Danke im Voraus !!

**Comment by codingPF** [comment]
@Marmos76 
Kannst du bitte dazu einen eigenes Thema aufmachen?
Ich würde hier gerne die Treiber geschichte Regel. Fragen zu MySql Variante sind bestimmt auch für andere interessant und dann besser zu finden.

**Comment by TpmKranz** [comment]
Ich habe nun `mysql-connector` 2.1.7 und 2.2.9 aus dem PyPI, `python3-mysql.connector` 8.0.15 aus den Ubuntu-Repos und `mysql-connector-python` 8.0.15, 8.0.16 und 8.0.18 aus dem PyPI getestet.
Das Problem tritt nur auf, wenn in Version 8.0.15 die reine Python-Implementierung anstelle der C-Extension benutzt wird.
In allen anderen Versionen ist es egal, welche Implementierung gewählt wird und 8.0.15 funktioniert, wenn die C-Extension benutzt wird (abgesehen von #160).
Die Ubuntu-Variante kommt ohne Unterstützung für die C-Extension und funktioniert dementsprechend von Hause aus nicht; die PyPI-Version funktioniert nicht, wenn die C-Extension ausgeschaltet wird.
Komischerweise liefert sogar Ubuntu 20.04 noch Version 8.0.15 aus, sodass vielleicht eine explizite Warnung angebracht wäre, in aktuellen Ubuntu-Versionen nicht das Repo-Paket für den Konnektor zu verwenden.
Implizit ist das ja schon dadurch gegeben, dass `pip` empfohlen wird, aber es gibt ja immer Rebellen. :)
