### ISSUE TITLE
standalone mvupdate+mysqldump: PROCEDURE does not exist

### ISSUE THREAD

**Issue by TpmKranz** [mediathekview/plugin.video.mediathekview#159]
Beim Experimentieren mit verschiedenen Versionen von mysql-connector (siehe #157) wollte ich mir etwas Zeit ersparen und eine bereits initialisierte Datenbank für jedes Experiment wiederherstellen (Authentifizierungsoptionen weggelassen):
```bash
mysqldump --extended-insert --lock-tables --databases mediathekview > mvdump.sql
# Experimente
mysql <<< "drop database mediathekview;"
# Experimente
mysql < mvdump.sql
# Weitere Experimente
```
Das resultierte jedoch in unauffindbaren stored Procedures: [mvupdate3-sqldump.log](https://github.com/mediathekview/plugin.video.mediathekview/files/4563729/mvupdate3-sqldump.log) (fragt mich nicht, warum mvupdate die Version 0.0 angibt; die [systemd-Service-Datei](https://github.com/mediathekview/plugin.video.mediathekview/files/4563787/mvupdate.service.txt) dazu könnt ihr gern auch auf Fehler untersuchen).
Ich habe übrigens auch schon ausgeschlossen, dass es am Wechsel von mysql-connector liegt; der Log ist das Ergebnis eines Dump-Drop-Restore mit gleichbleibendem Konnektor (2.2.9).

Habe ich beim Dumpen und/oder beim Wiederherstellen etwas falschgemacht oder ist das eine Einschränkung oder gar ein Fehler in mvupdate?

**Comment by codingPF** [comment]
Die procedures brauchst du beim laden etc. 
Versuch es doch mal mit --routines
[https://dev.mysql.com/doc/refman/8.0/en/mysqldump-stored-programs.html](url)

**Comment by TpmKranz** [comment]
:facepalm: Vielen Dank, ich wusste nicht, dass man Prozeduren-Dumpen separat aktivieren kann/muss.
