### ISSUE TITLE
Falscher Wert für ListItem.SortLetter infolabel gesetzt

### ISSUE THREAD

**Issue by Ch1llb0** [mediathekview/plugin.video.mediathekview#166]
Seit einiger Zeit unterstützt mein Skin die Anzeige des ersten Sortierbuchstaben (oder der -zahl) in Listen, die nach Namen sortiert sind und deren Sortierreinfolge angepasst werden kann. Dies funktioniert wie bei allen anderen Skins, die dies unterstützen, einwandfrei - bis auf zwei Ansichten dieses Addons. Hier werden offenbar falsche Werte für das betreffende Infolabel gesetzt.

Einmal diese Ansicht - Shows sortiert nach Sendern:
![screenshot000](https://user-images.githubusercontent.com/36623079/81173995-46e2d980-8fa1-11ea-8ad1-6e892db73e98.png)

Und diese Ansicht - Shows sortiert nach Titel:
![screenshot003](https://user-images.githubusercontent.com/36623079/81175353-b35ed800-8fa3-11ea-9d52-d68c266d5e92.png)

Beide Male ist oben rechts zu sehen, dass der Buchstabe/die Zahl leer bleibt, obwohl hier etwas angezeigt werden müsste. Mit anderen Skins, die diese Funktion auch unterstützen, passiert dies ebenfalls auf gleiche Art und Weise. So sieht es aus, wenn es korrekt funktioniert:
![screenshot001](https://user-images.githubusercontent.com/36623079/81174000-48ac9d00-8fa1-11ea-8757-9145ed8a9ecf.png)

Bitte löst dies und füllt das Infolabel in allen Ansichten korrekt! 👍

**Comment by Ch1llb0** [comment]
Wow, das war schnell. Vielen Dank! 👍

**Comment by codingPF** [comment]
Gerne..kannst gerne im Master testen

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4
