### ISSUE TITLE
Die https://liste.mediathekview.de/filmliste-v2.db.xz ist korrupt und nicht via 7z zu entpacken...

### ISSUE THREAD

**Issue by DummyDummyDummyDummyDummy** [mediathekview/plugin.video.mediathekview#167]
Hi,

die https://liste.mediathekview.de/filmliste-v2.db.xz scheint derzeit korrupt zu sein.... koennt ihr das einmal pruefen?

Danke....

P.S.  New@github, sorry für Formatierung

root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# wget https://liste.mediathekview.de/filmliste-v2.db.xz
--2020-05-18 22:37:47--  https://liste.mediathekview.de/filmliste-v2.db.xz
Auflösen des Hostnamen »liste.mediathekview.de (liste.mediathekview.de)«... 5.1.92.131, 159.69.182.203, 2a00:f820:417:2:51:92:de2:4e07, ...
Verbindungsaufbau zu liste.mediathekview.de (liste.mediathekview.de)|5.1.92.131|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 307 Temporary Redirect
Platz: https://verteiler3.mediathekview.de/filmliste-v2.db.xz [folge]
--2020-05-18 22:37:47--  https://verteiler3.mediathekview.de/filmliste-v2.db.xz
Auflösen des Hostnamen »verteiler3.mediathekview.de (verteiler3.mediathekview.de)«... 188.68.41.199, 2a03:4000:17:856:18a4:1aff:fe30:5612
Verbindungsaufbau zu verteiler3.mediathekview.de (verteiler3.mediathekview.de)|188.68.41.199|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 18243584 (17M) [application/octet-stream]
In »»filmliste-v2.db.xz«« speichern.

100%[====================================================================================================================>] 18.243.584  57,7KB/s   in 3m 47s 

2020-05-18 22:41:34 (78,6 KB/s) - »filmliste-v2.db.xz« gespeichert [18243584/18243584]

root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# ls -ltra
insgesamt 106336
-rw-rw-r--   1 vdr  vdr    453192 Okt 30  2019 subtitle.ttml
-rw-rw-r--   1 vdr  vdr    115784 Okt 30  2019 subtitle.srt
drwxr-xr-x 110 vdr  vdr      4096 Feb 12 22:32 ..
-rw-rw-r--   1 vdr  vdr      1518 Mai  2 17:01 settings.xml_filme3
-rw-rw-r--   1 vdr  vdr       256 Mai  7 23:05 recent_ext_searches.json
-rw-rw-r--   1 vdr  vdr      6193 Mai 12 16:22 recent_std_searches.json
-rw-r--r--   1 vdr  vdr  89974200 Mai 18 21:51 filmliste-v2.db
-rw-rw-r--   1 vdr  vdr       868 Mai 18 22:16 search_channels.cache
-rw-rw-r--   1 vdr  vdr      8947 Mai 18 22:16 get_shows.cache
-rw-rw-r--   1 vdr  vdr     44267 Mai 18 22:16 search_films.cache
-rw-r--r--   1 root root 18243584 Mai 18 22:35 filmliste-v2.db.xz
-rw-rw-r--   1 vdr  vdr      1486 Mai 18 22:37 settings.xml
drwxr-xr-x   2 vdr  vdr      4096 Mai 18 22:37 .
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# mv filmliste-v2.db filmliste-v2.db.0
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# cp -p filmliste-v2.db.xz filmliste-v2.db.xz.1
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# 7z x filmliste-v2.db.xz ^C
(reverse-i-search)`7': rm -rf "/media/easyvdr01/video0/Im_Zeichen_des_Terrors_-_197^C(8~10)"
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# 7z x filmliste-v2.db.xz && chown vdr:vdr filmliste-v2.db*

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=de_DE.UTF-8,Utf16=on,HugeFiles=on,2 CPUs)

Processing archive: filmliste-v2.db.xz

Extracting  filmliste-v2.db     Data Error

Sub items Errors: 1

root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# ls -ltra
insgesamt 212020
-rw-rw-r--   1 vdr  vdr    453192 Okt 30  2019 subtitle.ttml
-rw-rw-r--   1 vdr  vdr    115784 Okt 30  2019 subtitle.srt
drwxr-xr-x 110 vdr  vdr      4096 Feb 12 22:32 ..
-rw-rw-r--   1 vdr  vdr      1518 Mai  2 17:01 settings.xml_filme3
-rw-rw-r--   1 vdr  vdr       256 Mai  7 23:05 recent_ext_searches.json
-rw-rw-r--   1 vdr  vdr      6193 Mai 12 16:22 recent_std_searches.json
-rw-r--r--   1 vdr  vdr  89974200 Mai 18 21:51 filmliste-v2.db.0
-rw-rw-r--   1 vdr  vdr       868 Mai 18 22:16 search_channels.cache
-rw-rw-r--   1 vdr  vdr      8947 Mai 18 22:16 get_shows.cache
-rw-rw-r--   1 vdr  vdr     44267 Mai 18 22:16 search_films.cache
-rw-r--r--   1 root root 18243584 Mai 18 22:35 filmliste-v2.db.xz.1
-rw-r--r--   1 root root 18243584 Mai 18 22:35 filmliste-v2.db.xz
-rw-r--r--   1 root root 89974200 Mai 18 22:35 filmliste-v2.db
-rw-rw-r--   1 vdr  vdr      1486 Mai 18 22:37 settings.xml
drwxr-xr-x   2 vdr  vdr      4096 Mai 18 22:42 .
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# df -h .
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/sdb1        28G     14G   13G   52% /
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# ls -tlra
insgesamt 212020
-rw-rw-r--   1 vdr  vdr    453192 Okt 30  2019 subtitle.ttml
-rw-rw-r--   1 vdr  vdr    115784 Okt 30  2019 subtitle.srt
drwxr-xr-x 110 vdr  vdr      4096 Feb 12 22:32 ..
-rw-rw-r--   1 vdr  vdr      1518 Mai  2 17:01 settings.xml_filme3
-rw-rw-r--   1 vdr  vdr       256 Mai  7 23:05 recent_ext_searches.json
-rw-rw-r--   1 vdr  vdr      6193 Mai 12 16:22 recent_std_searches.json
-rw-r--r--   1 vdr  vdr  89974200 Mai 18 21:51 filmliste-v2.db.0
-rw-rw-r--   1 vdr  vdr       868 Mai 18 22:16 search_channels.cache
-rw-rw-r--   1 vdr  vdr      8947 Mai 18 22:16 get_shows.cache
-rw-rw-r--   1 vdr  vdr     44267 Mai 18 22:16 search_films.cache
-rw-r--r--   1 root root 18243584 Mai 18 22:35 filmliste-v2.db.xz.1
-rw-r--r--   1 root root 18243584 Mai 18 22:35 filmliste-v2.db.xz
-rw-r--r--   1 root root 89974200 Mai 18 22:35 filmliste-v2.db
-rw-rw-r--   1 vdr  vdr      1486 Mai 18 22:37 settings.xml
drwxr-xr-x   2 vdr  vdr      4096 Mai 18 22:42 .
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# diff settings.xml
settings.xml         settings.xml_filme3  
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# diff settings.xmlÜ
diff: fehlender Operand nach »settings.xmlÜ«
diff: »diff --help« gibt Ihnen mehr Informationen.
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# diff settings.xml*
15,16c15,16
<     <setting id="instanceid" value="" />
<     <setting id="lastactivity" value="1589832979" />
---
>     <setting id="instanceid" value="dab95fe20b4488a26705936640804e65" />
>     <setting id="lastactivity" value="1588431704" />
32c32
<     <setting id="updmode" value="1" />
---
>     <setting id="updmode" value="3" />
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# ls -ltra
insgesamt 212020
-rw-rw-r--   1 vdr  vdr    453192 Okt 30  2019 subtitle.ttml
-rw-rw-r--   1 vdr  vdr    115784 Okt 30  2019 subtitle.srt
drwxr-xr-x 110 vdr  vdr      4096 Feb 12 22:32 ..
-rw-rw-r--   1 vdr  vdr      1518 Mai  2 17:01 settings.xml_filme3
-rw-rw-r--   1 vdr  vdr       256 Mai  7 23:05 recent_ext_searches.json
-rw-rw-r--   1 vdr  vdr      6193 Mai 12 16:22 recent_std_searches.json
-rw-r--r--   1 vdr  vdr  89974200 Mai 18 21:51 filmliste-v2.db.0
-rw-rw-r--   1 vdr  vdr       868 Mai 18 22:16 search_channels.cache
-rw-rw-r--   1 vdr  vdr      8947 Mai 18 22:16 get_shows.cache
-rw-rw-r--   1 vdr  vdr     44267 Mai 18 22:16 search_films.cache
-rw-r--r--   1 root root 18243584 Mai 18 22:35 filmliste-v2.db.xz.1
-rw-r--r--   1 root root 18243584 Mai 18 22:35 filmliste-v2.db.xz
-rw-r--r--   1 root root 89974200 Mai 18 22:35 filmliste-v2.db
-rw-rw-r--   1 vdr  vdr      1486 Mai 18 22:37 settings.xml
drwxr-xr-x   2 vdr  vdr      4096 Mai 18 22:42 .
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# mv filmliste-v2.db^C
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# diff filmliste-v2.db.xz*
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# wget https://mvupdate.yeasoft.com/filmliste-v2.db.xz
--2020-05-18 22:46:10--  https://mvupdate.yeasoft.com/filmliste-v2.db.xz
Auflösen des Hostnamen »mvupdate.yeasoft.com (mvupdate.yeasoft.com)«... 77.232.232.101
Verbindungsaufbau zu mvupdate.yeasoft.com (mvupdate.yeasoft.com)|77.232.232.101|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 70138688 (67M) [application/x-xz]
In »»filmliste-v2.db.xz.2«« speichern.

100%[====================================================================================================================>] 70.138.688  5,78MB/s   in 12s    

2020-05-18 22:46:23 (5,45 MB/s) - »filmliste-v2.db.xz.2« gespeichert [70138688/70138688]

root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# mv filmliste-v2.db.xz
filmliste-v2.db.xz    filmliste-v2.db.xz.1  filmliste-v2.db.xz.2  
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# mv filmliste-v2.db.xz.2 filmliste-v2.db.xz
(reverse-i-search)`7': ^C x filmliste-v2.db.xz 
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview# rm filmliste-v2.db && 7z x filmliste-v2.db.xz && chown vdr:vdr filmliste-v2.db* 

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=de_DE.UTF-8,Utf16=on,HugeFiles=on,2 CPUs)

Processing archive: filmliste-v2.db.xz

Extracting  filmliste-v2.db

Everything is Ok

Size:       423805952
Compressed: 70138688
root@schimi:/var/lib/vdr/.kodi/userdata/addon_data/plugin.video.mediathekview#

**Comment by DummyDummyDummyDummyDummy** [comment]
Sorry.... jetzt funktioniert es wieder?!?!?!
War das jetzt mein Problem...?
Nein, ich habe es 2* heruntergeladen, unabhängig voneinander und einen diff gemacht... also war es nicht mein Fehler. Welchen Provider habt ihr? Der auskommentierte https://mvupdate.yeasoft.com/filmliste-v2.db.xz scheint ja auch zu existieren, oder?

**Comment by codingPF** [comment]
Hi,
Es passiert leider auch mal, dass die Filmliste / DB kaputt ist. In der Regel wartet man dann auf das nächste Update und alles geht wieder
