### ISSUE TITLE
Database Download stalls/blocks closing of Kodi

### ISSUE THREAD

**Issue by Aydan** [mediathekview/plugin.video.mediathekview#168]
I've had it quite often that when the Database Download stalls due to a connection problem, e.g. waking the PC from sleep with the network not yet ready, the download blocks at e.g. 2% forever, also preventing closing Kodi. I have to kill the process to exit Kodi.

Info:
Kodi 18.6 from deb-multimedia on Debian Stretch
Mediathekview 0.6.2 from Kodinerds repo

**Comment by codingPF** [comment]
Added timeout parameter to Urlopen (10 sec) which works for me in case I cut internet connection during download. It will come up with an error message and Kodi can be closed normal.
Seems to work with Kodi 17/18/19.
Currently av. in der branch.

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4

**Comment by Aydan** [comment]
Thanks!
