### ISSUE TITLE
Default Sortierreihenfolge

### ISSUE THREAD

**Issue by imolb** [mediathekview/plugin.video.mediathekview#169]
Danke für die Default-Sortierung aus #71 
Ideal wäre es noch, wenn man auch die _Richtung_ der Sortierung per Default vorgeben kann (auf- oder absteigend). Für mich persönlich ist nämlich meist "Sendedatum absteigend" die hilfreichste Sortierung.

**Comment by codingPF** [comment]
Finde ich auch aber ich habe noch keine Weg gefunden das zu beeinflussen.

**Comment by Ch1llb0** [comment]
Das unterstütze ich... Musste vorher immer beides manuell verstellen. Es ergibt kaum Sinn, aufsteigend nach Datum zu sortieren, wenn es dann auch noch eine zweite Seite gibt. Wäre super, auch dies könnte anpassbar gemacht werden. 👍

**Comment by codingPF** [comment]
Ich habe die Frage mal ins Kodi Forum weitergeleitet...denn ich habe den „Schalter“ dafür nicht gefunden

**Comment by maxberghammer** [comment]
Ja, das wäre echt saustark, wenn das gehen würde!

**Comment by Ch1llb0** [comment]
> Ich habe die Frage mal ins Kodi Forum weitergeleitet...denn ich habe den „Schalter“ dafür nicht gefunden

https://forum.kodi.tv/showthread.php?tid=354867

Wir sind gespannt 👍

**Comment by codingPF** [comment]
Ich habe jetzt mehrfach versucht auf verschidene Arten die Sortierung dem Container mitzugeben aber leider erfolglos...
Man kann das ganze auch aus dem Plugin selbst erzwingen aber das verursacht andere Problem...
@Ch1llb0,
hast du dazu noch ein gute Idee?

**Comment by Ch1llb0** [comment]
Spontan nicht. Eventuell lässt der Blick in den Code anderer Add-ons Schlüsse zu, wie es machbar sein könnte?

**Comment by codingPF** [comment]
Ich habe mich schon mal durch den Krypton branch gearbeitet aber nichts gefunden.
Es gibt in den Skins ab und an mal sowas 
`sortorder="$PARAM[sortorder]"`
Aber das setzten dieses Properties aus dem Addon code hat leider nicht das gewünschte Ergebnis.

Das Youtube plugin sortiert selber die Listen (im Phyton code) und gibt diese dann als NoSort an Kodi. Das ist jetzt nicht wirklich elegant.

Serien will man auch mal nach Name sortieren da diese oft auch richtig als 1 / 2 / 3 / .. hinterlegt sind.
Die "dauer" Serien habe ich als Suche hinterlegt und dort genau einmal die Sortierung auf DESC gestellt. Danach merkt er sich das....So ganz einfach ist die Lösung nicht...Leider gibt es keinen SORT_BY_AGE...

**Comment by Ch1llb0** [comment]
> Das Youtube plugin sortiert selber die Listen (im Phyton code) und gibt diese dann als NoSort an Kodi. Das ist jetzt nicht wirklich elegant.

Naja, das könnte ja aber hier bei diesem Add-on standardmäßig auch so gemacht werden.

> Serien will man auch mal nach Name sortieren da diese oft auch richtig als 1 / 2 / 3 / .. hinterlegt sind.

Wie beim YouTube Add-on auch kann man das ja weiterhin tun. Dort kann auch weiterhin 'Titel', 'Datum', etc. manuell ausgewählt werden. Aber 'Standard' ist eben besagte NoSort was aber real 'Datum' in korrekter Reihenfolge entspricht, was auch hier bei diesem Add-on sinniger Standard sein sollte, meiner Meinung nach.

Eventuell ließe sich ja beides ja kombinieren - die momentane Variante, mit der für das gesamte Add-on ein Sortkey vorgegeben werden kann plus die Variante wie bei YouTube. Somit hätte man Datum in korrekter Reihenfolge plus alle anderen Varianten der Sortierung als Option. Wäre das was?

**Comment by codingPF** [comment]
Ich habe es mal versucht (und die Implementierung ist fertig) aber der Teufel steckt im Detail.
Zum einen, gibt es trotz NO_SORT (oder genau genommen UNSORTED) die Möglichkeit ASC und DESC auszuwählen, was erstmal unschön aussieht aber im wahrsten Sinne des Wortes nichts macht.
Schlimmer aber ist…
Wenn man die Sortierung im UI von NO_SORT auf TITLE wechselt, geht das problemlos. 
Aber wenn man von TITLE auf NO_SORT / Default wechselt, dann passiert nichts da das UI ja nichts zum sortieren hat.
Macht Sinn….aber ob das für den Benutzer so nachvollziehbar ist?

**Comment by Ch1llb0** [comment]
Das ist merkwürdig, da genau diese beiden Vorgänge beim YouTube-Add-on funktionieren. Es kann von 'Default' (no sort) zu 'Title' oder anderem gewechselt werden und wieder zurück - die Sortierung ändert sich dann auch nachvollziehbar. Ebenso kann bei 'Default' (no sort) die Sortierreihenfolge geändert werden (von ASC zu DESC und umgekehrt) und dies hat auch eine sichtbare Auswirkung. Ohne den Code zu kennen - fehlt eventuell noch was, was bei der Methode des YT-Add-ons gemacht wird, um dies beides zu ermöglichen?

**Comment by codingPF** [comment]
Schau dir das bitte nochmal genau an.
Wenn ich das bei mir mache (im YT plugin) passiert genau das was ich beschrieben habe.
Die sortierung "Default" kommt so nicht mehr zurück.

**Comment by Ch1llb0** [comment]
War mir tatsächlich nie aufgefallen - hast recht. Frage ist nun: Ist es das kleinere Übel, die Sortierung so zu basteln oder Datum immer nur standardmäßig falsch herum (dass das falsch herum ist, darauf können wir uns einigen, oder? :) ) zu präsentiert bekommen?

Falls es wirklich keine andere Lösung für dieses Problem geben sollte... Es kann doch nicht sein, dass Kodi für Add-ons, wenn nach Datum sortiert wird, immer nur die verkehrte Reihenfolge anbietet und Devs keine Möglichkeit bietet, dies zu ändern.

**Comment by Ch1llb0** [comment]
Das Problem wurde hier bereits einmal beschrieben: https://forum.kodi.tv/showthread.php?tid=81155

**Comment by Ch1llb0** [comment]
Hilft die Aussage im Kodi Forum, über welches Infolabel die momentane Sortierreihenfolge auszulesen ist, bei der Lösung des Problems?

**Comment by codingPF** [comment]
Nicht wirklich...auch Programm dafür zu verwenden finde ich nicht so toll.
Ich habe jetzt die angesprochene Version fertig gemacht.
Wer testen möchte, kann dies gerne tun.
Ob das dann in den devBranch oder das nächste Release geht...weiß ich noch nicht so richtig.
[plugin.video.mediathekview-0.6.5.zip](https://github.com/mediathekview/plugin.video.mediathekview/files/4809148/plugin.video.mediathekview-0.6.5.zip)

**Comment by Ch1llb0** [comment]
Leider scheint wohl die YouTube-Methode die einzige zu sein, die grundlegend funktioniert, auch wenn sie das angesprochene Problem hat. Ist halt ein Kompromiss.

Werde testen 👍

**Comment by codingPF** [comment]
Ja ist Absicht bzw. liegt das einfach nur daran, dass alle Feature noch nicht gemergt sind/waren. Kommt dann alles zusammen wenn ich die Beta baue...

**Comment by codingPF** [comment]
Kodi Repo Check-in: Version 0.6.6 ist live
