### ISSUE TITLE
Möglicherweise war der Wechsel von ijson zu json nicht die beste Entscheidung

### ISSUE THREAD

**Issue by maxberghammer** [mediathekview/plugin.video.mediathekview#171]
Der json-Parser braucht so viel zu viel Hauptspeicher. Mein Odroid C2 bricht mir (trotz 2GB Hauptspeicher) beim Full-Import so leider mit einem OOM ab. Und was ich gesehen habe scheinen die Jungs mit RasPis das selbe Problem zu haben. Wäre hier ein SAX-Parser nicht die sinnvollere Option, so wie es auch in der 0.6.2 mit ijson noch der Fall war? Ich weiß, SAX ist immer ätzend anzuprogrammieren, aber hier wäre es IMHO der sinnvollere Weg.

**Comment by codingPF** [comment]
Kodi Repo Check-in: Version 0.6.6 ist live
