### ISSUE TITLE
Bitte Fehlermeldung für Datenbank-Download beim Start abschaltbar machen

### ISSUE THREAD

**Issue by M-Reimer** [mediathekview/plugin.video.mediathekview#173]
Mein HTPC wartet vor dem Starten von Kodi nicht auf das Netzwerk. So habe ich schneller Zugriff auf die lokal auf der Platte gespeicherten Daten und bis ich wirklich dazu komme ein Streaming-Addon zu nutzen ist das Netzwerk dann auch da.

Das hat zur Folge das mir das Mediathekview-Addon jetzt bei jedem Start einen Fehler anzeigt bezüglich des Datenbank-Downloads. Wenige Sekunden später führt das Addon wohl selber einen Retry durch und bekommt dann auch die Datenbank.

Bitte diesen Fehler optional machen (in den Einstellungen abschaltbar) oder eventuell intelligenter machen (paar "Frei-Retries" bis der Fehler aufpoppt).

**Comment by codingPF** [comment]
Wie wäre es denn einfach 10 - 20 sec zu warten bevor man das Update startet?
Bei mir laufen beim Boot direkt 3-4 Plugins los und wollen Updates...das finde ich persönlich nervig....

**Comment by codingPF** [comment]
Kodi Repo Check-in: Version 0.6.6 ist live
