### ISSUE TITLE
mvupdate: MySQL Database Error (Encoding?)

### ISSUE THREAD

**Issue by fabiangr** [mediathekview/plugin.video.mediathekview#174]
Hallo,
ich habe mvupdate auf meinem Server nach der aktuellen Anleitung eingerichtet. Das läuft soweit im Zusammenspiel mit dem Kodi Plugin auf einem RPi 3 prima. Beim Update bekomme ich allerdings recht häufig folgenden Fehler:

`2020-07-31 21:17:06.730343 ERROR [mvupdate-0.6.4:StoreMySQL]: Database error: 1366, 1366 (HY000): Incorrect string value: '\xC5\xABs zu...' for column '_description' at row 1`

Meistens betrifft es das Feld `_description`, gelegentlich auch `_title`. Muss ich für das richtige Encoding der Datenbank noch etwas tun?

Ubuntu 18.04, MySQL 5.7.31, mysql-connector 2.2.9, mvupdate current master.
Das Problem tritt sowohl mit mvupdate, als auch mvupdate3 auf.

**Comment by codingPF** [comment]
Ich nehme eigentlich immer den Standard- ohne weitere Änderungen...
Ich bauen die DB jetzt einmal neu auf und schaue ob ich irgendwelche Fehler sehe (das dauert aber ein paar Stunden)...
Bei Google habe ich das hier gefunden...

**Comment by fabiangr** [comment]
Hallo @codingPF ,

danke für die Antwort. Ich habe mittlerweile auch Hinweise gefunden, dass UTF-8 bei MySQL nicht gleich UTF-8 ist. Das "alte" utf8 umfasst wohl nur 3 Byte statt den eigentlich notwendigen 4. Dadurch lassen sich viele Zeichen, die eigentlich im Standard sind, nicht korrekt speichern. Deshalb wurde utf8mb4 eingeführt. 

Ich weiß jetzt aber nicht, an welcher Stelle die Konfiguration vorgenommen werden muss, damit MySQL auch wirklich utf8mb4 nutzt. Es könnte eine allgemeine Konfiguration sein, es könnte mit der Version von MySQL zusammen hängen oder beim Anlegen des Schemas relevant sein. 

Mit MySQL habe ich nicht so häufig zu tun, deshlab kenne ich die Besonderheiten da nicht. Wenn ich Zeit finde, schaue ich mir das Thema noch mal genauer an.

Mich wundert, dass es bisher nicht aufgefallen zu sein scheint. Mein Setup dürfte so selten ja nicht sein.

**Comment by alex1702** [comment]
Beim erstellen der Datenbank muss man utf8mb4 angeben. Dies kann man auch in den Einstellungen vom Server als default hinterlegen.

**Comment by alex1702** [comment]
Ich würde dir übrigens mal MariaDB ans Herz legen, wenn du nicht speziell MySQL wegen irgendeiner Software brauchst die das unbedingt voraus setzt. 

Da dürfte glaub ich utf8mb4 schon default sein.

**Comment by alex1702** [comment]
Hast du die Datenbank selber angelegt oder das Plugin das machen lassen?

**Comment by fabiangr** [comment]
> Beim erstellen der Datenbank muss man utf8mb4 angeben. Dies kann man auch in den Einstellungen vom Server als default hinterlegen.

Habe ich gemacht. Klappt nun auch. :+1: 

> Ich würde dir übrigens mal MariaDB ans Herz legen, wenn du nicht speziell MySQL wegen irgendeiner Software brauchst die das unbedingt voraus setzt.
> 
> Da dürfte glaub ich utf8mb4 schon default sein.

Probiere ich bei Gelegenheit gern mal aus.

> Hast du die Datenbank selber angelegt oder das Plugin das machen lassen?

Die Datenbank habe ich selbst angelegt. Das Schema habe ich mvupdate überlassen.

**Comment by fabiangr** [comment]
Hallo @codingPF , ich muss noch mal ganz blöd fragen: Weshalb dauert denn das Aktualisieren einer MySQL DB so dramatisch viel länger als wenn man SQLite verwendet? Auf meinem Server hat es viele Stunden  gedauert die MySQL initial zu befüllen. Der Prozess lief über Nacht. Das nächste Update war dann schon wieder ein Full Update, sodass es wieder einige Stunden gedauert hätte. Auch du hast oben geschrieben, dass es bei dir einige Stunden dauern würde. Das Aktualisieren der SQLite DB hingegen rattert in unter einer Minute runter.

**Comment by alex1702** [comment]
Wenn es nicht verstellt wurde, dann lädt das Plugin eine fertig generierte SQLite DB von unseren Servern, sodass nur noch die Differenz Listen einsortieren werden müssen. So spart man sich das Zeitintensive erstellen der SQLite DB von der akt Liste.

Ich nutze aktuell auch nur noch das SQLite verfahren bei meinen Kodi Maschinen, weswegen ich grad kein Vergleich habe wie lange der import der Akt-Liste bei mysql dauert.

Ich kann aber sagen, dass das erstellen der SQLite DB auf den Crawlerservern keine Stunden dauert. Eventuell so 10 Minuten.
Eventuell muss man da noch mal genauer analysieren was beim import in MySQL so lange dauern könnte.

**Comment by fabiangr** [comment]
Hi @alex1702, danke für die Erklärung. Ich hab mir das Schema und den Update Code mal angesehen, aber zumindest auf die Schnelle auch keine Hinweise gefunden, was da so absurd langsam sein könnte. Ein Insert von ~350.000 Zeilen sollte mE deutlich schneller gehen können. Mein Python ist aber etwas eingerostet, sodass ich da jetzt keine weitere Zeit investieren mag und lieber wieder zu SQLite auf meinem Raspi wechsle.
