### ISSUE TITLE
Datentyp von ftInsertFilm._aired von TIMESTAMP in DATETIME ändern

### ISSUE THREAD

**Issue by lausitzer** [mediathekview/plugin.video.mediathekview#175]
Ich nutze MariaDB als Backend und sehe wenn der Import der Sendungsdaten läuft in den letzten Monaten immer öfter die Fehlermeldung, dass ein weit in der Vergangenheit liegendes Datum (1969-12-29 12:25:47) kein gültiger Timestamp für _aired sei. Offenbar liegt es an der Prozedur ftInsertFilm, die einen Parameter _aired vom Typ TIMESTAMP hat. Der Wertebereich von TIMESTAMP beginnt erst bei 1970-01-01 00:00:01. Daher wäre es notwendig auf den den alternativen Datentypen DATETIME zu wechseln, was das Problem bei mir behoben hat. 

Zudem muss in der SP die Ersetzungsregel 
`IF(_aired = "1980-01-01 00:00:00", NULL, _aired),`
in
`IF(_aired <= "1980-01-01 00:00:00", NULL, _aired),`
abgeändert werden, damit es dann nicht aus gleichem Grund beim INSERT in die Tabelle film kracht.

**Comment by codingPF** [comment]
Das kann man wahrscheinlich im update parser noch einfacher fangen und dann muss man nicht an die DB / procedure ran.
Ich schau mir das an...

**Comment by gitargui** [comment]
ich hab die rrmote db auf aired typ datetime gesetzt und alle _aired in der StoredProcedure und in /storage/.kodi/addons/plugin.video.mediathekview/resources/lib/storemysql.py angepasst. Der Fehler kam trotzdem wieder. Wo mussmer denn noch was ändern???

gruss mike

**Comment by codingPF** [comment]
Versuch es doch mal bitte mit dem develop master. Da sollte das Problem gefixt sein und du kannst das nächste Release testen 😉

**Comment by codingPF** [comment]
Nachdem ich jetzt einen Bericht gelesen habe, dass alte Filme aus dem Archiven in die Mediathek geladen werden, habe ich diesen Change gemacht und die DB Struktur auf Datetime angepasst. Plus ein paar fixes werden dann jetzt auch die Filme von 1950 sauber angezeigt.

**Comment by codingPF** [comment]
Kodi Repo Check-in: Version 0.6.6 ist live
