### ISSUE TITLE
Anzeige erfolgt in geringster Auflösung

### ISSUE THREAD

**Issue by beate-hub** [mediathekview/plugin.video.mediathekview#179]
Wenn ich einen Livesender starte, dann startet dieser immer mit der geringsten Auflösung. In den Einstellungen ist "HD Streams bevorzugen" eingeschaltet.
Über das Zahnrad kann ich dann die Auflösung anpassen, danach werden auch höhere Auflösungen problemlos abgespielt.

Bei mir lauft Kodi unter Ubuntu 20.04

**Comment by codingPF** [comment]
Die Mediathek selbst kennt erstmal nur einen Link zum Live Stream.
Wenn ich mir die URL (im Browser / VLC) anschaue, dann haben ich auch keine Möglichkeit die Auflösung zu verändern (oder habe diese nicht gefunden).
Was KODI im Menu Settings > Select Program macht, muss ich mal nachlesen. Ich kann dort auch verschiedene Bitraten auswählen…oder beziehst du dich auf eine andere Einstellung?
Das ist jetzt aber erstmal KODI intern…

**Comment by yoshimo** [comment]
Wenn ich mir live.daserste.de anschaue habe ich als playlist
https://mcdn.daserste.de/daserste/de/master.m3u8

`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=4237552,AVERAGE-BANDWIDTH=4118400,CODECS="avc1.640020,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=50.000
master_3744.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2314400,AVERAGE-BANDWIDTH=2156000,CODECS="avc1.4d4020,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=50.000
master_1960.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1477872,AVERAGE-BANDWIDTH=1302400,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=50.000
master_1184.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=677336,AVERAGE-BANDWIDTH=668800,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=512x288,FRAME-RATE=50.000
master_608.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=366168,AVERAGE-BANDWIDTH=352000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=480x270,FRAME-RATE=50.000
master_320.m3u8
`
Da ist durchaus Verschiedenes an Qualität geboten. Von welchem Sender hier aber die Rede ist geht aus dem ersten Beitrag leider nicht hervor.

**Comment by vitusson** [comment]
Ich erinnere mich dass ich mal die gleichen Probleme mit einem anderen ZDF Plugin und Auflösungen beim Livestream hatte und nahezu verzweifelt bin. 
In der Tat war dafür eine Einstellung in einem anderen KODI Plugin zuständig, InputStream Adaptive. Das ist wohl für alles was mit Streams zu tun hat und dort kann man seine min und max Bandbreite und Auflösungen einstellen. Ich kann jetzt nicht mit 100%iger Sicherheit sagen das dies die Lösung ist, aber versuche auf jeden Fall mal dort zu drehen. 
Meine Livestreams in MV-Plugin kommen jedenfalls mit den 720p die ich dort beim InputStream gesetzt habe an.

**Comment by beate-hub** [comment]
Das beschriebene Problem tritt bei mir mit alles Sendern auf. Also z. B. "ZDF Livestream", "3Sat Livestream",... 
Bei "ARD Livestream" verhält es sich anders. Hier wird die höchste Auflösung verwendet. Wenn die Bitrate von Hand umstelle, dann sehe ich, dass immer die Stufe 0 ausgewählt ist. Das ist (bis auf ARD) immer die geringste Bitrate.

@vitusson wo kann ich InputStream Adaptive konfigurieren? Unter Addons finde ich nichts.

**Comment by beate-hub** [comment]
Ich habe jetzt Kodi nochmals deinstalliert und danach neu installiert, da ich "InputStream Adaptive" nich finden konnte. Auch in der neuen Installation war es zunächst nicht zu sehen. Habe es dann mit sudo apt-get install ... versucht zu installieren. Dabei erhielt ich dann die Info, dass es schon installiert sei.

Danach habe ich das Plugin dann gefunden. Jetzt klappt auch das Mediathekview-Plugin korrekt und startet die Streams in der höchsten Auflösung. Allerdings auch bei deaktiviertem InputStream Adaptive.

Ich weiß jetzt also nicht so genau, woran es liegt, aber ich bin happy. Vielen Dank an alle für den Schubs in die richtige Richtung.
