### ISSUE TITLE
MySQL Error im Zeitraum 1950-1969

### ISSUE THREAD

**Issue by Space2Walker** [mediathekview/plugin.video.mediathekview#180]
Ich habe ein neues [Docker Image](https://github.com/Space2Walker/mediathekview-update) zum updaten der DB mit mvupdate3 gebaut und beim ausführen folgenden Fehler bemerkt.

"2020-10-24 03:43:52.462010 ERROR [mvupdate3-0.6.4:StoreMySQL]: Database error: 1292, 1292 (22007): Incorrect datetime value: '1957-04-17 19:30:00' for column '_aired' at row 1" 

Der Fehler beschränkt sich anscheinend auf den oben genannten Zeitraum, und steht wahrscheinlich mit #175 in Verbindung.

**Comment by codingPF** [comment]
Kannst du das ganze einmalm it dem DEV Branch versuchen?
Da sollte entsprechender Fix schon drin sein.

**Comment by Space2Walker** [comment]
Habe ich gerade ausprobiert leider mit einem StopIteration error.
[log](https://pastebin.com/bR8tfe0N)
Und sorry das ich nicht selber drauf gekommen bin denn dev branch zunehmen hab ja #175 gelesen,
war wohl schon etwas spät gestern

**Comment by codingPF** [comment]
Ohje, das scheint an diesem alten MySqlConnector zu liegen...
Mit dem Kodi Connector (script.module.myconnpy 1.1.7) geht es
Mit dem neuesten Connector mysql-connector-python 8.0.22 geht es auch
Nur der alte 2.2.9 scheint da seine Problem zu haben…

Ich werde das morgen mal durchtesten…

**Comment by codingPF** [comment]
Es sollte reichen wenn wir eine Punkt hier offen halten (siehe #175 )
