### ISSUE TITLE
Wrong addon.xml for Kodi 19 Matrix

### ISSUE THREAD

**Issue by ekuester** [mediathekview/plugin.video.mediathekview#185]
If I install the plugin via Kodi 19 Matrix the provided addon.xml is still for Kodi 18 Leia and give the "famous" xbmc.python error. So could you please mention somewhere (maybe in the README.md), that one have to rename the provided addon.kodi19.xml to addon.xml and zip again to obtain the plugin for Kodi 19.
Vielen Dank, many thanks, tante grazie from Krefeld/Germany.

**Comment by codingPF** [comment]
Is there any reason why you are not using the official Kodi Repo?

**Comment by ekuester** [comment]
Caught ;-) But after updating from Kodi 18.9 to Kodi 19.0-7 under Fedora 33 with the old .kodi folder in my home directory there must something go wrong, since the downloaded official plugin gave me the xbmc.python error resulting from not using python-2.7 ... BTW Fedora 33 uses python-3.9 and with the renamed addon.kodi19.xml all works flawlessly.

**Comment by codingPF** [comment]
Adopted Readme.

Not sure on the update...
You are saying, the update from 18 to 19 ended up in a plugin which was not usable?
In the first moment this sounds like a Kodi issue to me...can you reproduce the issue?

**Comment by ekuester** [comment]
To my regret not ... Both my Kodi installations are updated and work as expected. I agree with you, that it is (was?) a Kodi issue, I assume there was some left file from the old version on my computer, which gave the irritations.

**Comment by codingPF** [comment]
Thx for checking.
Read me is up to date.
I will close this one
