### ISSUE TITLE
[feature] Possibility to change language/subtitle feature

### ISSUE THREAD

**Issue by Finnitio** [mediathekview/plugin.video.mediathekview#186]
It would be nice to change between subtitles languages and the language. Since I watch a lot of stuff from arte which has a lot of different OV's.

**Comment by codingPF** [comment]
Not sure I got this? You want to have subtitle in a different language than audio?

**Comment by codingPF** [comment]
Mediathekview film database contains only one subtitle. Therefore this isn’t possible for this plugin. You may rise this to mediathekview mserver
