### ISSUE TITLE
Kodi's Proxy Einstellungen werden nicht beachtet?

### ISSUE THREAD

**Issue by eikek** [mediathekview/plugin.video.mediathekview#188]
Hallo,

erstmal vielen Dank für dieses Plugin! 

ich bin nicht sicher, ob es mein Unvermögen ist – ich habe in den Kodi System-Einstellungen einen http/s Proxy eingetragen. Das Plugin scheint beim Zugriff auf die Streams den nicht zu verwenden. Ist das korrekt, bzw. wäre es möglich (falls dem so wäre), die Proxy-Einstellungen von Kodi zu verwenden?

**Comment by codingPF** [comment]
Die urls werden vom Plugin an den Kodi Player übergeben, Dieser (und somit Kodi) machen dann den Rest.
Meine Erwartung wäre, dass dann auch alle Settings (die für die Kodi gültig sind) verwendet werden.
Wenn ich das bei mir teste, kommt im LOG file auch...
`
2021-01-02 11:54:52.765 T:16808  NOTICE: VideoPlayer::OpenFile: https://apasfiis.sf.apa.at/ipad/cms-austria_episodes/...
2021-01-02 11:54:52.785 T:16808   DEBUG: Using proxy www.xxx.yyy.zzz type 0
`
Leider habe ich keine sinnvollen Proxy-Settings mit dennen man das weiter testen könnte.

**Comment by eikek** [comment]
Vielen Dank für die Aufklärung! Es tut mir leid, ich muss das nochmal bei mir überprüfen, da habe ich offensichtlich irgendwas falsch gemacht.
