### ISSUE TITLE
Total number of channels/shows/films always zero for mysql standalone database

### ISSUE THREAD

**Issue by FeLoch** [mediathekview/plugin.video.mediathekview#190]
First thanks for the nice plugin! As this is my first contribution to this repo, I hope not to post something stupid here :)

By using a standalone mysql database, the total  number of channels/shows/films in the table `status` is always set to zero.

See the example (bold line):
> $ ./mvupdate mysql -u XXXXXXX -p XXXXXXXXX -f -v
> 2021-01-23 12:40:30.061688 INFO [mvupdate-0.6.6]: Startup
> 2021-01-23 12:40:30.061816 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Database driver: External (mysql)
> 2021-01-23 12:40:30.061878 INFO [mvupdate-0.6.6:StoreMySQL]: Using MySQL connector version 2.1.4
> 2021-01-23 12:40:30.064988 INFO [mvupdate-0.6.6:StoreMySQL]: Connected to server localhost running 10.1.47-MariaDB-0ubuntu0.18.04.1
> 2021-01-23 12:40:30.066577 INFO [mvupdate-0.6.6]: Starting up...
> 2021-01-23 12:40:30.067879 INFO [mvupdate-0.6.6]: Initiating differential update...
> 2021-01-23 12:40:30.067928 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Cleaning up old downloads...
> 2021-01-23 12:40:30.067991 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Trying to download Filmliste-diff.xz from https://liste.mediathekview.de/Filmliste-diff.xz...
> 2021-01-23 12:40:30.243653 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Trying to decompress xz file...
> 2021-01-23 12:40:30.264456 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Return 0
> 2021-01-23 12:40:30.264767 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Starting import of 647 records from ./Filmliste-diff
> 2021-01-23 12:40:30.266523 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Initializing update...
> 2021-01-23 12:40:30.389286 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Filmliste dated 23.01.2021, 12:14
> 2021-01-23 12:40:30.389455 INFO [mvupdate-0.6.6:MediathekViewUpdater]: In progress (0%): channels:0, shows:0, movies:0 ...
> 2021-01-23 12:40:30.800201 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Added: channels:0, shows:3, movies:0 ...
> 2021-01-23 12:40:31.417954 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Deleted: channels:0, shows:0, movies:0
> **2021-01-23 12:40:31.418048 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Total: channels:0, shows:0, movies:0**
> 2021-01-23 12:40:31.420524 INFO [mvupdate-0.6.6:MediathekViewUpdater]: 704 records processed
> 2021-01-23 12:40:31.420575 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Import of ./Filmliste-diff in update cycle 0 finished. Duration: 1 seconds
> 2021-01-23 12:40:31.420865 INFO [mvupdate-0.6.6:MediathekViewUpdater]: Cleaning up downloads...
> 2021-01-23 12:40:31.421101 INFO [mvupdate-0.6.6]: Exiting...

It seems, that something is missing in the mysql procedure `ftUpdateEnd`.

**Comment by FeLoch** [comment]
If you agree with me, I can create a pull request, as I have the changes implimented for my local repo.

**Comment by codingPF** [comment]
Thank you for the offer but there will be a Version jump soon and your work will be obsolet...thanks again

**Comment by codingPF** [comment]
If you want, you can do some testing on the dev branch...

**Comment by FeLoch** [comment]
Thanks for the information! I did the same with a new database and the dev branch, but got still the same issue. Seems reasonable to me, as the procedure `ftUpdateEnd` is still the same (compared to master).

**Comment by codingPF** [comment]
I did the update a couple of hours ago....the function is not used or present anymore

**Comment by FeLoch** [comment]
ah, you're right! Seems that my fork is some commits behind. Sorry for this.

**Comment by FeLoch** [comment]
As this issue is not valid for the next version, I'll close it.

Thanks for your patience!
