### ISSUE TITLE
Addon marked broken

### ISSUE THREAD

**Issue by AleXSR700** [mediathekview/plugin.video.mediathekview#191]
Hello everyone, 
I saw that the addon was now marked broken. 

It cannot be used/installed on Kodi 18.x or 19.x.

Was this marked by you or automatically? I could not find any info. I was surprised that it was marked broken on my Kodi 18.x installations also. 

Thank you for your hard work!

**Comment by codingPF** [comment]
Yes, it was marked broken by Team Kodi and we in discussions to resolve this issue.
I am sorry but unthinkable this will take some time...

**Comment by Ch1llb0** [comment]
May we know how this happened? :)

**Comment by codingPF** [comment]
Sure...they looked at the update procedure and have concerns that this kind update is not compliant to there policies.

**Comment by Ch1llb0** [comment]
Ah, I can see here: https://github.com/xbmc/repo-plugins/pull/3387 Hopefully, you can clear this and get the addon back into the repo soon!

**Comment by knoedel001** [comment]
Can you please explain how to create a working ZIP file to install the addon via "Unknown Sources" or provide an own addon repo?

**Comment by appleonkel** [comment]
@knoedel001 
https://kodirepo.mediathekview.de/ I used this one.
There is also a ZIP file for Matrix https://kodirepo.mediathekview.de/repo-beta/plugin.video.mediathekview/plugin.video.mediathekview-1.0.0%2Bmatrix.1.zip

**Comment by knoedel001** [comment]
Thank you!

**Comment by AleXSR700** [comment]
I will keep my fingers crossed that you can resolve the issues without having to do too much additional work.

I do see their point and I was surprised to read that your database approach is for speed purposes. I actually find that on Android SmartTVs the update process of MediathekView is much slower than any other plugin using streaming content (e.g. ran, ProSiebenSat.1, the old mediathek plugins which were replaced by yours, NFL Game Pass, etc.).

**Comment by codingPF** [comment]
That deepens pretty much on what you are up to. Searching in several sources just takes quite long and a DB is faster but if you know that you are looking for - a specific plugin for one single source is surely fast. In case you are just up for a single source, you may want to just simply install this source and do not care for the others.

**Comment by AleXSR700** [comment]
I meant the updating of the database. That is not dependend on the network speed but the device speed. So you have to wait until that process is done. A live update directly via the API is much faster than creating/updating an entire database.

**Comment by codingPF** [comment]
We have not been able to bring this dission to a good end. 
Therefore new releases will be added to our [Repo](https://github.com/mediathekview/kodi-repos) from now on.

**Comment by beta-tester** [comment]
can you please add a note to the "[Install](https://github.com/mediathekview/plugin.video.mediathekview#install)" and "[Installation](https://github.com/mediathekview/plugin.video.mediathekview#installation)" section of the README.md file.
it took me quite some time to figure out how to install this add-on for Kodi 19.

**Comment by codingPF** [comment]
> can you please add a note to the "[Install](https://github.com/mediathekview/plugin.video.mediathekview#install)" and "[Installation](https://github.com/mediathekview/plugin.video.mediathekview#installation)" section of the README.md file.
> it took me quite some time to figure out how to install this add-on for Kodi 19.

Please feel free to make suggestion here/in a new issue or directly via PR…

**Comment by beta-tester** [comment]
i was so free and created a pull request
 Installationsverweis auf mediathekview/kodi-repos #210

**Comment by codingPF** [comment]
Released als 1.0.9
