### ISSUE TITLE
Landscape fanart & contentid change

### ISSUE THREAD

**Issue by Ch1llb0** [mediathekview/plugin.video.mediathekview#194]
Ich möchte zwei neu aufgetauchte Probleme der neuen 1.0.0-Version vermelden.

1. Der content type wird, unabhängig vom content type-Setting in den Einstellungen des Addons, in den ersten Listen _Livestreams_, _Kürzlich hinzugefügt_ und _Durchsuchen_ auf _movies_ gesetzt und sorgt damit für eine merkwürdige Darstellung in Skins, die content types zur Zuweisung bestimmter Darstellungen z.B. von Listen nutzen. Kann in dieser Liste der Sender der content type wie bei älteren Versionen wieder leer bleiben? Er ist korrekt leer, wenn man eine Ebene weiter geht und die Liste der Sendungen eines Senders aufruft.

2. In der neusten Version werden die Icons für Sender und Sendungen (letztendlich alle Icons, die das Addon bietet) auch als ListItem.Art(fanart) gesetzt. Damit tauchen diese, je nach Skin, riesig und unscharf im Hintergrund auf. Ist es möglich, dies wieder rückgängig zu machen und das Infolabel ListItem.Art(fanart) leer zu lassen?
Fanart sollte eher ein hoch aufgelöstes, möglichst 16:9-kompatibles Bild sein, was (wie ich verstehe) leider bei den einzelnen Sendungen über das Mediathekview-Backend nicht bereitgestellt werden kann. Enstprechend wäre keines dann allerdings IMHO eleganter.

Ein Screenshot, der beide Probleme gut demonstriert:

![screenshot00001](https://user-images.githubusercontent.com/36623079/111875182-c51d5400-8998-11eb-9ca4-d32e7179fafa.png)

Danke für die tolle Arbeit an diesem Addon!

**Comment by codingPF** [comment]
Das wird jetzt etwas schwierig...denn über Geschmack lässt sich bekanntlich (nicht) streiten.

Punkt 1:
Den Content Type "movies" habe ich gesetzt damit man die View "Wall" verwenden kann. Diese ist für content type "leer" nicht verfügbar. Bei "leer" gibt es nur die View "IconWall" und dort passen nur 4 Sender (IconWall) in eine Zeile (anstatt 6 Sender bei Wall)...

![livestream](https://user-images.githubusercontent.com/12601561/111880531-6661d580-89ac-11eb-8841-b9cc1c99c2b6.png)

Punkt 2:
Ich hatte irgendwann alle "icons" gesetzt und fand diesen unscharf Effekt gut...das ist jetzt Geschmackssache


Vielleicht bekommen wir hier noch ein paar Meinungen dazu?

**Comment by Ch1llb0** [comment]
> Den Content Type "movies" habe ich gesetzt damit man die View "Wall" verwenden kann. Diese ist für content type "leer" nicht verfügbar. Bei "leer" gibt es nur die View "IconWall" und dort passen nur 4 Sender (IconWall) in eine Zeile (anstatt 6 Sender bei Wall)...

Hm... Das ist das Problem mit content types, wenn ein Addon sie setzt. Kodi sieht vor, dass Video-Addons dies ausschließlich mit dem type _videos_ tun sollte, nicht mit anderen. Skins sollten an content types angepasste Ansichten haben, nicht Addons content types setzen, damit bestimmte Ansichten erzwungen werden - das sage ich als Skinner, der darauf angewiesen ist, dass Addons berechenbar nach Vorgaben content types setzen. Ich wäre sehr dankbar, wenn dieses Addon dies wie andere tun könnte 👍🏻 

> Ich hatte irgendwann alle "icons" gesetzt und fand diesen unscharf Effekt gut...das ist jetzt Geschmackssache

Ja, dieser Punkt ist sicherlich Geschmackssache. Auch hier ist das Problem, dass es mit einem Skin wie Estuary in Ordnung aussieht, mit einem Fanart-zentrierteren Skin wie dem OSMC Skin allerdings weniger. Wäre hier ein Kompromiss möglich? Z.B. hochauflösendere, auf 16:9 ausgelegte Fanarts für jeden Sender und nicht nur die Icons doppelt? :)

**Comment by codingPF** [comment]
1. Den Type auf "Video" zu ändern wurde es auch tun, da unter Video die "Wall" verfügbar ist.

> Kodi sieht vor, dass Video-Addons dies ausschließlich mit dem type _videos_ tun sollte,

Vielleicht kannst du dazu mal die Doku linken? Kann ja nie schaden mal was neues zu lesen.

2. Bilder

> hochauflösendere, auf 16:9 ausgelegte Fanarts

Das wird schwieriger. Die Repos aus dennen die Sender kommen, haben i.d.R. nur 256x256.
Hast du eine Hochauflösende Quelle?

3. Sieht komisch aus.



>     und sorgt damit für eine merkwürdige Darstellung in Skins

Kannst du das vielleicht noch etwas genauer fassen? Ich habe mir grade mal das OSMC skin installiert und finde es eigentlich gut...wahrscheinlich weil ich es nich anders kenne !?

![osmc2](https://user-images.githubusercontent.com/12601561/111915112-fcf9c980-8a74-11eb-9c7e-fdf71402856b.png)

**Comment by Ch1llb0** [comment]
1. Wo dies im Kodi wiki und bei github ausgeführt wird, hatte ich schon einmal in einem anderen issue verlinkt: https://github.com/mediathekview/plugin.video.mediathekview/issues/126#issuecomment-695212944

Item-Listen, die selbst keine Videos enthalten (wie übergeordnete Listen mit Sendern) haben entsprechend, wie zb im Youtube addon, das von Kodi devs bei git als Referenz erwähnt wird, keinen content type.

2. Spontan habe ich keine Idee, woher man kuratiert und unkompliziert hochauflösendere Bilder erhalten kann. Allerdings sind niedrig aufgelöste fanart Bilder auch von Kodi als nicht wünschenswert anzusehen (https://kodi.wiki/view/Artwork_types#fanart). Darauf verlässt sich zb der OSMC Skin und daher merke ich es an.

3. Eigentlich bezieht sich das sehr auf 2. Die gute Sichtbarkeit des fanart ist beim OSMC Skin darauf ausgelegt, hoch aufgelöste Bilder prominent zu zeigen. Daher sehen dann unscharfe, niedrig aufgelöste Bilder "komisch" aus.

**Comment by codingPF** [comment]
1. Schade...ich dachte hier gäbe es noch mehr als "mach mal wie bei Youtube".
2. Ich schaue mal ob ich weitere Bilder finde und baue die dann gerne ein...

**Comment by Ch1llb0** [comment]
1. Die Dokumentation ist leider etwas lückenhaft, ja. Ist für Skinner entsprechend auch frustrierend... Wäre videos für die video listen und kein content type für die normalen item listen möglich? Verstehe die Angelegenheit mit Estuary, dass dort manche Ansichten nicht verfügbar sind. Das ist natürlich in manchen Fällen unschön, allerdings funktioniert das Problem auch anders herum: Es sind dann plötzlich Ansichten eines skins verfügbar, die mit der Liste nicht funktionieren.

Beim OSMC Skin sind das zb Ansichten, die extra Platz für Informationen der movie library anzeigen. Der Platz bleibt dann aber frei und die Ansicht bietet plötzlich zu viel white space. Um da die Ansichten konsistent zu halten, sind die content types sehr praktisch.

2. Super, danke! 👍🏻

**Comment by Ch1llb0** [comment]
1. Die Dokumentation ist leider etwas lückenhaft, ja. Ist für Skinner entsprechend auch frustrierend... Wäre videos für die video listen und kein content type für die normalen item listen möglich? Verstehe die Angelegenheit mit Estuary, dass dort manche Ansichten nicht verfügbar sind. Das ist natürlich in manchen Fällen unschön, allerdings funktioniert das Problem auch anders herum: Es sind dann plötzlich Ansichten eines skins verfügbar, die mit der Liste nicht funktionieren.

Beim OSMC Skin sind das zb Ansichten, die extra Platz für Informationen der movie library anzeigen. Der Platz bleibt dann aber frei und die Ansicht bietet plötzlich zu viel white space. Um da die Ansichten konsistent zu halten, sind die content types sehr praktisch.

2. Super, danke! 👍🏻

**Comment by codingPF** [comment]
Schick mir doch mal was du siehst und was du erwartest. Dann kann ich das hier Lokal nachvollziehen...

**Comment by Ch1llb0** [comment]
Z.B. die Ansicht "Wall info" des OSMC Skins ist für Serien, Seasons oder Filme in der Kodi-Bibliothek mit einer hinterlegten Beschreibung oder eben Videos mit Beschreibung eines Video-Addons gemacht. Entsprechend setzen sie auf den korrekt gesetzten content type (movies, tv shows, seasons, videos). Wird der content type nun in einer Liste gesetzt, die für keinen Eintrag solche Informationen zur Verfügung stellt, sieht es so aus:

![screenshot00000](https://user-images.githubusercontent.com/36623079/112214065-0fb00200-8c1f-11eb-92e3-b27d54e0930f.png)

Das ist nicht, vofür die Ansicht gemacht ist. Die Kontrolle hier drüber sollte entsprechend beim Skin liegen. Auch andere Skins machen das - Estuary ist da sogar meist sehr großzügig und bietet fast alle Ansichten überall an, egal welcher content type gesetzt ist. Umso angepasster die Ansichten allerdings sind, um eher greift die (zugegeben eher schlecht dokumentierte) Ansatz von Kodi, dass der content type grundlegende Steuerungsmöglichkeit der Skins ist, um spezifisch an Inhalte anpassen zu können.

In einer Liste, die videos enthält (und entsprechend meiner Einstellung in den Addon-Einstellungen des Mediathekview-Addons den content type "videos" gesetzt hat), sieht es dann sinnvoll und korrekt aus:

![screenshot00001](https://user-images.githubusercontent.com/36623079/112214072-1179c580-8c1f-11eb-9eb3-6c4d1c35aa87.png)

**Comment by alex1702** [comment]
Und wenn man einfach bei den Sendern noch Erklärtexte von wikipedia hinzufügt?

> Punkt 2:
>Ich hatte irgendwann alle "icons" gesetzt und fand diesen unscharf Effekt gut...das ist jetzt Geschmackssache

>Vielleicht bekommen wir hier noch ein paar Meinungen dazu?

Ich finde den unschärfe Effekt auch nicht schlimm.
Hatte schon überlegt, falls man unterschiedliche Bilder fürs Icon und das große Bild setzen kann, ob man nicht Screenshots von den Mediatheken macht und diese dann vllt auch ganz leicht unscharf dort einbindet.
Das müsste man eventuell mal ausprobieren wie das aussieht.

**Comment by Ch1llb0** [comment]
> Und wenn man einfach bei den Sendern noch Erklärtexte von wikipedia hinzufügt?

Ich habe einen anderen Teil noch nicht einmal angeführt: Es fehlen _alle_ zusätzlichen Informationen, die eine Ansicht mit dem content type _movies_ zur Verfügung stellen würde. In einer korrekten Liste gäbe es zusätzlich sekundäre Informationen neben den Beschreibungstexten, die in einer zweiten Zeile unter den jeweiligen Listentiteln (oder bei Wall oder anderen Ansichten an anderer Stelle) angezeigt werden würden:

![screenshot00000](https://user-images.githubusercontent.com/36623079/112479326-3aac6a00-8d75-11eb-82eb-2daf375a2500.png)

All diese Felder, die für _movies_-spezifische Informationen vorgesehen sind (jeder Skin hat da eigentlich in irgendeiner Form speziellen Platz für vorgesehen), bleiben mit einer reinen Senderliste wie auch mit anderen Listen des Mediathekview-Addons leer. Ich sehe keine realistische Möglichkeit, dies zu ändern. Aber eventuell über sehe ich da auch was.

> Ich finde den unschärfe Effekt auch nicht schlimm.

Der Unschärfe-Effekt aufgrund (zu) niedriger Auflösung im Hintergrund ist halt nicht das, was vom Skin und Kodi intendiert ist. Auch sollte Fanart im Hintergrund das Hintergrundbild des Skins überdecken, was normales Fanart auch tut... (Teil-)transparente Icons aber eben nicht.

> Hatte schon überlegt, falls man unterschiedliche Bilder fürs Icon und das große Bild setzen kann, ob man nicht Screenshots von den Mediatheken macht und diese dann vllt auch ganz leicht unscharf dort einbindet.
> Das müsste man eventuell mal ausprobieren wie das aussieht.

Das klingt nicht schlecht. 👍🏻 

---

Wenn ich es mir wünschen dürfte, wäre es schön, wenn das Addon überall in Listen, die Videos mit zusätzlich hinterlegten Informationen auflisten, fest den content type _videos_ setzen würde, der für Video-Addons vorgesehen ist, in normalen Item-Listen keinen (wie dies auch andere Addons korrekt tun) und im Hintergrund wenn bildfüllende, hoch genug auflösende Fanart anbietet. Dann würde das Addon die Informationen korrekt zur Verfügung stellen und alles weitere den Skins überlassen. Wenn die Darstellung nicht ganz dem eigenen Geschmack entspricht, dann liegt dies am Ende ja eher am Skin, als daran, dass das Addon den Skin nicht so, wie gewünscht, dazu zwingt, es anders als vom Skin intendiert anzuzeigen. Das ist meine Perspektive als Skinner.

**Comment by Ch1llb0** [comment]
Wie ist der Stand der Überlegungen hierzu? Würde mich sehr über Veränderungen freuen, wenn mein Input denn überzeugend war 👍🏻

**Comment by codingPF** [comment]
Eigentlich wird alles was hier aufläuft irgendwann auch umbaut...in welcher Form oder wann kann ich dir noch nicht sagen...

**Comment by codingPF** [comment]
Ich habe jetzt die Bilder neu gebaut. Ich glaube es hätte schon gereicht auf 16x9 zu gehen...ich vermute Kodi skaliert da irgendwie rum und dadurch werden die Bilder unscharf...
Die Version ist im Alpha/Beta Repo

**Comment by Ch1llb0** [comment]
Ich bitte die verspätete Rückmeldung zu entschuldigen!

Der korrigierte ContentType in den Listen ist perfekt, vielen Dank 👍🏻 

Mit den Hintergrundbildern kann ich mich nicht wirklich anfreunden... Sie sind jetzt zwar hochauflösend, allerdings jetzt durch den fehlenden Rand um sie herum bildschirmfüllend bis an die Ränder dargestellt und je nach Farbe des Skins mal besser, mal schlechter zu erkennen. Monochrom und mit Rand wären sie mMn mit erheblich mehr Farben, Skalierungsarten (bildfüllend, etc.) und somit Skins kompatibel. Hier zwei Beispiele davon, was ich meine:

![screenshot00000](https://user-images.githubusercontent.com/36623079/127152634-d88b3229-249c-43f1-9de8-d781f64af0d1.png)
![screenshot00001](https://user-images.githubusercontent.com/36623079/127152636-7f061469-7492-49f1-bccf-f0e5616497a9.png)

Ließe sich da noch was anpassen? Ich denke, dass es nicht nur eine Anpassung an den OSMC Skin wäre, aber die Hintergrundbilder und Icons kompatibler machen würde (obwohl ich persönlich die Bilder im Hintergrund immer noch gänzlich weglassen würde, wie es zuvor war).

**Comment by Ch1llb0** [comment]
Gibt es hierzu Neuigkeiten? :)

**Comment by codingPF** [comment]
Released als 1.0.9

**Comment by Ch1llb0** [comment]
Dieser Issue ist geschlossen worden, allerdings hat sich bezüglich der Fanart nichts in 1.0.9 geändert - es fehlen einige und sie haben alle keinen Whitespace-Rahmen, um die Kompatibilität mit Skins zu erhöhen (wie erläutert). Kann sich hier noch etwas tun, @codingPF? 😃
