### ISSUE TITLE
Possibility to download multiple episodes at once

### ISSUE THREAD

**Issue by AleXSR700** [mediathekview/plugin.video.mediathekview#196]
Hello,

I was wondering if it is somehow possible to download either a show with all of the episodes or somehow mark e.g. all search results for download?
My kids and I love the zoo shows and I would like to download them for a vacation. But it would take forever to download the short episodes one by one.

Would be a cool feature, if it is not already somehow possible.

Thank you for your consideration :)
Alex

**Comment by codingPF** [comment]
Let me check if this somehow fits into the search option without breaking everything

**Comment by codingPF** [comment]
You can have a try on the [Kodi Alpha/Beta Repo](https://github.com/mediathekview/kodi-repos)

**Comment by AleXSR700** [comment]
That is very, very cool! Thank you very much. I am doing a few test runs but so far it seems to be working nicely :-)

I don't want to cause extra work, but would the same menu item also work in the TV Shows list? Sometimes shows don't carry their usual names in the title, so they will show up in the shows item but not in the search results.
But only if that's not too much work of course :-)

**Comment by codingPF** [comment]
Added the new version to Kodi Alpha/Beta Repo.

I did remove the download HD option and moved it to settings ("download quality").
The context option is now av. for all sections (quick search, search, browse).

Hopefully there are not too many bugs. You testing and feedback is welcome.

**Comment by codingPF** [comment]
Released als 1.0.9
