### ISSUE TITLE
Arte Serie Salamander nicht gefunden

### ISSUE THREAD

**Issue by AnnaHolzgrat** [mediathekview/plugin.video.mediathekview#198]
Meine Datenbank ist angeblich aktuell (22.4.2021, 20:32:00) und enthält 451957 Filme (genauso wie das Mediathekview-Programm auf Windows). Ich finde aber die Serie "Salamander" auf Arte nicht - weder mit der Suche noch wenn ich über "Arte-Fernsehfilme und Serien - Serien" alles durchschaue. Ein paar andere Filme, die ich testweise gesucht habe, werden gefunden. Ich habe das Mediathekview-Addon bereits deinstalliert und neu installiert, das hat nicht geholfen. Ich verwende das Mediathekview-Addon 1.0 (Leia) für den Raspberry Pi 4 und die interne SQLite-Datenbank.

**Comment by codingPF** [comment]
Hi,
es gibt unter Einstellungen eine Option "Keine Filme aus der Zukunft". Diese Option ist im default aktiv und schließt Sendungen (oft Trailer) mit Ausstrahlungsdatum > heute aus.
Du kannst jetzt diese Option in den Einstellungen deaktivieren oder diese Einstellung in einer Suche verändern (keine Trailer: No).
Dann findet er diese Serie auch.

PS. Für solche Fragen ist das [Forum](https://forum.mediathekview.de/) auch immer ein guter Ort

**Comment by AnnaHolzgrat** [comment]
Super, jetzt klappt alles! Danke für die schnelle Antwort und sorry für den falschen Frageort, zukünftig nehme ich das Forum.

**Comment by codingPF** [comment]
Es gibt keinen falschen Frageort 😉
