### ISSUE TITLE
ATV4 - Download Database failed - Subprocesses are not supported

### ISSUE THREAD

**Issue by petsander** [mediathekview/plugin.video.mediathekview#199]
Hallo,

leider kann ich das MediathekView Addon Eurer Kodi 19 (Matrix) Repository (stable) nicht nutzen, da die Datenbank mit folgendem Hinweis nicht downgeloadet werden kann: „Fehler beim Herunterladen von decompress failed. Subprocesses are not supported on this platform“. Ich nutze Kodi 19 auf ATV 4. Ebenso getestet habe ich die Version Eurer Kodi 19 Beta Repo - mit gleichem Ergebnis.

Habt Ihr einen Tipp, wie ich dies lösen kann?

**Comment by codingPF** [comment]
Ist auf dem ATV4 XZ installiert?
Wenn ja, kannst du es kurzfristig weg nehmen und prüfen ob es dann klappt?
Alternativ zum (deinstall von XZ) könnte ich dir die Code Zeile geben und du änderst das lokal...was einfacher für dich ist.

Das Problem wird auch im Kodi Forum beschrieben...es scheint nicht wirklich einfach zu sein Kodi auf ATV 4 zu betreiben...

**Comment by codingPF** [comment]
No response….closing
