### ISSUE TITLE
Listen oeffnen oft sehr langsam (oder haengen)

### ISSUE THREAD

**Issue by kaymes** [mediathekview/plugin.video.mediathekview#203]
Ich habe es immer mal wieder dass das Mediathekview Plugin Programm- oder Filmlisten nur sehr langsam oeffnet und anzeigt.
Wenn ich auf "Browse Shows" gehe, werden die Sender schon merklich langsamer angezeigt.
Wenn ich dann einen sender (z.B. ZDF) auswaehle, dauert es sehr lange bis die Liste der Sendungen angezeigt werden. Manchmal dauert es Minuten. Meist dauert es so lange dass ich frustriert neu starte.

Manchmal ist das Problem nach einem Reboot behoben, aber nicht immer. Was immer hilft ist manuell ein komplettes Datenbankupdate durchzufuehren.

Ich habe nichts aussergewoehnliches in den logs gefunden. Auch ist wenn es haengt die CPU-Auslastung minimal.
Ich weiss, das ist nicht viel um die Ursache einzugrenzen. Gerne mache ich weitere Tests wenn es wieder auftritt.

Mein System ist Libreelec 9.2.7 (Laia) auf einen Raspberry 4.
das Mediathekview plugin ist version 1.0.0

**Comment by codingPF** [comment]
Welche Kodi Version ist das?
Wie ist der Update Mode eingestellt? 
Im normal Fall würde er die DB so oder so einmal pro Tag neu erstellen/laden. Das passt zu dem "manuell ein komplettes Datenbankupdate durchzufuehren" nicht so ganz...
Du kannst im Kodi->System das Log level auf DEBUG schalten.
Dann solltet du im Log sachen finden wir 

> INFO: [plugin.video.mediathekview-1.0.5:MediathekViewPlugin]: request processed: 0.0124831199646 sec

Was ist denn für die lange? Bei mir kann es auch mal passieren das es beim ersten öffnen 10 sec dauert...

**Comment by kaymes** [comment]
Die Kodi Version ist Leia (18.9.0)

Meine aktuellen Database Einstellungen sind:
Database type: internal (sqlite)
Fast Native Updates: aktiv
Database update mode: Continuously
Update interval: 24 hours
Update Batch Size: 10000

Fuer das manuelle db update stelle ich den update mode auf "manual" um.

Ich habe die Zeiten nie gestoppt. Wenn es so langsam ist wuerde ich folgendes schaetzen:
Die Senderliste dauert 10-30 Sekunden. 
Dann die Programmliste aufzurufen dauert mehrere Minuten. Meist gebe ich auf und reboote, sodass ich nicht wirklich weiss wie lange es wirklich dauern kann und ob es wirklich immer irgendwann kommt. Es gab aber auf jeden Fall faelle wo nach ein paar Minuten die Liste angezeigt wurde.

Ich werde versuchen das naechste mal wenn es passiert ein debug log einzufangen.

**Comment by alex1702** [comment]
Und auf was für einer Hardware läuft es?

**Comment by codingPF** [comment]
No follow up….closing
