### ISSUE TITLE
Suchfeld "Show + Titel"

### ISSUE THREAD

**Issue by WilmaMortens** [mediathekview/plugin.video.mediathekview#204]
Das MediathekView Plugin ist mein meistgenutztes Plugin in Kodi!
Ich habe allerdings Schwierigkeiten mit der Suche. Am Beispiel der neuen Serie "Schneller als die Angst" (ARD) habe ich ausprobiert, was das Problem ist: ich habe im Suchfeld "Titel" eingegeben "Schneller als die Angst", aber "Schneller als die Angst" ist in der SQLite-Datenbank nicht der "title", sondern der "showname" der Serie. 
Wenn ich in MediathekViewWeb suche, finde ich die Serie sofort. Dort gibt es nur ein einziges Suchfeld und ich vermute, dass "showname" und "title" einfach aneinander gehängt werden und dann darin gesucht wird - jedenfalls finde ich die Serie auch, wenn ich bei der Suche 
	Folge 4 Vergeltung
eingebe oder gar
	Angst Folge 4

Könnte ein solches Suchfeld auch im Plugin eingebaut werden - entweder als Ersatz für show und title oder als neues Suchfeld? Das wäre toll!

**Comment by codingPF** [comment]
Wenn du die "schnelle Suche" (Quick Search) verwendest, dann wir ein Filter auf Title und Show generiert. Damit finde ich deine Serie mit allen folgend sofort (achtung den "no Trailer" Filter musste ich entfernen weil das Ausstahlungsdatum in der Zukunft liegt).
Sonst kann man mit der "Suche" auch alle Filter selber setzen, so wie man es braucht.
