### ISSUE TITLE
Python 3.10.1 - register_adapters_and_converters - issue on RP3 - Kodi 19.3-3 

### ISSUE THREAD

**Issue by ErnstNeger** [mediathekview/plugin.video.mediathekview#205]
Hi,

writing this in English to achieve the widest reach.

I just installed a fresh Kodi ([19.3-3](https://archlinuxarm.org/packages/armv7h/kodi-rpi)) on a RapsberryPi 3 running an up-to-date ArchLinuxARM.

Installing the latest version of the addon from the [Matrix repository](https://kodirepo.mediathekview.de/repo-matrix/repository.mediathekviewmatrix/repository.mediathekviewmatrix-1.0.zip) seems to break _all_ other addons in Kodi. I confirmed that for my setup by doing a fresh install after encountering the issue and finding the same result.

Here's what I did:

- I installed Kodi from scratch `(sudo pacman -S kodi-rpi kodi-rpi-dev kodi-rpi-eventclients`).
- I installed Kodi addons [Inputstream adaptive](https://aur.archlinux.org/packages/kodi-addon-inputstream-adaptive-any/) and [Inputstream RTMP](https://aur.archlinux.org/packages/kodi-addon-inputstream-rtmp-git/) from AUR.
- I rebooted.
- I updated the entire system using `sudo pacman -Syu`, nothing to do.
- I check [dmesg](https://paste.kodi.tv/ukopuyiver), nothing suspicious.
- I started my configured VPN client, no issues there.
- I started Kodi using `sudo systemctl start kodi.service
- I enabled Kodi logging right away (I got asked whether I want to activate the RTMP addon with a pop-up prior to enabling the logging).
- I installed the [DNS Leak Test](https://github.com/Space2Walker/plugin.program.dnsleaktest/archive/refs/tags/v1.1.3.zip) addon to be able to test my VPN connection.
- I started the DNS Leak Test addon (started and DNS was not leaking 🥳).
- I installed latest version of the MediathekView addon from the repository.
- I started MediathekView (nothing happening, blue circle just turning for ages).
- I quit MediathekView (luckily Kodi has _not_ crashed at that point) and go back to the addon home screen.
- I started the DNS Leak Test addon _again_ (it did _not_ start, the blue circle was just turning for ages).
- Figuring the problem would be with the MediathekView addon, I tried uninstalling the addon which failed and Kodi crashed (this is the point where my [kodi.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7818292/kodi.log) ends.
- I had to _ungracefully_ stop Kodi using `systemctl stop kodi.service`, maybe the [output](https://paste.kodi.tv/gaperetefe) while it was stoping is interesting.
- After a reboot (Arch was still responsive at this point) I could disable the MediathekView addon and tried uninstalling it again which worked this time.
- At that point I found the latest [kodi_crashlog-20220105_183945.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7818294/kodi_crashlog-20220105_183945.log) (previous ones show very similar if not identical logs).

The crash log (to me) suggests some kind of issue with time/date, so I checked my setup using `timedatectl` but it seems [ok](https://paste.kodi.tv/xamezorato).

I have absolutely no clue what the issue might be, so I'm happy if anyone can guide me somewhere. Of course, the root cause might be with Kodi or my setup as well, I just figured this would be a good starting point. I'm happy to post somewhere else as well if I have some reasonable hints to do so at lest 😄 

Thanks and best regards.

**Comment by codingPF** [comment]
The last step in your logfile is the download and decompress of the movie DB.
`2022-01-05 18:20:22.635 T:720     DEBUG <general>: [plugin.video.mediathekview-1.0.0+matrix.1:UpdateFileDownload]: decompress xz 0 in 38.24269223213196 sec`
The next step would be rename of the decompressed file (as per below log file from my installation):
`[plugin.video.mediathekview-1.0.0+matrix.1:UpdateFileDownload]: renamed [...]tmp_filmliste-v3.db to [...]filmliste-v3.db in 0.003 sec`
I think you should check the path if the file has been downloaded / compressed and try to rename it. Maybe you sent a listing of the diretory.
`2022-01-05 18:19:44.392 T:720     DEBUG <general>: [plugin.video.mediathekview-1.0.0+matrix.1:UpdateFileDownload]: downloaded /home/kodi/.kodi/userdata/addon_data/plugin.video.mediathekview/tmp_filmliste-v3.db.xz in 16.130406618118286 sec`

**Comment by ErnstNeger** [comment]
Hi,

unfortunately, I can't check that right now as the plugin crashed Kodi on installation _again_and Kodi was then in a crash-restart loop. Unfortunately, I didn't have logging enabled at the time of installation (for whatever stupid reason 🙄). However, I could find Kodi crash logs and they all boil down to some issue with the conversion of a timestamp, see files attached.

Best regards.

[kodi_crashlog-20220106_154437.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7822959/kodi_crashlog-20220106_154437.log)
[kodi_crashlog-20220106_154527.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7822960/kodi_crashlog-20220106_154527.log)
[kodi_crashlog-20220106_154610.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7822961/kodi_crashlog-20220106_154610.log)
[kodi_crashlog-20220106_154651.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7822962/kodi_crashlog-20220106_154651.log)
[kodi_crashlog-20220106_154732.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7822964/kodi_crashlog-20220106_154732.log)
[kodi_crashlog-20220106_154813.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7822966/kodi_crashlog-20220106_154813.log)
[kodi_crashlog-20220106_154858.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7822967/kodi_crashlog-20220106_154858.log)
[kodi_crashlog-20220106_154944.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7822968/kodi_crashlog-20220106_154944.log)
[kodi_crashlog-20220106_155026.log](https://github.com/mediathekview/plugin.video.mediathekview/files/7822969/kodi_crashlog-20220106_155026.log)

**Comment by ErnstNeger** [comment]
Update:

Without _manually_ removing the folder `plugin.video.mediathekview` from `/home/kodi/.kodi/addons`, Kodi was stuck in an infinite crash-restart loop (Arch was still responsive, so I could stop Kodi eventually using `systemctl stop kodi.service` and remove the plugin _manually_. Afterwards, Kodi started up just fine.

Best regards.

**Comment by codingPF** [comment]
The MV plugin will start a service on Kodi start up. So every time you start Kodi, the service will be started.
You can switch off the service via settings or update the setting.xml (/home/kodi/.kodi/userdata/addon_data/plugin.video.mediathekview/) file manually:
`<setting id="updmode">0</setting>`

The date time exception is some 3.10 python bug reported [here](https://bbs.archlinux.org/viewtopic.php?id=272121)
`"/usr/lib/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters`

**Comment by ErnstNeger** [comment]
> The MV plugin will start a service on Kodi start up. So every time you start Kodi, the service will be started. You can switch off the service via settings or update the setting.xml (/home/kodi/.kodi/userdata/addon_data/plugin.video.mediathekview/) file manually: `<setting id="updmode">0</setting>`

Couldn't do that as the folder was _non-existent_.

> The date time exception is some 3.10 python bug reported [here](https://bbs.archlinux.org/viewtopic.php?id=272121) `"/usr/lib/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters`

Agreed, that seems to be the issue, breaks a sh*tload of addons, f.e. [YouTube](https://github.com/anxdpanic/plugin.video.youtube/issues/255). Thus, I changed the title to something more meaningful.

> A workaround is described in the Kodi Forum [here](https://forum.kodi.tv/showthread.php?tid=366000) which makes me think this a global issue with Kodi since the author does not mention any relation to some plug-in.

Sure is. I will wait for a fix in Python rather than going through the whole downgrade hassle and possibly breaking other stuff on the road.

> Anyway, please provide the listing and we can take it from there….I will also upload a version 1.0.6 into the beta Repo which will do some changes to the reported issue. Not sure if this will fix the issue but these changes have been on my plate anyway…

I take it you're talking about the listing of files in `/home/kodi/.kodi/userdata/addon_data/plugin.video.mediathekview/`? Like I said, can't provide it as the directory does not get created on installing (Kodi crashes beforehand).

**Comment by codingPF** [comment]
Sorry, our updates on this topic collided…you can have a try in the beta Repo but I guess you are going to rollback your installation…
Closing this one
