### ISSUE TITLE
Buffer/Adaptive Bitrate Switching und Mediathekview?

### ISSUE THREAD

**Issue by yoshimo** [mediathekview/plugin.video.mediathekview#208]
Bis dato scheint alles im Ökosystem von Mediathekview auf direkte Links zu setzen auf Dateien mit Endungen wie MP4.
Wir haben hier nicht die beste aller Leitungen und seit InputStreamAdaptive mit
https://github.com/xbmc/inputstream.adaptive/pull/732
für die Zukunft eine Lösung geschaffen hat Ruckler zu vermeiden mit dem Wechsel der Qualität und vorrausschauendem Laden, wie sieht es in MediathekView hierzu aus?
Die offizielle Webseite der ARD-Mediathek mit dem Browser betrachtete zum Beispiel nutzt M3U-Playlists wo ISA dann ansetzen könnte.
Wahlweise könnte man natürlich die ganze Datei auf die Platte schreiben , dabei Anfang und Ende priorisieren und dann das ganze mit zunehmend vorhandenen Blöcken von vorne Abspielen wie es manch Torrent Programm damals als "Livestream" Ersatz gemacht hat :)

**Comment by codingPF** [comment]
Da bin ich bei dir…die adaptiv Links wären für Kodi viel besser und geeigneter.
Leider ist das aber im Moment nicht über die Architektur von MV abzubilden und wird bis zum nächsten großen Backend Release von MV warten müssen…

**Comment by yoshimo** [comment]
Kann man den Fortschritt dazu in einem TODO Issue irgendwo beobachten?

**Comment by codingPF** [comment]
Nein, leider nicht
