### ISSUE TITLE
Frage: Wie kann man mehrere Begriffe bei "Ignoriere Titel mit" berücksichtigen?

### ISSUE THREAD

**Issue by beta-tester** [mediathekview/plugin.video.mediathekview#209]
Verzeihung, wenn ich auf diese Weise hier eine Frage stelle.
Ich möchte keine Sendung aufgelistet bekommen, die im Titel die Begriffe "Audiodeskription" oder "(mit Gebärdensprache)" enthalten,
Leider weiß ich nicht, wie ich unter "Einstellungen -> Allgemein -> Ignoriere Titel mit" die Begriffe eintragen muss, damit sie "_oder_" verknüpft sind.

**Comment by codingPF** [comment]
Versuch es mal mit pipe ("|")...also Audiodeskription|Gebärdensprache

**Comment by beta-tester** [comment]
@codingPF , danke, es klappt ... super!
