### ISSUE TITLE
Verbesserte Metadaten: Tags, Genres

### ISSUE THREAD

**Issue by domschl** [mediathekview/plugin.video.mediathekview#21]
Leider liefern die Sendeanstalten nur Metadaten von schlechter Qualität. Das macht es schwieriger, Archive zu sortieren, und Downloads in bestehende Archive zu integrieren.

**1. Tags (static)**
Daher wäre es wohl sinnvoll, NFO Dateien (sowohl `tvshow.nfo` als auch `episode.nfo`) mit:
`<tag></tag>`
auszustatten. Tags könnten als Minimum den Ursprung einer Datei/Show anzeigen, z.B.:
`<tag>Mediathek</tag>`
evtl. weitere Möglichkeiten wären `<tag>Subscription</tag>`.

Da innerhalb von Kodi nach Tags gesucht und gefiltert werden kann, könnten so einfacher importierte Mediathek-Inhalte identifiziert werden.

Später fügt dann die A.I. weitere Tags hinzu ;-)

**2. Genres via static rules**
`<genre></genre>`
Eine Möglichkeit, Genres einfach hinzuzufügen, wäre über statische, jedoch erweiterbare, Rules. Wir könnten RegExs auf Show/Title/Description definieren, die dann ein Genre synthetisieren. Das ist relativ billig machbar. Die RegExe könnten in einer separaten Datei liegen, die dann beim Start geladen wird, und beim Download von Sendungen könnten dann zumindest einige Sendungen, die durch solche rules erfaßt sind, mit sinnvollen Genres ausgestattet werden.

**Comment by tuxpoldo** [comment]
Geile Idee!

**Comment by domschl** [comment]
Some more information on `NFO` files:

The `tvshow.nfo` can have both multiple `<genre>SomeGenre</genre>` and multiple `<tag>SomeTag</tag>` lines. So a single tvshow can have multiple genres and multiple tags, each specified by a separate line in the XML file.

```
<genre>Science Fiction</genre>
<genre>Dystopian</genre>
```

Both genres and tags can be used for searches, additionally users can add tags to shows using Kodi's UI.

Genres and tags are free choice, there are no 'pre-defined' genres. (Over history, there have been some, but that doesn't seem to be the current state.) Simply using a new genre within a tvshow.nfo establishes that genre.

It's possible to use one or multiple genres also in episode-NFOs, but for some reason, it's not possible to use tags within episode-NFOs.

Sources:
* http://kodi.wiki/view/NFO_files/TV_shows
* http://kodi.wiki/view/Databases

**Comment by tuxpoldo** [comment]
Kurzer Zwischenstand: nach unserer letzten gemeinsamen Programmiersession sind wir hier einen Schritt weiter gekommen. Mehr dazu gibt es demnächst im Forum.

**Comment by domschl** [comment]
stale, closed.
