### ISSUE TITLE
Kodi crashes with segmentation fault

### ISSUE THREAD

**Issue by marcoSchr** [mediathekview/plugin.video.mediathekview#211]
# Observed behavior

When opening the addon the overview with search, livestream etc. is presented.
When selecting any menu item, kodi completely crashes with a segmentation fault

# Steps to reproduce
- Start kodi
- Start the Mediathekview addon
- select livestreams
- --> Kodi crashes

# System Information:
OS: Arch Linux
Kodi Version: 19.4
Mediathekview addon version: 1.0.9

# Additional Information

I have found out, that when downgrading python to 3.10.2 no crash happens.
I am not sure where the issue comes from, but mediathekview is the only addon that crashes kodi for me.
Is there any additional information I can provide?

[kodi_crashlog-20220530_163909.log](https://github.com/mediathekview/plugin.video.mediathekview/files/8799187/kodi_crashlog-20220530_163909.log)

**Comment by codingPF** [comment]
Looks like this was reported here.
https://bbs.archlinux.org/viewtopic.php?id=275402
I will try to check but that does not sound promising

**Comment by marcoSchr** [comment]
Thanks for the information.
The issue in the link you posted, might be something other than what I experienced.

My issue was solved by a python update yesterday, with the following fix: https://github.com/python/cpython/commit/178a238f25ab8aff7689d7a09d66dc1583ecd6cb
