### ISSUE TITLE
Background fanart (colours and whitespace for best visual compatability)

### ISSUE THREAD

**Issue by Ch1llb0** [mediathekview/plugin.video.mediathekview#212]
[Dieser Issue](https://github.com/mediathekview/plugin.video.mediathekview/issues/194) ist geschlossen worden, allerdings hat sich bezüglich der Fanart leider bezüglich eines Punktes in 1.0.9 nicht viel geändert - die Fanart haben keinen Whitespace-Rahmen und manche sind aufgrund der Farbe je nach Überlagerungsfarbe eines Skins kaum bis gar nicht erkennbar.

Whitespace und monochrome Fanart würden sehr helfen, um die allgemeine Kompatibilität mit jeglichen Skins zu erhöhen bzw. dafür zu sorgen, dass die Fanart in jedem Szenario gut sichtbar sind. Es wäre gut, wenn die hinterlegten Fanart, die Skins abrufen können, berücksichtigen könnten, dass Skins verschiedene Farben überlagern können und die Art der Skalierung ebenso nicht vorgegeben ist, sondern von Skins frei gewählt werden kann. Die meiner Meinung nach beste Variante, um hier größtmögliche visuelle Kompatibilität herzustellen, wäre es, die Fanart in weiß-transparent und mit einem transparenten Rahmen als Whitespace um die Icons zu hinterlegen.

Zu welchen unschönen Darstellungsvarianten es in der momentanen Variante kommen kann, siehe hier: https://github.com/mediathekview/plugin.video.mediathekview/issues/194#issuecomment-887466066

Kann sich hier noch etwas tun, @codingPF? 😃

**Comment by codingPF** [comment]
Am besten machst du einen PR und dann schaue ich mir gerne an wie sich das mit dem normalen Skin verträgt.
