### ISSUE TITLE
Wrong format of <aired> tag in NFO file

### ISSUE THREAD

**Issue by Girke** [mediathekview/plugin.video.mediathekview#215]
Hi,
vorab, MediathekView (für Kodi und Windows) ist ein richtig gutes Programm - vielen Dank dafür!

Mein Problem: Die <aired>-Informationen in den generierten NFO-Dateien scheinen nicht in einem gültigen Format zu sein. Laut dem Kodi-Wiki (https://kodi.wiki/view/NFO_files) sollte das Format yyyy-mm-dd sein. Derzeit sieht es aber aus, wie ein Unix-Zeitstempel. 
```
<aired>1664718300</aired>
<year>1664</year>
```
Vielleicht könnten Sie auch <premiered> mit generieren, da <aired> laut dm Wiki nicht genutzt wird.
Des Weiteren wird <year> auch falsch berechnet.

Besten Dank.

**Comment by codingPF** [comment]
ok, das sieht nach einem kleinen fix aus aber

`Vielleicht könnten Sie auch mit generieren, `
Was soll das bedeuten?

**Comment by codingPF** [comment]
In der preview ist das Problem behoben

**Comment by Girke** [comment]
Hallo, sorry für mein Kauderwelsch. Das sollte heißen: "Vielleicht können Sie auch das <premiered> mit gleichem Wert mit generieren, da <aired> laut dem Kodi-Wiki scheinbar nicht genutzt wird. Desweiteren wird wegen des falschen Formats auch <year> falsch berechnet.".
Das mit dem <year> ist ja schon behoben, aber wenn Sie das mit dem <premiered> noch reinbringen könnten..

Auf jeden Fall vielen Dank für die superschnelle Reaktion.

**Comment by codingPF** [comment]
Alles Gut 😂
Das Jahr ist auch drin.
Es gibt da allerdings Unterschiede von zwischen Movie & Show.
Ich schließe das issue dann gehen nächste Woche
