### ISSUE TITLE
Pause/Zurückspulen

### ISSUE THREAD

**Issue by NgrNxk** [mediathekview/plugin.video.mediathekview#217]
Hi!

normalerweise kann man in den Mediathek-Apps der Sender auch zurückspulen -- bei ARD sogar 90 Minuten! Wieso ist das in diesem Addon nicht möglich? Ich glaube mich zu erinnern, dass es im MediathekView Standalone-Client möglich ist...

VG
Adam

**Comment by codingPF** [comment]
Ja in den Apps oder auf der Website geht das. Die dort eingesetzten Player unterstüzuen (so wie die ARD) ca 90 min.
Leider kann Kodi das so nicht leisten.
Der Stndalone Client hat keinen eigenen Player und verwendet VLC...aber auch VLC kann das nicht wirklich abbilden.
Vielleicht wird es irgendwann mal mit Kodi möglich sein aber im Moment geht es leider nicht.
