### ISSUE TITLE
Hintergrund Service für DB Aktualisierung

### ISSUE THREAD

**Issue by yoshimo** [mediathekview/plugin.video.mediathekview#219]
Der DB Server ermöglicht es scheinbar dass nur der Unterschied zur letzten Datenbank heruntergeladen werden wenn die noch nicht zu alt ist. 
Auch ist es lästig wenn man gerne etwas gucken möchte, aber vorher noch einen Download vornehmen muss.
Könnte man nicht wenn Kodi startet und kein andres Streaming Plugin aktiv ist, schon mal anfangen die letzten Filme&Serien herunterzuladen mit geringer Priorität? Sprich ich mach den Fernseher an, hole mir etwas zu trinken und bis ich wieder komme ist neben dem Netflix Service durch den MV-Service die Datenbank schon aktuell?
Wenn man das quasi regelmäßig macht, ist auch der Einfluss auf das Usererlebnis durch kleinere Datenmengen die synchronisiert werden müssen, deutlich geringer und man freut sich: Plugin auf: Loslegen :)

Zum jetzigen Zeitpunkt scheint er nur zu aktualisieren 5 Sekunden nachdem ich auf die Infos zur Datenbank geklickt habe und da man MV nicht jeden Tag braucht hat man ein Auffrischungsdefizit und die DB kann mehrere Tage alt sein obwohl Kodi beinahe täglich aktiv ist.

**Comment by vitusson** [comment]
Auf die Gefahr hin daß ich dich evtl. falsch verstehe, aber 
https://github.com/mediathekview/plugin.video.mediathekview#funktionsweise-der-aktualisierungsmethoden 
hast du schon gelesen?

Das ist doch alles einstellbar und der Default steht auf "Automatisch".

**Comment by yoshimo** [comment]
Der steht auf automatisch. Ich habe das Gefühl der Hintergrund Dienst startet nicht mit Kodi sondern erst mit dem Plugin und damit verliert er einen Teil seines Nutzens.

**Comment by codingPF** [comment]
Zu deinen Fragen:
`Könnte man nicht wenn Kodi startet und kein andres Streaming Plugin aktiv ist, schon mal anfangen die letzten Filme&Serien herunterzuladen mit geringer Priorität?`
Das geht leider nur näherungsweise mit der "Zeitgesteuert/Continously" Option. In diesem Fall wird er morgens (~6 Uhr) das "Full Update" machen und dann nur noch die Delta Daten.
`Ich habe das Gefühl der Hintergrund Dienst startet nicht mit Kodi sondern erst mit dem Plugin und damit verliert er einen Teil seines Nutzens.`
Das Update pausiert wenn die App nicht verwendet wird. Das hat dann umgekehrt den Effekt, dass ein Update erst beginnt wenn man die App aufruft. Das hat mich auch immer aus den Gründen die du oben schreibst gestört. Deshalb bin ich dann auf "Zeitgesteuert" umgestiegen.
Das ganze verhalten geht auf diesen Teil der Anleitung zurück.
`Die automatische Aktualisierung pausiert, wenn das Addon länger als 2 Stunden nicht bedient wurde, um Bandbreite und bei mobilen Geräten Strom zu sparen.`
