### ISSUE TITLE
[Feature] MediathekViewWeb

### ISSUE THREAD

**Issue by Gunnar-GO** [mediathekview/plugin.video.mediathekview#220]
Wie wäre es statt eine übergroße Datenbank herunterzuladen, die Abfrage an MediathekViewWeb.de weiterzuleiten.

Die Rückmeldung sollte sich doch recht leicht parsen lassen.

**Comment by vitusson** [comment]
Die aktuelle Filmlistendatenbank hat im gepackten Zustand 88 MB. 
Daran ist nichts "übergroß".

**Comment by codingPF** [comment]
Ich mag die Idee aber MVW passt nicht in die Struktur der Kodi App. Übersicht Seiten würden dann entfallen wenn man MVW nicht anpasst. 
Man könnte natürlich eine neue App schreiben um MVW auf Kodi zu bringen aber die gibt es schon…einfach mal suche

**Comment by Gunnar-GO** [comment]
@vitusson Stimmt es macht total Sinn, dass bei jedem Start erst einmal 88 MB geladen, dann entpackt und dann verarbeitet werden. Schön, dass du das für alle entscheiden und festlegen kannst, wie man es zu finden hat. Das macht auf kleinen Android-HDMI-Geräten wirklich Spaß. 🤦

____________

@codingPF du magst recht haben. Bzgl. anderes PlugIn: ich bin allerdings gerade nicht sicher ob ich das Richtige suche, denn ich habe gerade nur ein 2 Jahre altes Repo gesehen, meintest du dieses?

https://github.com/itouch5000/plugin.video.mediathekviewweb

Ich teste es gern. Danke dir für den Hinweis.

**Comment by vitusson** [comment]
@ Gunnar-GO Du willst für alle festlegen dass das Plugin doch bitteschön MVW nutzen soll und bist beleidigt wenn man anmerkt dass 88M nicht viel sind. Merkste selber. Wahrscheinlich nicht, 
EOD

**Comment by Gunnar-GO** [comment]
@vitusson ich habe es nicht festgelegt, geschweige denn ein Urteil über Andere gefällt, dass hast du und das ich nicht das erste Mal. Ich habe codingPF gedankt, da seine Anmerkung inhaltlich war, deine hingegen ist lediglich anmaßend, überheblich und vor allem egoistisch. Du entscheidest ja auch wann wer reden/schereiben darf "EOD". Daher .. 🤦

Der das Request wurde ja bereits geschlossen.

**Comment by codingPF** [comment]
Ich meinte eigentlich [diese](https://github.com/dojomo/plugin.video.mediathekdirekt) 
Ich habe beide nie getestet…Feedback ist willkommen…ggf ist das eine valide Alternative für schwache Geräte

**Comment by Gunnar-GO** [comment]
Danke für die Verlinkung, das PlugIn scheint ein anderes Schema zu verfolgen.

Ich habe mir unterdessen das [Plugin.Video.Mediathekviewweb von itouch5000](https://github.com/itouch5000/plugin.video.mediathekviewweb) angesehen, bzw. deren Forks für Kodi 20.0. Das wären die [Variante von vbprofi](https://github.com/vbprofi/kodi-19---repo/tree/main/plugin.video.mediathekviewweb), welche unsauber arbeitet und die [funktionsfähige Lösung von Kasi45](https://github.com/kasi45/plugin.video.mediathekviewweb). Letzteres hat einen Darstellungsfehler bei den Ergebnissen, so dass diese immer als Weit (also die Bebilderte horizontale Darstellung) erfolgt, dass sollte sich aber korrigieren lassen.

Generell besitzt das PlugIn einen sehr ähnlichen Aufbau und Verhalten zu dem MediathekView-Plugin, entspricht also eher dem nach dem ich fragte. Schade, dass diese Lösung nicht mit aufgenommen ist.

Deine Verlinkung habe ich auch kurz getestet und mich erinnert, dass ich das Plugin in einer früheren schon einmal eingesetzt hatte. Es verfolgt einen etwas anderen Ansatz und Verhalten, was ich jetzt weder gut noch schlecht werten möchte. 

Die Varianten der oben genannten sind quasi analog zum Mediathekview und nutzen diese Daten, während das [plugin.video.mediathekdirekt](https://github.com/dojomo/plugin.video.mediathekdirekt) auf die Mediathekdirekt.de JSON Datei zugreift.
