### ISSUE TITLE
Port zu Jellyfin

### ISSUE THREAD

**Issue by IchBinGROOT** [mediathekview/plugin.video.mediathekview#221]
Hallo und erstmal vielen Dank für das ganze Projekt, ich nutze es sehr regelmäßig um ein paar der guten Serien abspeichern zu können. 

Dieses Plugin sieht super aus und scheint bisher für Kodi einwandfrei zu funktionieren. Hat schonmal jemand versucht das ganze auf Jellyfin umzubauen? Ich bin dabei, meine Medienbibliothek auf Jellyfin umzustrukturieren, da ich dann auf allen Endgeräten die gleiche Benutzeroberfläche habe. Da wäre es sehr schade, wieder alles manuell herunterladen zu müssen, um es danach einzupflegen.

**Comment by alex1702** [comment]
Ist Jellyfin nicht nur eine Mediensammlung mit Streamserver?
Gehts dann darum mit dem Plugin Filme zu downloaden und direkt in die Jellyfin Datenbank zu packen?
