### ISSUE TITLE
ViewType springt immer zurück auf "IconWall"

### ISSUE THREAD

**Issue by relthyg** [mediathekview/plugin.video.mediathekview#223]
Wenn ich z.B. bei den Livestreams als ViewType "WideList" auswähle, die Liste verlasse und wieder reingehe, steht der ViewType wieder auf "IconWall"

Getestet mit

- Version 1.0.12+matrix1 unter Kodi 19.4 auf Debian Bullseye (Raspberry Pi)
- Version 1.0.12+matrix1 unter Kodi 20.0 unter Arch Linux

**Comment by codingPF** [comment]
Versuch mal in den Einstellungen  > advanced > static view id auszuschalten. Das sollte kein Problem lösen.

**Comment by relthyg** [comment]
Danke, hat geklappt.
