### ISSUE TITLE
Support for Kodi 20 (Nexus)

### ISSUE THREAD

**Issue by alexgit2k** [mediathekview/plugin.video.mediathekview#224]
The Kodi MediathekView.de Addon supports currently Kodi 17, 18 and 19:
https://github.com/mediathekview/plugin.video.mediathekview/blob/7da2e21e9c3b3731acfa2d8d8ecc4d88a3155259/README.md?plain=1#L341

Please also support Kodi 20 (Nexus) which has been released in January: https://kodi.tv/article/kodi-20-0-nexus-release/

**Comment by codingPF** [comment]
Just use the Repo and it will work for Nexus 20 as well

**Comment by alexgit2k** [comment]
Great! Can you please add Kodi 20 (Nexus) to:
- https://mediathekview.de/download/#mediathekview-f%C3%BCr-kodi-fr%C3%BCher-xbmc
- https://github.com/mediathekview/kodi-repos/blob/master/README.md
- https://github.com/mediathekview/plugin.video.mediathekview/master/README.md

So that there is no misunderstanding about the supported versions.
