### ISSUE TITLE
Error in Dockerfile

### ISSUE THREAD

**Issue by sepo83** [mediathekview/plugin.video.mediathekview#225]
In https://github.com/mediathekview/plugin.video.mediathekview/commit/51f8341c94261051750110d490083f81afebf744 the Dockerfile was chanced by adding `sqlite3` package. However, in Linux Alpine there is only a `sqlite` package (see https://pkgs.alpinelinux.org/packages?name=sqlite&branch=v3.18&repo=&arch=&maintainer=). Thus, building the docker image currently throws an error.

**Comment by codingPF** [comment]
thanks for raising the issue...i did fix the typo
