### ISSUE TITLE
Suche in Mediathek aus der Programmübersicht

### ISSUE THREAD

**Issue by Girke** [mediathekview/plugin.video.mediathekview#227]
Hallo,
erstmal wieder Danke für deine/eure Arbeit. Prima Programm und Plugin.
Für das Plugin hätte ich folgenden Feature-Wunsch: 
In der Programmübersicht (EPG) hat man die Möglichkeit, zu einem Programmeintrag in der Mediathek zu suchen. D.h. entweder gibt es bei Klick auf einen Eintrag schon im Kontextmenü einen Punkt "In Mediathek suchen" oder im Info-Fenster einen entsprechenden Button.
Ich habe es selber versucht, weiß aber nicht, wie man das EPG-Kontextmenü erweitern könnte oder welche onclick-Aktion ich beim Button hinterlegen muss. ActivateWindow (wie in Favoriten verwendet) funktioniert leider nicht für die onclick-Action, da das Info-Fenster scheinbar modal ist (?).
Danke und Gruß

**Comment by codingPF** [comment]
Interessante…das könnte sogar klappen….ich schau mir das mal an

https://forum.kodi.tv/showthread.php?tid=330252

**Comment by Girke** [comment]
Hi,
kurzes Update: Ich habe es jetzt für den Button im Info-Dialog erstmal hinbekommen, in dem ich als erste onclick-Action Dialog.Close(all,true) aufrufe und dann erst das ActivateWindow.
Danke für den Link zum ContextMenu Addon. Schaue ich mir auch nochmal an.

**Comment by codingPF** [comment]
Bin gespannt auf deinen PR

**Comment by Girke** [comment]
Sorry, da bin ich jetzt etwas überfordert.
Ich habe ja dafür direkt die estuary-Skin (bzw. eine eigene Kopie davon) angepasst. Dafür kann ich ja hier keine Änderungen vornehmen, oder?
Ansonsten ist die Anpassung dort recht einfach:
Datei: xml/DialogPVRInfo.xml
...

> 					<include content="InfoDialogButton">
> 						<param name="width" value="275" />
> 						<param name="id" value="904" />
> 						<param name="icon" value="icons/search.png" />
> 						<param name="label" value="In Mediathek suchen" />
> 						<param name="visible" value="Window.IsActive(PVRGuideInfo) | Window.IsActive(PVRRecordingInfo)" />
> 						<param name="onclick_1" value="Dialog.Close(all,true)" />
> 						<param name="onclick_2" value="ActivateWindow(10025,plugin://plugin.video.mediathekview-wifi/?mode=research&search=$INFO[ListItem.Title],return)" />
> 					</include>
> 

...
Und die übergeordnete grouplist etwas nach links gesetzt, damit es hinpasst.

Was ich gern noch ändern würde ist, dass bei jedem Aufruf die Suche auch gespeichert wird. Da wäre mir eine Einmal-Suche lieber. Gibt es dafür einen anderen Aufrufparameter?
Danke und Gruß

**Comment by codingPF** [comment]
Ok, das kann ich als Optionen Parameter für die “schnelle Suche” machen. Sag ich dann Bescheid- braucht aber noch etwas Zeit.
Ich dachte an die Kontextmenü Erweiterung aber so geht es natürlich auch.

**Comment by codingPF** [comment]
Ich habe es in das preview Repo hochgeladen…ist aber noch nicht 100% Rund beim zurück Button…

**Comment by codingPF** [comment]
Ist jetzt als feature im master
