### ISSUE TITLE
Mediathekview Kodi addon crashing under QNAP

### ISSUE THREAD

**Issue by n-albrecht** [mediathekview/plugin.video.mediathekview#228]
I've installed Kodi "Matrix" v 19.4 via the QNAP app from Qnapclub (https://www.qnapclub.eu/de/qpkg/874). I've installed the MV repo and the Mediathekview addon which worked fine for months. Without me having updated anything that I remember, the addon stopped working. 
Logfile mentions the following error:
`CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediathekview/) failed
GetDirectory - Error getting plugin://plugin.video.mediathekview/
Python interpreter stopped
SyntaxError: future feature annotations is not defined
from future import annotations
/opt/Kodi19L/.kodi/addons/script.module.myconnpy/lib/mysql/connector/abstracts.py line 33`

I could not copy the error message, so I had to type it off the screen, apologies for any errors.
Any idea what I can do? Is that something specific to my (QNAP-based) install?
I've tried reinstalling the app and the repo, installed the stable and the preview version to no avail.
Feedback in English or German is fine.

**Comment by codingPF** [comment]
The error is related to MySQL driver (script.module.myconnpy). It looks like there was a change of this module about one month ago in Kodi Repo. You may try to downgrade to the previous script.module.myconnpy version and check if this is the root cause.

**Comment by n-albrecht** [comment]
I don't think it's worth troubleshooting on sigle file basis, I don't need Kodi this much on its current platform. If anyone else has a simple idea or the issue results from a bug, feel free to contact me. As this does not seem to be the case, I'm closing the issue. No worries and thanks for the idea, @codingPF !
