### ISSUE TITLE
Triviale Suchen führen zu Kodi-Tod.

### ISSUE THREAD

**Issue by domschl** [mediathekview/plugin.video.mediathekview#23]
Setup: Kodi auf Raspberry Pi 2 / Leia

Suche nach 'und' in Descriptions führt dazu, daß das Add-on ca. 30min versucht alle Sendungen mit 'und' in der Beschreibung in eine Kodi-Listbox zu pressen.

Resultat: das ganze System hängt, Reboot erforderlich...

**Comment by tuxpoldo** [comment]
Wir müssen tatsächlich die maximale Anzahl dargestellter Treffer begrenzen... Wichtig ist, dass der Benutzer darüber informiert wird...
