### ISSUE TITLE
mediathekview plugin for Kodi 20 (nexus)

### ISSUE THREAD

**Issue by m1bcodes** [mediathekview/plugin.video.mediathekview#235]
Hello all,
I just upgraded my Kodi installation from 17 to 20 and I noticed, that the last supported version in the repositories is 19.
repo-mv is empty and contains only the png and xml file. Is that an isse with deployment or is nexus not supported?
Do you recommend installing the plugin from source or downgrade kodi to 19?
Thanks a lot.
Michael

**Comment by codingPF** [comment]
Please check the readme file or use the links below for as source for the repo

ZIP-Datei Stable Repository [Stable Repository](https://kodirepo.mediathekview.de/repo-mv/repository.mediathekview/repository.mediathekview-1.0.0.zip)
ZIP-Datei Preview Repository [Preview Repository](https://kodirepo.mediathekview.de/repo-mvp/repository.mediathekviewpreview/repository.mediathekviewpreview-1.0.0.zip)

**Comment by m1bcodes** [comment]
Thank you for answering.
These links I have already tried out.
Both files contain only the icon and xml files:
![grafik](https://github.com/mediathekview/plugin.video.mediathekview/assets/21145098/debaa9a0-95ce-4e72-90d9-a4a285fcb427)
But not any code, in contrast to the repos for the other Kodi versions - hence my question.
I am now using the zip file for Kodi 19, which works fine.

Thanks a lot.

**Comment by codingPF** [comment]
This is the way it is suppose to work. The xml contains the descriptor for the different versions (18 and 19+). You simply install the repository (from zip) and afterwards you install from repository (choosing the just installed repo) the application. 
You can use the zip for 19 which will work with 20 and 21 but you will not get code updates. To get code updates you need to install the repo which manages these.
