### ISSUE TITLE
Feature Request: Suche auf Uhrzeiten begrenzen

### ISSUE THREAD

**Issue by dpuschek** [mediathekview/plugin.video.mediathekview#238]
Ich komme von enigma2 und dort konnte das Mediathekview Plugin auch nach Uhrzeiten filtern. Dieses Feature fehlt mir in Kodi, bzw. ich habe es nicht gefunden:

Ich kann zwar prima meine Lieblingssendungen schon mal nach Sendern filtern (z.B. ARD + NDR) und nach Mindestlänge, aber nicht nach Uhrzeit. So würden mir zig Wiederholungen angezeigt werden, die außerhalb der regulären Sendezeit liegen (z.B. öfters nachts). Ich möchte z.B. nur Sendungen angezeigt bekommen, die zwischen 22:00 und 23:30 beginnen.

**Comment by codingPF** [comment]
Ich schaue mir das mal an. Welche Sendung wäre das zum Beispiel?

**Comment by dpuschek** [comment]
sorry, habe was verwechselt. Das e2 Mediathekview-Plugin kann auch keine Uhrzeiten. War wohl anderes Plugin.
