### ISSUE TITLE
'Esc' causes Kodi context-errors

### ISSUE THREAD

**Issue by domschl** [mediathekview/plugin.video.mediathekview#24]
In some states of the mediathek-plugin, 'Esc' causes Kodi-Errors:
Similar errors happen when leaving 'Search' via 'Esc' and sometimes in other screens when 'Esc'-ing out of the plugin.

```
12:22:52.642 T:140514708928576   ERROR: GetDirectory - Error getting plugin://plugin.video.mediathekview/?mode=search
12:22:52.644 T:140514708928576   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediathekview/?mode=search) failed
```
Restarting the plugin yields:
```
12:35:58.464 T:140004683573312   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
12:35:59.389 T:140004219299584  NOTICE: [plugin.video.mediathekview-0.3.4:Store]: Database driver: Internal (sqlite)
```

**Comment by tuxpoldo** [comment]
Unfortunately this is a problem caused by the Kodi-Architecture and it is not possible to avoid it (See our phone call). It would take too long to explain the details....
