### ISSUE TITLE
Typo deutsche Sprachdatei

### ISSUE THREAD

**Issue by vitusson** [mediathekview/plugin.video.mediathekview#25]
https://github.com/mediathekview/plugin.video.mediathekview/blob/784e8c6179bcd34a8bfb9e53c715511f646f4197/resources/language/resource.language.de_de/strings.po#L282

Kleiner kosmetischer Fehler, aber fiel mir gerade auf
Sollte "Video wird heruntergeladen" heißen
)

**Comment by tuxpoldo** [comment]
Danke!
