### ISSUE TITLE
MySQL - Anlegen der Datenbank

### ISSUE THREAD

**Issue by hawkeyexp** [mediathekview/plugin.video.mediathekview#26]
Durch Zufall über einen Blogeintrag auf das Addon gestoßen.
Zum Testen mal installiert und da ich für alles in Kodi schon lange MySQL verwende also umgestellt auf Datenbank MySql -> Fail.

Bitte im Addon die Prüfung bzw. Möglichkeit zum Erstellen der Tabellen einbinden. Manueller Import einer fest benannten SQL macht wenig sinn (und die Datenbank hat nen "doofen" Namen - vielleicht eher mal anpassen auf "mediathekview" damit es eindeutig ist). Das Ist leider zu umständlich.
Zumal das Addon auch ständig mit der SQL reden will obwohl keine Tabelle da ist und es ständig zu Fehler-Popups führt.
Ich habs jetzt erst mal aufm Fußweg eingebunden.

**Comment by steff75** [comment]
Wenn ich noch was anhängen darf. MariaDB10 läuft auf Synology Diskstations standardmäßig auf Port 3307. Im Addon hat man zur Zeit noch keine Option, den Port von 3306 umzustellen. Wäre prima, wenndas ginge. Danke!

**Comment by tuxpoldo** [comment]
Da wart ihr mal wieder schneller - das wollte ich heute noch eintragen :-) Kommt im nächsten Release.
