### ISSUE TITLE
How to install this plugin in OSMC

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/plugin.video.mediathekview#38]
Please can someone add the instructions how to install the plugin?

It would be nice, if the plugin is downloadable via the OSMC search add-on function.

Let me propose you enable the Wiki function of github, so that we can collaboratively write a manual.

**Comment by domschl** [comment]
Here is a [pull request](https://github.com/xbmc/repo-plugins/pull/1595) to Kodi's official plugin repository that is currently been worked on. As soon as that pull request is merged into the official Kodi code base, the plugin should be available to all KODI Krypton (and later) based systems.

**Comment by Wikinaut** [comment]
Great! Thanks.
