### ISSUE TITLE
Search for "Suchen in Titel und Beschreibung" : "Mediathekview Datenbankfehler" MySQL Syntax Error 

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/plugin.video.mediathekview#39]
Ich bekomme bei allen Suchen dieser Art sofort "Mediathekview Datenbankfehler" (MySQL statement Syntax error).

Beispiel: suche nach ```extra``` (für ```extra 3```).

Die Suche nach Titeln funktioniert.

* plugin release version v0.4.0 (https://github.com/mediathekview/plugin.video.mediathekview/releases/tag/release-0.4.0)

**Comment by domschl** [comment]
Ist nicht das Problem hier, aber evtl. auch im gleichen Zug auch auf "preparedStatement" für user-input umstellen, da Suchen mit z.B. `"` direkt in trübe Gewässer führen...

**Comment by Wikinaut** [comment]
@domschl Wo(wie) kann ich den Fehler suchen?

**Comment by domschl** [comment]
@tuxpoldo arbeitet bereits an einigen SQL-Themen, also einfach etwas Geduld haben, das sollte sich bald alles stabilisieren.

**Comment by tuxpoldo** [comment]
Zwei Sachen wären interessant:
1. Welche Version von MySQL bzw. MariaDB? Wir hatte uns hier ja leider ausgeschwiegen... Ich habe das ganze bis jetzt nur auf 5.7 getestet....
1. DIe QUeries werden immer im Kodi-Log geschrieben. Diese würde mich mal interessieren.

**Comment by tuxpoldo** [comment]
In der nächsten Version sind das auf jeden Fall prepared statements, so dass dieses Problem schon mal nicht mehr reingreifen kann.
