### ISSUE TITLE
Kein Download mehr möglich "'mvutils' is not defined"

### ISSUE THREAD

**Issue by vitusson** [mediathekview/plugin.video.mediathekview#46]
Ich renne hier gerade bei jedem Downloadversuch in den gleichen Fehler.
Hat mit der vorherigen Version noch funktioniert.
LibreELEC 8.2.2

````
13:31:44.500 T:998831008  NOTICE: [plugin.video.mediathekview-0.4.0:Store]: Database driver: Internal (sqlite)
13:31:44.500 T:998831008  NOTICE: [plugin.video.mediathekview-0.4.0:StoreSQLite]: Using SQLite version 3.15.2, python library sqlite3 version 2.6.0
13:31:44.502 T:998831008  NOTICE: [plugin.video.mediathekview-0.4.0:StoreSQLite]: SQLite Query: SELECT film.id,title,show,channel,description,duration,size,datetime(aired, 'unixepoch', 'localti
me'),url_sub,url_video,url_video_sd,url_video_hd FROM film LEFT JOIN show ON show.id=film.showid LEFT JOIN channel ON channel.id=film.channelid WHERE ( film.id=122907 )
13:31:44.546 T:998831008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'mvutils' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/addon.py", line 329, in <module>
                                                addon.Do()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/addon.py", line 317, in Do
                                                self.doDownloadFilm( filmid[0], quality[0] )
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/addon.py", line 179, in doDownloadFilm
                                                showname        = mvutils.cleanup_filename( film.show )[:64]
                                            NameError: global name 'mvutils' is not defined
                                            -->End of Python script error report<--_
````

**Comment by tuxpoldo** [comment]
Sorry! Heute gibt es noch ein Update.... Erstaunlich dass das noch keiner vorher gemeldet hat.

**Comment by vitusson** [comment]
Nur das weder dieses Release, noch das neuere 0.4.2  bis jetzt im Kodi-Repository angekommen ist.
Oder verstehe ich das alles falsch und muß doch dein beta-Repo wieder aktivieren, wenn ich so essentielle Fixes haben möchte?

**Comment by vitusson** [comment]
Okay, nevermind.
hab die Antwort in https://forum.mediathekview.de/topic/1097/aktuelle-release-ank%C3%BCndigungen gefunden. RTFM hilft wie immer  ;-)

**Comment by tuxpoldo** [comment]
Ich weiss... das ist jetzt ziemlich blöd, aber leider dauert das ganze noch ein wenig. In der 0.4.1 und 0.4.2 ist jede menge Bugfix und Security reingeflossen. Das Problem ist nur, dass eine neue Python-Library benötigt wird, die es aber noch nicht als Kodi-Modul gab. Ich habe bereits vor einer Woche den [Pull-Request #754](https://github.com/xbmc/repo-scripts/pull/754) eingereicht - aber solange der nicht freigegeben ist, kann ich auch nicht den Pull Request für die neue Version stellen... Also wirst Du leider das Repo kurzfristig aktivieren müssen. Kannst es danach ja wieder ausschalten bzw. kannst das ganze natürlich auch manuell installieren. Im Forum sind immer zeitnahe Ankündigungen.

**Comment by vitusson** [comment]
Kein Problem. Ich hatte mich nur gewundert daß kein Update kam und das Kleingedruckte in der  aktuellen Releasankündigen nicht genau genug gelesen.
