### ISSUE TITLE
Dep script.module.defusedxml breaks install/update

### ISSUE THREAD

**Issue by hawkeyexp** [mediathekview/plugin.video.mediathekview#54]
The new entry <import addon="script.module.defusedxml" version="0.5.0"/> breaks install/update of mediathekview in latest release. I didn't found a repo which contains this version. Where is it available ?

Note: would be nice if new dependencies are set the needed package is available via an existing repo. Best way would be adding it to you repo to make install possible.

**Comment by hawkeyexp** [comment]
Found the package on:
https://archive.yeasoft.net/xbmcaddonsbeta/script.module.defusedxml/script.module.defusedxml-0.5.0.zip

But your package is buggy - the addon id is wrong in addon.xml !!

should be 'id="script.module.defusedxml"' but currently it is 'id="script.module.ijson"'

**Comment by tuxpoldo** [comment]
You are right! I discoverd the error days ago and fixed it See [Pull Request #754](https://github.com/xbmc/repo-scripts/pull/754/files#diff-b6770f6a615373aad31cff0f2e3a92c6R2) in the official Kodi Repository. I fixed it now in the beta repository. Now the automatic installation of the updates should work.
