### ISSUE TITLE
Feature Request: Einfache Blacklist 

### ISSUE THREAD

**Issue by fzinken** [mediathekview/plugin.video.mediathekview#56]
Letztendlich wäre es natürlich toll die gleichen Filter Möglichkeiten zu haben wie in MV aber als Anfang würde eine Blacklist Möglichkeit um z.B. die Hörfassung auszuschließen sehr hilfreich sein

**Comment by codingPF** [comment]
Es gibt jetzt in den Settings ein "einfache" Backlist die für die Suche verwendet wird.
Das feature ist im DEVBRANCH

**Comment by codingPF** [comment]
Released to 1.0.0 master
