### ISSUE TITLE
MySQL Datenbank kann nicht erstellt werden

### ISSUE THREAD

**Issue by ArtusKing** [mediathekview/plugin.video.mediathekview#59]
Der Versuch die Datenbank via MySQL aufs NAS auszulagern bricht mit folgender Fehlermeldung ab:
"1071 (42000): Specified key was too long; max key length is 1000 byte

**Comment by tuxpoldo** [comment]
Der Fehler tritt auch bei anderen auf. Es gibt dazu Forums Diskussionen:
* [SQL-Datenbank - Fehler bei Erstellung](https://forum.mediathekview.de/topic/1163/sql-datenbank-fehler-bei-erstellung)
* [Mysql Datenbank](https://forum.mediathekview.de/topic/1136/mysql-datenbank/10)

**Comment by ArtusKing** [comment]
Mit der Version 0.4.3.3 wird nun eine Datenbank erzeugt, 
danach erscheint die Fehlermeldung: MySQL Connection not available

16:10:08.717 T:9228  NOTICE: [plugin.video.mediathekview-0.4.3.3:StoreMySQL]: Current SQL mode is
16:10:08.718 T:9228  NOTICE: [plugin.video.mediathekview-0.4.3.3:StoreMySQL]: Reducing channel name length...
16:10:08.734 T:9228  NOTICE: [plugin.video.mediathekview-0.4.3.3:StoreMySQL]: Reducing show name length...
16:10:08.835 T:9228  NOTICE: [plugin.video.mediathekview-0.4.3.3:StoreMySQL]: Reducing film title length...
16:10:08.855 T:9228  NOTICE: [plugin.video.mediathekview-0.4.3.3:StoreMySQL]: Deleting old dupecheck index...
16:10:08.863 T:9228   ERROR: [plugin.video.mediathekview-0.4.3.3:StoreMySQL]: === DATABASE SCHEME UPDATE ERROR: 1091 (42000): Can't DROP 'dupecheck'; check that column/key exists ===
16:10:08.872 T:9228  NOTICE: [plugin.video.mediathekview-0.4.3.3:Service]: Starting up... (instance id: dfa085578ff60ba2be4945ddb9c575ff)
16:10:20.913 T:16036   ERROR: XFILE::CDirectory::GetDirectory - Error getting
16:10:21.378 T:7012   ERROR: Previous line repeats 6 times.
16:10:21.378 T:7012  NOTICE: [plugin.video.mediathekview-0.4.3.3:Store]: Database driver: External (mysql)
16:10:21.378 T:7012  NOTICE: [plugin.video.mediathekview-0.4.3.3:StoreMySQL]: Using MySQL connector version 1.1.7
16:10:21.394 T:7012  NOTICE: [plugin.video.mediathekview-0.4.3.3:StoreMySQL]: Connected to server 192.168.1.182 running 5.1.72
16:10:23.659 T:7012   ERROR: [plugin.video.mediathekview-0.4.3.3:StoreMySQL]: Database error: MySQL Connection not available.
16:10:34.684 T:6132  NOTICE: Storing total System Uptime
16:10:34.684 T:6132  NOTICE: Saving settings
16:10:34.697 T:6132  NOTICE: Saving skin settings
16:10:34.704 T:6132  NOTICE: stop all
16:10:34.704 T:6132  NOTICE: stop player
16:10:34.704 T:6132  NOTICE: ES: Stopping event server
16:10:34.708 T:10152  NOTICE: ES: UDP Event server stopped
16:10:34.708 T:9228  NOTICE: [plugin.video.mediathekview-0.4.3.3:Service]: Shutting down... (instance id: dfa085578ff60ba2be4945ddb9c575ff)
16:10:34.708 T:9228  NOTICE: [plugin.video.mediathekview-0.4.3.3:Service]: Exit (instance id: dfa085578ff60ba2be4945ddb9c575ff)
16:10:34.719 T:9228 WARNING: CPythonInvoker(0, C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.mediathekview\service.py): the python script "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.mediathekview\service.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon,class XBMCAddon::xbmcaddon::Addon,class XBMCAddon::xbmcaddon::Addon,class XBMCAddon::xbmcaddon::Addon,class PythonBindings::XBMCAddon_xbmc_Monitor_Director
16:10:34.731 T:6132  NOTICE: closing down remote control service
16:10:34.731 T:6132  NOTICE: stopped
16:10:34.932 T:6132  NOTICE: destroy
16:10:35.193 T:6132  NOTICE: unload skin
16:10:35.330 T:6132  NOTICE: unload sections
16:10:35.350 T:6132  NOTICE: special://profile/ is mapped to: special://masterprofile/
16:10:35.350 T:6132   ERROR: CProfilesManager: current profile index ({0}) is outside of the valid range ({1})
16:10:35.350 T:6132  NOTICE: application stopped...

**Comment by tuxpoldo** [comment]
@ArtusKing: Das Problem dürfte mit der aktuellen Version gelöst sein. Kannst Du das mal bitte prüfen?

**Comment by ArtusKing** [comment]
Vielen Dank,  MySQL funktioniert nun tadellos.
Ich habe nicht mehr damit gerechnet, um so größer ist die Freude.
Und Danke auch, dass du mich darauf hingewiesen hast.

**Comment by tuxpoldo** [comment]
Sehr gut! Dann schließe ich das Issue.
