### ISSUE TITLE
Daten-Verzeichnisauswahl als experten Einstellung

### ISSUE THREAD

**Issue by alex1702** [mediathekview/plugin.video.mediathekview#69]
Wie im Forum erwähnt sollte es eventuell möglich sein das Verzeichnis wo die Filmliste hingeladen wird auslagerbar zu machen. Eventuell sollte die SQLite Datenbank mit auslagerbar sein, da es sonst nur die halbe Miete ist. Da das Updaten bei z.b. einem Raspberry Pi auf der SD-Karte einige Schreibzugriffe erzeugt, wäre es schonender wenn man dies auslagern kann. Das ganze könnte man hinter einer experteneinstellung verstecken.

Beitrag im Forum:
https://forum.mediathekview.de/topic/1170/feature-request-pfad-f%C3%BCr-daten-einstellbar

Zu erledigende Aufgaben:

- [] Auslagerung des Pfades nach tmp
- [] Option für das Auslagern des Pfades an einen beliebigen Ort per Konfiguration (experten Einstellung)

**Comment by Chris56** [comment]
Ich möchte das für den Raspberry Pi noch näher erläutern:
1. Speed: SD Karte: read/write 10-20 Mbyte/sec, Pi3 Memory 500!! MByte/sec
2. Durch viele Schreibzyklen geht die SD Karte kaputt.
3. Wenn man also die Daten (nicht die Settings) auf /tmp legt, geht es sehr schnell und die SD Karte bleibt unberührt. Man sollte dann bis auf die erstellte Datenbank alle anderen Daten löschen um nicht zu viel Memory zu benutzten.

**Comment by alex1702** [comment]
Keine doofe Idee solange das tmp Verzeichnis als Ramdisk eingerichtet ist.

**Comment by Chris56** [comment]
Ich kenne beim Raspberry Pi keine Distribution bei der das nicht so ist.
Man würde wegen der kurzen Lebensdauer nicht für /tmp die SD Karte benutzen.
Bei openelec/libreelec oder den Distributionen auf denen man Kodi startet ist /tmp als tmpfs gemountet.

**Comment by alex1702** [comment]
ok, hab halt nicht alle ausprobiert ^^
Werde mal gucken ob ich zumindest das mal einbauen kann.

**Comment by Chris56** [comment]
Ich kenne den Code gar nicht, deshalb schon einmal Entschuldigung:
Wie ich es sehe gibt es 3 Dateien, derzeit:
227352576 filmliste-v1.db
135767396 Filmliste-akt
1599824 Filmliste-diff
Wenn /tmp -also das Memory nutzt- dann sollte Filmliste-akt und/oder -diff nach Erstellen der db  löschen.
Gibt es Möglichkeiten die db kleiner zu halten? Immerhin fast doppelt so groß, wie die Daten aus denen sie hervor geht.

**Comment by tuxpoldo** [comment]
Ist jetzt für das nächste große Release (0.6.0) eingeplant.

**Comment by codingPF** [comment]
Ich möchte das hier schließen...
Technisch geht das alles aber Kodi sagt, dass man sich nur im „User Space“ bewegen soll....das ist sonst ein Security Thema...
Standalone MySQL oder Schnelle SD wäre die Lösung
