### ISSUE TITLE
[Feature] Update MySQL von einem anderen Host

### ISSUE THREAD

**Issue by MyLive** [mediathekview/plugin.video.mediathekview#72]
Ich nutze ein ARM System und hier braucht das Update der Mediathek Datenbank sehr lange.

Ist es möglich dieses auf einem anderen Rechner durchzuführen und damit MySQL zu betanken ?

**Comment by alex1702** [comment]
Ja richte dir einen MySQL Server ein und stelle dann in den Einstellungen auf MySQL. Auf dem system wo das update ausgeführt werden soll muss dann Python vorhanden sein, dann clonst du das repo und führst das script periodisch aus.

**Comment by alex1702** [comment]
Siehe unter "Standalone Datenbank Update Prozess" in der readme.
