### ISSUE TITLE
Browse by category

### ISSUE THREAD

**Issue by gsantner** [mediathekview/plugin.video.mediathekview#76]
Currently there seem to be no way to browse the library by categories and finding stuff be only "new" and "by character" is not very intuitive. I'm not very aware of all the mediathek shows hence don't know where to find something that interests me. Therefore, please add some kind of "Browse by category", the needed tags should be able to be scraped. Thanks!

(btw sorry if reports are awaited in DE)

**Comment by tuxpoldo** [comment]
There is one serious pitfall: The MediathekView Database does not contain any category information about the shows. Therefore it is almost impossible to implement such a feature.

**Comment by regenduft** [comment]
This cannot be true, i can see a column named "Thema" here https://mediathekviewweb.de/

**Comment by tuxpoldo** [comment]
You are right, but unfortunately the column named "Thema" does not really contain useful category information like "Sports", "Nature", "Crime" or so, but contains exactly what the plugin calls "Show".

A Movie like the weekly "Tatort" (let's take the last one from Sunday March 03 2019) is listend with "Thema" = "Tatort", "Title" = "Borowski und das Glück der Anderen":

![image](https://user-images.githubusercontent.com/1818987/54037965-b3a4ed00-41bf-11e9-9bc1-3d98b3cf7b36.png)

In the Plugin you wiill find it a s Show="Tatort", Video=""

![image](https://user-images.githubusercontent.com/1818987/54038136-19917480-41c0-11e9-999a-cb966abd5403.png)

![image](https://user-images.githubusercontent.com/1818987/54038162-2910bd80-41c0-11e9-9a27-2062b832db9d.png)

**Comment by tuxpoldo** [comment]
Same as #21 - Working on it...

**Comment by domschl** [comment]
We have already tested a machine-learning based topic classifier. Integration of that classifier will be the next step with the Mediathek view plugin. This will provide a number of topics across all those chaotic and fragmented data sources, and will hopefully make searching for interesting  content easier and more accessible.
