### ISSUE TITLE
Movie section

### ISSUE THREAD

**Issue by gsantner** [mediathekview/plugin.video.mediathekview#77]
Currently the only way to find more-or-less movie-alikes is by settings the min-duration up. It would be great to have a dedicated Movies section which list such. The needed info should be scrapeable if not already available. This list e.g. should not contain things like News, daily zoo documentaries, weather, 

Thanks!

**Comment by tuxpoldo** [comment]
There is one serious pitfall: The MediathekView Database does not contain any category information about the shows. Therefore it is almost impossible to implement such a feature.
