### ISSUE TITLE
[MySQL/MariaDB] MySQL Connection not available

### ISSUE THREAD

**Issue by x2k13** [mediathekview/plugin.video.mediathekview#79]
Seltsames Szenario:

Sobald der (externe) Datenbankserver bzw. der Datenbankdämon neu gestartet (start-stop/restart) wird, schlägt eine erneute Verbindung fehl. Man kann dies dann nur durch manuelle Aktualisierung des Addons fixen, alternativ deaktivieren und wieder aktivieren. Das Merkwürdige daran ist, dass das Addon sich offensichtlich ständig versucht neu zu connecten, aber irgendwo drüber stolpert. Getestet mit MySQL 5.7.x und MariaDB 10.1.x.

Idee?

**Comment by alex1702** [comment]
Steht dazu was in den Logs?

**Comment by x2k13** [comment]
Auf den ersten Blick nichts Verdächtiges, denke ich.
Wäre aber nett wenn jemand noch mal drüber schauen kann: [https://pastebin.com/Nfn5upSx](url)
Habs mal ab "MySQL Connection not available" bis zum De-/Aktivieren aus dem Log rausgepuhlt.
Die ganzen PushCecKeypress Einträge kann man ignorieren > Tastendruck der Fernbedienung halt.

**Comment by tuxpoldo** [comment]
Ich schaue mir das am WE mal an - ist eh höchste Zeit dass ich mal ein neues Release raus bringe - habe schon sehr viel neues gemacht, aber leider ist mir der Umzug in eine andere Stadt inklusive allen Ärgers den man am Bau nur so kriegen kann dazwischen gekommen.

**Comment by tuxpoldo** [comment]
Was ich ja hochgradig kurios finde, ist die Tatsache wie es zu diesem Fehler kommt. Prinzipiell gibt es im Plugin zwei Seelen:

- Die erste ist das Plugin selber. Es wird jedes Mal aufgerufen, wenn der Benutzer im Plugin eine Interaktion macht, und das Plugin füllt dann lediglich eine Liste auf dem Kodi-Bildschirm. Bei einer solchen Operation wird eine Verbindung jedes mal neu aufgebaut. Diese Verbindungen existieren nur kurzfristig. Wäre also spannend zu wissen, ob bereits diese Verbindungen nach dem Neustart des Datenbankservers fehlschlagen.
- Die zweite ist ein Service, der für das periodische Aktualisieren der Datenbank zuständig ist. Dieser Service existiert während der gesamten Laufzeit von Kodi und - soweit ich mich erinnere - hat dieser auch nur eine Connection die beim Start erzeugt wird. Dieser wäre also definitiv ein Kandidat für die Fehlermeldung.

Inwieweit diese beiden voneinander unabhängigen Teile irgendetwas miteinander Teilen, ist mir nicht wirklich klar, da es keine Brauchbare Doku in Kodi gibt, die beschreibt, wie die Python-Engines mehrere Addons die gleichzeitig aktiv sind behandeln.

Ich werde nun erst mal versuchen, das ganze mit einigen Tests zu reproduzieren.

**Comment by x2k13** [comment]
Kleines Update dazu:

Wie ich feststellen konnte, gibt es sporadisch, eine daher in den Logs schwer einzugrenzende Besonderheit. Ab und an verliert das Addon auch bei durchlaufendem DB Server die Connection, bzw. nur zum DBMS, da die kabelgebundene LAN Verbindung 24/7 steht, mit statischem DHCP Lease (v4 und v6) scheint dies nicht das Problem zu sein. Ich bin jetzt kein Experte wie die DB Integration genau funktioniert aber wenn die Verbindungen nur kurzzeitig aufgebaut werden, könnte das zu einer Art Race Condition führen, evtl. ist auch der Timeout etwas zu kurz gewählt (nur ein Gedanke).

Auch ist mir aufgefallen, dass das Aktualisieren (Delta..) der DB meist elend langsam vor sich geht, trotz GBit LAN und entsprechend fixer HD, auf der die DB sitzt (6GBit SATA). Dies ist bei der Standalone von MediathekView direkt auf der DB-Maschine definitiv nicht so, gerade mit der aktuellen 13.1.1. Eigentlich sollte das Ganze in der o.g. Konfig ja ähnlich fix laufen, sollte man meinen.

Jedenfalls schon mal Danke für die Mühe :-)

**Comment by tuxpoldo** [comment]
Das kann ich definitiv bestätigen:

````
14:12:53.266 T:123145553661952  NOTICE: virtual bool CAESinkDARWINOSX::Initialize(AEAudioFormat &, std::string &): Opening default device Built-in Output
14:12:55.637 T:123145562861568  NOTICE: [plugin.video.mediathekview-0.4.4.8:Store]: Database driver: External (mysql)
14:12:55.638 T:123145562861568  NOTICE: [plugin.video.mediathekview-0.4.4.8:StoreMySQL]: Using MySQL connector version 1.1.7
14:12:55.688 T:123145562861568  NOTICE: [plugin.video.mediathekview-0.4.4.8:StoreMySQL]: Connected to server qnap1 running 10.0.34-MariaDB
14:12:55.693 T:123145562861568  NOTICE: [plugin.video.mediathekview-0.4.4.8:StoreMySQL]: MySQL Query: SELECT film.id,`title`,`show`,`channel`,`description`,TIME_TO_SEC(`duration`) AS `seconds`,`size`,`aired`,`url_sub`,`url_video`,`url_video_sd`,`url_video_hd` FROM `film` LEFT JOIN `show` ON show.id=film.showid LEFT JOIN `channel` ON channel.id=film.channelid WHERE ( ( `title` LIKE %s ) OR ( `show` LIKE %s ) ) AND ( ( `aired` IS NULL ) OR ( TIMESTAMPDIFF(HOUR,`aired`,CURRENT_TIMESTAMP()) > 0 ) )
14:13:09.686 T:123145564471296   ERROR: [plugin.video.mediathekview-0.4.4.7:StoreMySQL]: Database error: MySQL Connection not available.
````

Gerade auf meine Entwicklerkiste passiert. Ich hatte gestern aufgehört zu arbeiten und habe Kodi weiter laufen lassen. Als ich gerade weiter machen wollte, ist genau das passiert - viel intgeressanter ist aber zu sehen, dass die Meldungen aus dem UI-Teil als `plugin.video.mediathekview-0.4.4.8:StoreMySQL` gekennzeichnet werden, die aus dem Service-Teil hingegen als `plugin.video.mediathekview-0.4.4.7` - was darauf hindeutet, dass kein Reload des Datenbanktreibers dort stattfindet.

Ich habe jetzt zwar keine Ahnung, warum das passiert, aber ich kann definitiv sagen, dass `python-mysql` kein Reconnect unterstützt (Zumindest wenn ich [diesem etwas älteren Beitrag](https://geert.vanderkelen.org/2011/connector-python-auto-reconnect/) glauben soll).

Ich schaue mir den Code nochmal an, und ändere eventuell mal den Scope des Datenbanktreibers, so dass er jedes Mall wenn er benötigt wird (Update) geladen wird, statt nur ein mal.

**Comment by tuxpoldo** [comment]
Hallo @x2k13 !

Mich würde mal interessieren, ob die letzte Version irgendetwas verbessert hat. Die Version findet sich im Beta-Repository bzw. in wenigen Tagen wird sie ins offizielle Kodi-Repo übernommen. Pull-Request wurde bereits gestellt.

**Comment by x2k13** [comment]
@tuxpoldo 

Mache ich dann gerne, bin gerade unterwegs, daher geht's erst in ein paar Tagen.
Ich melde mich dann wieder, danke für die Info!

**Comment by x2k13** [comment]
Sooo, bin wieder daheim und habe nach Update des Addons auf die neue Version die alte DB sicherheitshalber mal komplett entfernt, durch das Addon neu anlegen lassen und nach der Aktualisierung sieht das Ganze schon anders aus. Habe noch nicht in die Logs geschaut, aber bisher gab's keine Fehlermeldung, daher denke ich das es jetzt soweit funktioniert. Die Geschwindigkeit hat sich allerdings nicht verbessert, aber das ist eine andere Geschichte.

Ich lasse das Issue aber vorerst noch offen, falls doch noch was aufschlägt. Wenn sagen wir mal in einer Woche alles immer noch gut ist, sag ich nochmal kurz Bescheid und schließe hier, ist das okay?

**Comment by tuxpoldo** [comment]
Das mit der Geschwindigkeit hat damit auch nichts zu tun - das liegt leider in der Natur der Sache. Wichtig ist erst mal, dass das Connection-Problem gelöst ist. Schauen wir uns das mal eine Woche an.

**Comment by x2k13** [comment]
Ja ist richtig, hatte das auch nur erwähnt weil es schon ein Issue zur Geschwindigkeitsverbesserung gibt.
Hätte ja durchaus sein können, dass dies im aktuellen Release schon eingeflossen ist.

**Comment by x2k13** [comment]
So, ich habe mir das Ganze jetzt gut 4 Tage angeschaut, läuft. Keinerlei Connection Probleme mehr.
Deswegen denke ich, das Issue kann man als gelöst ansehen. Danke für deine Mühe, ich mach dann mal zu.
