### ISSUE TITLE
Datenupdate beschleunigen

### ISSUE THREAD

**Issue by Siggi0904** [mediathekview/plugin.video.mediathekview#85]
Hallo,

ist es möglich das Datenupdate massiv zu beschleunigen?
Auf meiner Wetek 1 dauert das Update ca 60-90 Minuten, was zu lange ist und somit das Plugin nicht nutzbar ist.

Vorschlag wäre z.B. die Nutzung der MediathekWeb Datenbank.
Diese Datenbank gehört ja dem Projekt an, wodurch eine Zusammenarbeit möglich ist.

Technische Hintergründe: Wetek Play 1, Libreelec 8.2.5, Datenbank lokal, Update automatisch.

Bei allen nötigen Gerätespezifischen Diagnosen helfe ich gern.

Danke.

**Comment by alex1702** [comment]
Soweit ich weiß ist geplant das einzubauen.

**Comment by Siggi0904** [comment]
Gern doch, ich bin für Beta Tests inkl. reporting immer zu haben.

Wäre schön, wenn das Plugin auch auf einer Wetek play nutzbar wäre.

**Comment by tuxpoldo** [comment]
Hier eine kurze Erklärung des Ansatzes. Die im Moment eingebaute Routine für die vollständige Aktualisierung funktioniert folgendermaßen:

1. Alle Einträge in der Datenbank werden als Löschkandidaten markiert
2. Jeder Eintrag in der heruntergeladenen Filmliste wird in der Datenbank gesucht. Wird er gefunden, wird die Löschkandidaten-Markierung entfernt. Wird er nicht gefunden, wird ein neuer Eintrag angelegt.
3. Am Ende der Routine, werden alle Einträge, die noch die Löschkandidaten-Markierung haben, gelöscht.

Ein Ansatz zur Beschleunigung könnte nun jener sein, bei einer vollständigen Aktualisierung eine neue Datenbank im Hintergrund komplett aus der heruntergeladenen Filmliste neu zu erstellen, und danach die alte Datenbank mit der neuen zu ersetzen. Dieser Ansatz könnte eventuell etwas schneller sein, weil einfach jeder Eintrag der Filmliste hinzugefügt wird, ohne irgendwelche Suchaktionen zu machen. Des weiteren könnten die Indizes der Datenbank erst nach der Befüllung erstellt werden. Verschiede Optimierungen sollen hier erst mal getestet werden, bevor das ganze implementiert wird.

Ein solcher Ansatz hat allerdings 3 Nachteile die nicht unerwähnt bleiben sollen:

1. Da bei einer vollständigen Aktualisierung eine zweite Datenbank erstellt wird, muss zumindest so viel Speicherplatz auf dem Medium vorhanden sein.
2. Die Anzahl der vom Plugin verursachten Schreibzugriffe dürfte deutlich höher sein.
3. Es kann nicht ermittelt werden, vie viele neue und wie viele gelöschte Einträge durch die Aktualisierung erfolgt sind.

**Comment by tuxpoldo** [comment]
Hier eine Tabelle mit den auf meinem Mac Mini Late 2012 mit Samsung 840 EVO SSD ermittelten Aktualisierungs-Zeiten:

Modalität | Ermittelte Zeit 
--------- | --------------
Aktualisierung einer älteren Datenbank im herkömmlichen Modus | 106 Sekunden
Befüllung einer leeren Datenbank im herkömmlichen Modus | 113 Sekunden
Befüllung einer leeren Datenbank im neuen Modus mit Indizes | 92 Sekunden
Befüllung einer leeren Datenbank im neuen Modus nachträglicher Index-Erstellung | 97 Sekunden
Befüllung einer leeren Datenbank im neuen Modus nachträglicher Index-Erstellung und abgeschalteten Fremdschlüsseln | 108 Sekunden

Fazit: Das beste Resultat sind 92 Sekunden gegenüber 106 Sekunden bei einer Aktualisierung was einer Verbesserung von 13,2% bzw. 92 Sekunden gegenüber 113 Sekunden bei der Ersterstellung einer Datenbank, was einer Verbesserung von 18,6% entspricht.

Stellt sich nun die Frage, ob sich der Aufwand einer derartigen Änderung lohnt. So wirklich klar ist mir das nicht. Ich denke, dass es sich auf jeden Fall lohnt, diesen Ansatz bei der Ersterstellung der Datenbank anzuwenden, da dies keine größeren Änderungen im Code (keine Notwendigkeit der Verwaltung einer zweiten Datenbank bei der Aktualisierung) erfordert, fast 20% Geschwindigkeit bringt, und keinen der Nachteile jedoch ein schnelleres Erfolgserlebnis direkt nach der Installation.

Ob eine Beschleunigung von 13,2% bei der Voll-Aktualisierung wirklich der Bringer ist, wage ich hingegen zu bezweifeln.

**Comment by Siggi0904** [comment]
Und direkt eine Datenbank vom Server laden? Dann würde das Einlesen entfallen.

Falls all dies nichts bringt, sollte man vielleicht die Kraft für die Unterstützung von MediathekViewWeb verwenden.

**Comment by tuxpoldo** [comment]
Die Datenbank direkt vom Server laden, wäre sicherlich eine brauchbare Idee. Unkomprimiert ist die Datenbank 236 MB groß. Komprimiert man sie mit Maximum-Compression mit `bzip2` ist sie noch 56 MB groß, mit `xz` 45 MB - das ist leider immer noch doppelt so groß wie das originale Datenbank-File (23 MB).  Um einen solchen Download anzubieten muss erst mal eine passende Infrastruktur geschaffen werden - es ist mir nicht so ganz klar, ob das mit den bestehenden Mitteln praktikabel wäre... Ich hatte schon oft darüber nachgedacht.

**Comment by tuxpoldo** [comment]
Also.... Das letzte Update des Plugins habe ich nur auf dem offiziellen Kodi-Repo released und dort werden zur Zeit ca. 2700 Downloads angezeigt. Also kann man mal ganz vorsichtig davon ausgehen, dass dies auch die aktuelle Nutzerzahl ist. Unter der Annahme, dass jeder davon ein mal am Tag die vollständige Aktualisierung herunterladen würde, wären das ca. 150 GB pro Tag. oder 4,5 TB pro Monat. Ist also nicht ganz trivial - allzumal davon ausgehen ist, dass die Nutzerzahl noch steigen könnte...

**Comment by tuxpoldo** [comment]
Die Stored Procedures kommen nur bei MySQL zum Einsatz. Bei SQLite geht das mit normalen Queries, da SQLite keine Stored Procedures unterstützt. Alles was wir hier diskutieren betrifft SQLite. Der Einsatz einer externen MySQL Datenbank ist eigentlich nur sinnvoll, wenn man einen Server/NAS hat der das Update selbsttätig macht, und die Kodis nur noch die Datenbank zum Abfragen mitbenutzen. Nutzer die eine solche Konfiguration haben, haben kein Geschwindigkeitsproblem, weil sie immer eine aktuelle Datenbank haben (die wird ja im Idealfall auf dem Server aktuell gehalten).

**Comment by lookshe** [comment]
Unabhängig der Prozedurfrage wäre auch noch folgende: Warum für jeden Film md5 aus channel, show und url berechnen (https://github.com/mediathekview/plugin.video.mediathekview/blob/master/resources/lib/storemysql.py#L886), statt einfach diese drei Werte als Unique-Key zu verwenden und eine Abfrage auf der DB zu machen? Ggf. könnte ein REPLACE-INTO mit dem Unique-Key sogar schneller sein, als erst die Abfrage und dann entweder Update auf touched oder ein Insert auszuführen.
Weiterhin konnte ich auf die Schnelle nicht finden, ob evtl. die Prozeduren alle einzeln mit Commits aufgerufen werden, was die DB natürlich extrem verlangsamen würde oder ob alles in einer Transaktion stattfindet mit einmaligem Commit.
Und eine kleine weitere Verbesserung: https://github.com/mediathekview/plugin.video.mediathekview/blob/master/resources/lib/storemysql.py#L999 --> Warum erst zählen und nicht auslesen, wieviel die Delete-Queries gelöscht haben? Stichwort [ROW_COUNT()](https://mariadb.com/kb/en/library/information-functions-row_count/)

**Comment by tuxpoldo** [comment]
Ganz am Anfang war das so (Unique Key). Wir haben das geändert weil der Index sehr groß war und bei Systemen mit langsamen IO die Sache zusätzlich verlangsamt hat.

Zum Thema `ROW_COUNT()`: Stimmt. Nach dem das Update gelaufen ist, spart man dadurch bestimmt 500 Millisekunden ;-)

**Comment by Siggi0904** [comment]
Wenn du die Datenbankabfragen so lassen willst, was ich auch durchaus verstehen kann, wäre ja das direkte herunterladen der DB ein Versuch wert. Müssten die gesehen Markierungen nur in eine separate DB.

Alles was wir beide (lookshe und ich) hier machen sind ja nur gute Ratschläge um die Performance zu erhöhen.

Alles im Sinne des Plugins und der Nutzung auf langsamen Systemen zu Erhöhen.

**Comment by tuxpoldo** [comment]
Dafür bin ich auch dankbar. Aber leider kann keiner dieser Vorschläge einen nennenswerten Performance-Gewinn bringen.... wie gesagt: das mit dem Unique-Index hatte wir schon mal ganz am Anfang (Schaut mal in die Git-Historie rein), und das mit dem Zählen statt `ROW_COUNT()` ist eine einmalige Operation am Ende des Updates und bringt nahezu nichts gegenüber den 60-90 Minuten, die das Update auf einer WeTek dauert.

Ich muss aber jetzt noch mal auf den Kern des Problems zurück kommen und der betrifft alle Leute die ein kleines Android-Basiertes Kodi-Device bzw. einen Raspi mit seiner leider sehr lahmen SD-Kartenanbindung haben und eine lokale Datenbank fahren. Das ist die Sorte Nutzer, die ein Geschwindigkeitsproblem haben. Und denen kann man leider nur auf zwei mögliche Art und weisen helfen:

1. Entweder können diese die Datenbank bereits fertig herunterladen. Das wäre zwar cool, aber ich sehe mich im Moment nicht im Stande die Infrastruktur dafür bereit zu stellen. **Habt ihr irgendeine Idee, wo man die Dateien am besten ohne Zusatzkosten Hosten könnte - ich bezweifle nämlich dass mein Server der Last stand hält**
2. Die Anfragen erfolgen über eine externe Datenbank - das könnte z.B. MediathekViewWeb sein. Das Problem ist leider, dass diese im Moment nicht die Anfragen unterstützt, die für ein solchen Plugin nötig wären, sondern lediglich eine Volltext-Suche - zumindest habe ich noch keine dafür passende API gefunden. Die Lösung wäre hier also eine neue abfragbare API zur Verfügung zu stellen. Das könnte mittelfristig machbar sein...

**Comment by lookshe** [comment]
Wie wäre es mit den Verteilservern des Projekts?

Warum ein Replace-Into (1 Query) gegen ein Select + Insert/Update (2 Queries) keinen Performancegewinn bringen soll und das Thema Transaktionen unbeachtet gelassen wird, was u.U. viel Perfomance bringt, da nur einmalig am Ende die DB beschrieben wird, statt bei jedem Insert/Update, will ich gar nicht versuchen zu verstehen.

**Comment by Siggi0904** [comment]
Du bist doch mit deinem Projekt offizieller Port von der Desktop-Version.
Somit sollten dir doch alle Ressourcen der Verteilserver zur Verfügung stehen.

Des Weiteren könnte eine Anfrage beim MediathekviewWeb auch hilfreich sein.
Dort könnte die DB ausgepackt ja schon liegen.

Das wären so meine Ideen.

**Comment by tuxpoldo** [comment]
Also:
1. Ein `REPLACE` könnte vielleicht tatsächlich etwas bringen. Habe mir gerade noch mal die Doku von SQLite angeschaut, und es wird ein solches Statement unterstützt. Ich teste das gleich mal aus, udn berichte, ob sich dadurch das Timing verbessert.
2. Ob das mit den Transaktionen bei SQLite was bringt ist fraglich, da er alle Operationen erst mal in einer großen Datei schreibt, und die dann beim Commit abarbeitet. Da der Hauptgrund für die Langsamkeit die IO Leistung des Massenspeichers ist, könnte das unter Umständen sogar kontraproduktiv sein. Ich schaue mir aber mal an, ob ich das mit endlichen Aufwand getestet bekomme...
3. Das ich ein offizieller Port bin, bedeutet nicht zwangsläufig, dass ich mit den Verteiler-Servern machen kann, was ich will. Die Bandbreite dieser Server ist eine kostbare Ressource von der ich persönlich im Moment nicht weiss, wie ausgelastet sie ist. Die Entscheidung liegt in diesem Falle definitiv nicht bei mir. Aber ich kann Alex, der sich darum kümmert ja mal auf diesen Thread aufmerksam machen. Möglicherweise gibt es vielleicht ja doch eine Möglichkeit....

**Comment by tuxpoldo** [comment]
p.S.: MediathekViewWeb nutzt Elastic Search als interne DB/Index. Dies ist nicht auf eine Kodi-Box übertragbar.

**Comment by Siggi0904** [comment]
Kommentar von lookshe an mich gerade per jabber:
"10k eintraege in eine (eigene) db eingefuegt mit replace-into. mit transaktion 12s, ohne 62s"

Könnte also nicht schlecht sein. :-)

**Comment by tuxpoldo** [comment]
Wenn das so übertragbar wäre, wäre das in der Tat vielversprechend. Ich probiere gleich mal ein paar der Sachen aus.

**Comment by lookshe** [comment]
https://stackoverflow.com/questions/1711631/improve-insert-per-second-performance-of-sqlite <-- da steht auch einiges zu dem Thema. Wenn man dem Glauben schenken darf, und meine Erfahrung bzgl. Datenbanken sagt dies, bringt allein die Transaktion um alle DB-Aktionen extrem viel.

**Comment by lookshe** [comment]
Die angegebenen Werte von Siggi waren nur von irgendwelchen Testdaten auf ner Mysql, um das Thema Transaktion zu veranschaulichen. Hab mir aber mal den Spass gemacht, das ganze mit ner sqlite zu bauen, einfach nur Id und Text-Felder.
Vorbereitung DB und zwei Skripte mit Daten, einmal mit, einmal ohne Transaktion, jeweils 1000 Datensätze:
```
sqlite3 -batch test.db "create table test(id integer primary key, test text);"
for i in `seq 1000`; do echo "replace into test values ($i, 'test');"; done > test_no_transaction.sql
echo "begin transaction;" > test_transaction.sql
for i in `seq 1000`; do echo "replace into test values ($i, 'test');"; done >> test_transaction.sql
echo "commit transaction;" >> test_transaction.sql
```
Einmalig DB befüllt, damit Ergebnisse vergleichbar sind und dann folgendes aufgerufen:
```
date ; sqlite3 -init test_transaction.sql -batch test.db "" ; date
Sun Aug 26 16:48:29 CEST 2018
Sun Aug 26 16:48:29 CEST 2018
```
Ab und zu war es auch eine knappe Sekunde
Im Gegensatz dazu ohne Transaktion:
```
date ; sqlite3 -init test_no_transaction.sql -batch test.db "" ; date
Sun Aug 26 16:48:52 CEST 2018
Sun Aug 26 16:52:28 CEST 2018
```
Das ganze ausgeführt auf einem Server ohne SSD.

Dagegen mein Laptop mit SSD:
```
lookshe@laptop /opt/test
16:51:32>>date ; sqlite3 -init test_transaction.sql -batch test.db "" ; date
So 26. Aug 16:51:33 CEST 2018
So 26. Aug 16:51:33 CEST 2018
```
```
lookshe@laptop /opt/test
16:51:33>>date ; sqlite3 -init test_no_transaction.sql -batch test.db "" ; date
So 26. Aug 16:51:37 CEST 2018
So 26. Aug 16:52:11 CEST 2018
```

Eine Transaktion sollte spontan also eine sehr starke Beschleunigung bringen. Wieviel dann natürlich Select+Update/Insert gegen Replace-Into ausmacht, lässt sich schwer einschätzen ohne im Detail die datenbankinternen Abläufe zu kennen. In sqlite stecke ich dafür auch nicht weit genug drin.

**Comment by tuxpoldo** [comment]
Ich bin gerade dabei das ganze zu testen. Leider muss ich um die Sache mit der Transaktion hinzubekommen, an einer Stelle eine unvorhergesehene Änderung machen. Dauert also noch einen Moment...

**Comment by tuxpoldo** [comment]
...jetzt weiss ich wieder, warum ich das mit den Transactions damals nicht gemacht habe. Der Python-Treiber für SQLite macht einem nämlich das Leben zur Hölle....

https://stackoverflow.com/questions/15856976/transactions-with-python-sqlite3

Der meint das nämlich besser zu können, und verwaltet die Transaktionen selber... Und so richtig abgewöhnt bekomme ich ihm das nicht. Erst wundert man sich, dass es genau so lahm wie vorher ist...

````
2018-08-26 17:48:42.611789 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (95%): channels:19, shows:3871, movies:241999 ...
2018-08-26 17:48:43.127711 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (96%): channels:19, shows:3876, movies:242999 ...
2018-08-26 17:48:43.634872 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (96%): channels:19, shows:3877, movies:243999 ...
2018-08-26 17:48:44.189760 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (96%): channels:19, shows:3877, movies:244999 ...
2018-08-26 17:48:44.758470 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (97%): channels:19, shows:3877, movies:245999 ...
2018-08-26 17:48:45.280164 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (97%): channels:19, shows:3883, movies:246999 ...
````

und dann knallt es, weil angeblich keine Transaktion zum Committen mehr da ist...

````
2018-08-26 17:48:46.900401 NOTICE [mvupdate-0.5.1:StoreSQLite]: Before End of Transaction
2018-08-26 17:48:46.900541 ERROR [mvupdate-0.5.1:StoreSQLite]: Database error during critical operation: cannot commit - no transaction is active - Database will be rebuilt from scratch.
````

**Comment by tuxpoldo** [comment]
So. Jetzt endlich geht es. Ob er aber wirklich Transaktionen intern benutzt, ist schwer zu sagen. Das `END TRANSACTION` macht er jetzt halt anstandslos. Aber...

````
2018-08-26 18:29:13.636480 NOTICE [mvupdate-0.5.1]: Startup
2018-08-26 18:29:13.636676 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Database driver: Internal (sqlite)
2018-08-26 18:29:13.636749 NOTICE [mvupdate-0.5.1:StoreSQLite]: Using SQLite version 3.24.0, python library sqlite3 version 2.6.0
2018-08-26 18:29:13.636875 NOTICE [mvupdate-0.5.1:StoreSQLite]: ===== RESET: Database will be deleted and regenerated =====
2018-08-26 18:29:13.649765 NOTICE [mvupdate-0.5.1]: Starting up...
2018-08-26 18:29:13.650056 NOTICE [mvupdate-0.5.1]: Initiating full update...
2018-08-26 18:29:13.650295 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Starting import of approx. 252983 records from ./Filmliste-akt
2018-08-26 18:29:13.650367 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Initializing update...
2018-08-26 18:29:13.650411 NOTICE [mvupdate-0.5.1:StoreSQLite]: BEGIN TRANSACTION
2018-08-26 18:29:13.650454 NOTICE [mvupdate-0.5.1:StoreSQLite]: Starting full database update in fast mode
2018-08-26 18:29:13.655131 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Filmliste dated 26.08.2018, 17:26
2018-08-26 18:29:13.655927 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (0%): channels:0, shows:0, movies:0 ...
2018-08-26 18:29:14.026063 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (0%): channels:1, shows:14, movies:1000 ...
2018-08-26 18:29:14.422919 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (0%): channels:1, shows:18, movies:2000 ...
...
2018-08-26 18:31:02.822418 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (98%): channels:20, shows:5047, movies:249000 ...
2018-08-26 18:31:02.912509 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Added: channels:20, shows:5058, movies:249218 ...
2018-08-26 18:31:02.922067 NOTICE [mvupdate-0.5.1:StoreSQLite]: Before End of Transaction
2018-08-26 18:31:02.925369 NOTICE [mvupdate-0.5.1:StoreSQLite]: After End of Transaction
2018-08-26 18:31:02.925438 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Deleted: channels:0, shows:0, movies:0
2018-08-26 18:31:02.925470 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Total: channels:20, shows:5058, movies:249218
2018-08-26 18:31:02.925721 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Import of ./Filmliste-akt in update cycle 0 finished
2018-08-26 18:31:02.925763 NOTICE [mvupdate-0.5.1]: Exiting...
````
18:31:02 - 18:29:13 = 109 Sekunden. Aus irgendeinem Grunde bringt es hier gar nix. Man kann sich allerdings nicht wirklich sicher sein, dass der Python-Treiber nicht doch macht, was er will....

**Comment by bagbag** [comment]
Die aktuelle Version von MediathekViewWeb bietet eine relativ einfache API an (die doch etwas mehr als eine einfache Volltextsuche bietet). Siehe hierzu [ein kleines Beispiel](https://gist.github.com/bagbag/a2888478d27de0e989cf777f81fb33de).
Ansonsten will ich auch selbst endlich mal MVW 2 weiter bringen, das hat dann eine viele mächtigere API. Testen kannst du das mal hier: [https://testing.mediathekviewweb.de/dev](https://testing.mediathekviewweb.de/dev). Mögliche Queries findest du hier: [https://github.com/mediathekview/mediathekviewweb/blob/backup/common/search-engine/query/definition.ts](https://github.com/mediathekview/mediathekviewweb/blob/backup/common/search-engine/query/definition.ts)

Mein Server hat monatlich 20TB ungedrosselt zur verfügung, davon werden monatlich aktuell etwa 6TB verbraucht (durch MVW, der Verteiler (in MV mit hoher Priorität genutzt) und ein paar private sachen). Da kannst du gerne einige TBs nutzen.

**Comment by lookshe** [comment]
Wäre es vielleicht möglich alle Queries zu loggen? Dann könnte man das testweise ohne Python- oder Framework-Overhead laufen lassen und zudem wiederholt auf der selben Datenbank um vergleichbare Ergebnisse zu haben. Zudem ist der Vergleich auf einem schnellen System mit viel I/O-Performance eher kontraproduktiv, da einige der Berechnungen Zeit kosten und nichts mit I/O zu tun haben.

**Comment by tuxpoldo** [comment]
Hallo Patrick, danke für die Infos. Nächste Woche, wenn ich wieder was Zeit habe, schaue ich mir das mal an. Das erste Beispiel kannte ich bereits - du hattest es mir ja schon mal verlinkt. Leider kriege ich mit dieser Technik allerdings nicht alle Queries die ich bräuchte hin (zumindest glaube ich das). Das neue API sieht vielversprechend aus.

Leider haben alle vorgeschlagenen Ansätze keinen großen Erfolg gebracht. Ich hatte eben auch noch mal versucht, das ganze innerhalb einer Transaktion laufen zu lassen - musste dabei aber entdecken, dass es die spezielle Implementierung der SQLite Library in Python ziemlich schwer macht, Transaktionen überhaupt zu nutzen. Das hatte ich bereits im Dezember, am Anfang der Entwicklung bemerkt, aber nach so langer Zeit verdrängt/vergessen.

Wie dem auch sei - vor lauter Bäumen habe ich wohl den Blick für das wesentliche verloren. Denn irgendwie habe ich wohl immer für ausgemacht angesehen, dass die Datenbank der Grund ist, warum das Update so langsam ist. Der vorherige Kommentar von @lookshe zielt zwar darauf ab, genauer zu testen, was die Datenbank da überhaupt tut, aber er hat mich auf die Idee gebracht, mal zu schauen, was der Rest eigentlich tut... Und da tun sich nämlich Abgründe auf.

Also habe ich mal die drei Routinen des Datenbankinterfaces die vom Updater aufgerufen werden (`ft_update_start`, `ft_update_end`, `ft_insert_film`) ausge"faked" so dass sie einfach gar nichts tun und sofort zurück kommen. Danach den Updater aufgerufen und.... voilà:

````
2018-08-26 22:22:30.582343 NOTICE [mvupdate-0.5.1]: Starting up...
2018-08-26 22:22:30.582665 NOTICE [mvupdate-0.5.1]: Initiating full update...
2018-08-26 22:22:30.582951 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Starting import of approx. 252983 records from ./Filmliste-akt
2018-08-26 22:22:30.583038 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Initializing update...
2018-08-26 22:22:30.589695 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Filmliste dated 26.08.2018, 17:26
2018-08-26 22:22:30.590480 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (0%): channels:0, shows:0, movies:0 ...
...
018-08-26 22:23:51.719791 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: In progress (98%): channels:0, shows:0, movies:0 ...
2018-08-26 22:23:51.788052 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Added: channels:0, shows:0, movies:0 ...
2018-08-26 22:23:51.788108 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Deleted: channels:0, shows:0, movies:0
2018-08-26 22:23:51.788128 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Total: channels:0, shows:0, movies:0
2018-08-26 22:23:51.788389 NOTICE [mvupdate-0.5.1:MediathekViewUpdater]: Import of ./Filmliste-akt in update cycle 0 finished. Duration: 81 seconds
2018-08-26 22:23:51.788421 NOTICE [mvupdate-0.5.1]: Exiting...
````

**81 Sekunden**, ohne dass in der Datenbank überhaupt etwas passiert ist! Im Umkehrschluss bedeutet das, dass basierend auf den Daten des letzten Tests (109 Sekunden) nur 28 Sekunden in der Datenbank verbracht wurden.

Also habe ich den Code mal schnell auf meinen richtigen Kodi-Rechner kopiert, der um Längen langsamer ist (ASRock ION 3D 152D/B Desktop-PC - Intel Atom D525 1,8GHz, 2GB RAM), also in etwa vergleichbar mit einem RasPI (zumindest CPU mäßig) und siehe da...

````
2018-08-26 22:42:56.249729 NOTICE [mvupdate-0.0:MediathekViewUpdater]: In progress (98%): channels:0, shows:0, movies:0 ...
2018-08-26 22:42:56.619993 NOTICE [mvupdate-0.0:MediathekViewUpdater]: Added: channels:0, shows:0, movies:0 ...
2018-08-26 22:42:56.620188 NOTICE [mvupdate-0.0:MediathekViewUpdater]: Deleted: channels:0, shows:0, movies:0
2018-08-26 22:42:56.620352 NOTICE [mvupdate-0.0:MediathekViewUpdater]: Total: channels:0, shows:0, movies:0
2018-08-26 22:42:56.621069 NOTICE [mvupdate-0.0:MediathekViewUpdater]: Import of ./Filmliste-akt in update cycle 0 finished. Duration: 457 seconds
2018-08-26 22:42:56.621283 NOTICE [mvupdate-0.0]: Exiting...
````

**457 Sekunden**, ganze 8 Minuten lediglich für das Parsen und Aufbereiten der Update-Datei. Ein echtes Update dauert auf der Kiste wenn ich mich recht erinnere so um die 15 Minuten. Es ist also einfach so, dass alleine der Python Code der die Daten entsprechend aufbereitet nicht gerade durch Effizienz glänzt. An diesem Punkt würde mich mal interessieren, wie sich das ganze auf so einer Kiste wie ein Wetek Play verhalten würde aber ich wüsste jetzt auf Anhieb nicht, wie ich den Test dort ausführen könnte.

Das deckt sich auf jeden Fall mit gewissen Erfahrungen die wir in der Firma bzgl. Processing größerer Textdaten in Python 2 gemacht haben. Da hat die Umstellung auf P3 und den entsprechend neueren Libraries einen dramatischen Performance-Gewinn gebracht. Leider ist man bei Kodi-Addons aber auf das angewiesen, was die Umgebung zu bieten hat, und das ist nun mal das Python was in Kodi hineinkompiliert wurde und eine Handvoll reiner Python-Libraries die sich als Library-Addons nachrüsten lassen. Das war es dann auch schon, da man über die Zielplatformen keine Annahmen machen kann...

Somit wäre die einfachste und beste Lösung immer noch jene, eine fertige SQLite Datenbank zum Download anzubieten, wie ich bereits weiter oben erwähnte. Möglicherweise wäre es nicht ganz unsinnig das zu versuchen, allzumal die Plugin-Benutzer eh schon pro Tag einmal die `Filmliste-akt` ziehen - also wäre die Zusätzlich erforderliche Bandbreite nur die DIfferenz der Größe. Ich sollte tatsächlich Alex mal fragen, ob wir uns das leisten können...

**Comment by Siggi0904** [comment]
OK, danke für den Hinweis.

Bevor du das bezüglich der externen Datenbank im Team anfragst, könnten wir das auch erstmal auf der Wetek testen. Wenn du mir das Update zum Plugin gibst und die DB erstmal bei dir liegen hast, könnten wir sehen ob und wieviel schneller das ist.

**Comment by tuxpoldo** [comment]
Ich habe gestern noch ein wenig Zeit investiert, um mal zu schauen inwieweit ich eine ausreichende Versorgungsinfrastruktur auch selber hinbekomme, und bin da inzwischen besserer Dinge. Ich werde das jetzt auf jeden Fall mal einbauen und dann stelle ich euch mal eine Version zum Testen bereit.

Es wird euch sicher gefallen, weil es dann im Vergleich blitzschnell sein wird. Herunterladen, Entpacken, Fertig.

Melde mich, wenn es soweit ist.

**Comment by Siggi0904** [comment]
Klingt gut, würde mich freuen, wenn das Addon wieder nutzbar ist.
Das Addon hat einfach ein großes Potential.

**Comment by tuxpoldo** [comment]
Kurze Frage.... Du machst mich jetzt stutzig: _"...wenn das Addon **wieder** nutzbar..."_ Willst Du mir damit sagen, dass das früher mal schneller war? Das kann ich mir beim besten willen nicht vorstellen. Falls aber doch, musst DU mir unbedingt sagen, bei welchen Versionssprung sich da so viel negatives getan hat.

**Comment by tuxpoldo** [comment]
BTW: Wir arbeiten gerade an der Bereitstellung der Infrastruktur....

**Comment by Siggi0904** [comment]
Na da bin ich ja gespannt wie schnell die aktualisierte Version ist.

Bezüglich "wieder nutzbar" war eher auf den Zugriff der Mediathek gemeint.
Ich hatte vorher ein anderes Addon: https://kodi.wiki/view/Add-on:Mediathek

Wollte deinem Addon aber den Vorzug geben.

**Comment by Siggi0904** [comment]
Hi, gibt es schon was zum Testen?

**Comment by Krawei** [comment]
Any updates here?

**Comment by tuxpoldo** [comment]
Yes. The first working version has been committed today. I'm working hard on testing and preparing the infrastructure for servicing the updates. I think that I will release a package in the beta repository within this week.
