### ISSUE TITLE
Betriebsmodus ohne lokale Datenbank

### ISSUE THREAD

**Issue by tuxpoldo** [mediathekview/plugin.video.mediathekview#86]
Auf sehr langsamen Geräten ist der Betrieb mit lokaler Datenbank nicht zumutbar. Es soll geprüft werden, inwieweit ein DB-Backend welches auf einen Dienst wie MediathekVIewWeb zugreift, ein brauchbares Subset an Funktionalität erlaubt.

**Comment by Siggi0904** [comment]
Ich würde hierzu sagen, dass es nicht unbedingt an der Datenbank liegt.
Das entpacken des Download files dauert halt sehr lange.

Vielleicht könnte vorab mal das Addon um genaueres reporting erweitert werden.
Dann kann man mal sehen, was da im Detail so lange dauert.

**Comment by tuxpoldo** [comment]
Das Reporting gibt es. Den genauen Vorgang kann man im Kodi-Logfile beobachten. Das Entpacken geht vergleichsweise schnell vonstatten. Es ist wirklich das Einpflegen in die SQL Datenbank, was eine Ewigkeit dauert.

**Comment by Siggi0904** [comment]
Oh ok, das erklärt das super.

Danke für die Infos. Dann bin ich mal auf die Optimierungen im anderen Issue gespannt.

**Comment by Wikinaut** [comment]
Siehe hier https://github.com/mediathekview/plugin.video.mediathekview/issues/50

**Comment by tuxpoldo** [comment]
Ups! Hatte wohl übersehen, dass es den Feature-Request schon gab.....

**Comment by tuxpoldo** [comment]
Ist im wesentlichen das Gleiche wie #50 
Das Problem wurde in Version 0.6.0 entschieden entschärft durch #85 #110
