### ISSUE TITLE
Aktualisierungen der Datenbank per Zeitintervall

### ISSUE THREAD

**Issue by tanrak** [mediathekview/plugin.video.mediathekview#94]
Hallo, danke erstmal für diese tolle Mediathek-Erweiterung. Nun aber kurz zu meinem Anliegen. Kann es sein, dass mit dem letzten Update die Möglichkeit der Datenbankaktualisierung in einem zeitlichen Intervall weggefallen ist? Wenn ja, warum und lässt sich dieses Feature wieder integrieren?!

**Comment by tuxpoldo** [comment]
Hallo @tanrak ,

die Möglichkeit ist nicht weggefallen - sie hat sich lediglich verändert. Ich zitiere hier mal das `README.md`:

> Das Addon unterstützt 4 verschiedene Aktualisierungsmethoden:
> 1. **Automatisch (Standard):** Bei dieser Methode wird die Aktualisierung der Datenbank automatisch durchgeführt. Die Aktualisierung erfolgt ein mal pro eingestelltem Aktualisierungsintervall (Standard: 2 Stunden). Die erste Aktualisierung eines Kalendertages ist eine vollständige Aktualisierung, alle weiteren sind Differenz-Aktualisierungen. Die automatische Aktualisierung pausiert, wenn das Addon länger als 2 Stunden nicht bedient wurde, um Bandbreite und bei mobilen Geräten Strom zu sparen.
> 2.  **Nur beim Start:**: Eine Aktualisierung erfolgt nur beim Start von Kodi. Handelt es sich hierbei um die erste Aktualisierung des Kalendertages, ist dies eine vollständige Aktualisierung, ansonsten eine differentielle. Alle weiteren Aktualisierungen müssen manuell über das Hauptmenü vom Benutzer
ausgelöst werden.
> 3.  **Manuell:** Es erfolgt keine automatische Aktualisierung. Der Benutzer hat die Möglichkeit Aktualisierungen über das Hauptmenü auszulösen. Handelt es sich hierbei um die erste Aktualisierung des Kalendertages, ist dies eine vollständige Aktualisierung, ansonsten eine differentielle.
> 4.  **Abgeschaltet:** Es erfolgt keine automatische Aktualisierung. Diese Konfiguration ist nur dann sinnvoll, wenn das Plugin eine externe Datenbank nutzt und diese anderweitig aktualisiert wird.

Was mir allerdings aufgefallen ist, ist dass die Einstellung für den Aktualisierungsintervall nicht mehr sichtbar ist. Das ist offensichtlich ein Fehler, den ich in der nächsten Version korrigieren werde.

**Comment by tanrak** [comment]
Danke für die Info. Genau diese Einstellung habe ich vermisst. Die Pausierung von 2h erklärt nun auch, warum mit der neuen Version jedes mal wenn ich Abends dieses Addon erstmalig nutze eine vollständige Aktualisierung stattfindet. Mit der vorherigen Version hatte er zu diesem Zeitpunkt nur noch das inkrementelle Update machen müssen, da auf meinen 24h on Raspi2 das Update alle 2h durchgeführt wurde. Nun dauert das vollständige Update auf einen Raspi2 schon ein bisschen und ich muss nun bevor ich einen halbwegs aktuellen Stand habe etwas warten.
Aus Bandbreiten- und Stromgründen kann ich die Sache mit der Pause durchaus nachvollziehen, ist aber für meine Zwecke nicht so gut. Vielleicht wäre es möglich, das Addon, unabhängig von der automatischen Aktualisierung, dazu zu bringen einmal am Tag zu einem festen wählbaren Zeitpunkt ein Update anzustoßen. Ist ja letzlich egal, ob das erstmalig am Kalendertag (und damit ein vollständiges Update wäre) oder später stattfindet (und damit ein inkrementelles Update wäre). Ich könnte diesen Zeitpunkt aber auf bspw. eine Stunde vor der Zeit in der ich das Addon nutzen möchte stellen und hätte damit ohne warten zu müssen einen aktuellen Datenstand.
Ich hoffe mein Problem und mein Anliegen einigermaßen verständlich dargelegt zu haben.

**Comment by tuxpoldo** [comment]
Kann ich verstehen. Ich baue Dir dann mal noch ein weiteren Modus ein ("Immer"). Finde ich auch besser.

**Comment by tanrak** [comment]
Sehr schön. Vielen Dank!
