### ISSUE TITLE
Sortierung nach Uhrzeit, Datum

### ISSUE THREAD

**Issue by x2k13** [mediathekview/plugin.video.mediathekview#95]
Es wäre schön, wenn man die Listen jeweils nicht nur nach Titel _oder_ Datum, sondern auch nach Uhrzeit _und_ Datum, im Idealfall nach Datum, Uhrzeit, Titel sortieren könnte. 

Derzeit ist es so: Bei mir sehe ich entweder 2018 (Titel) oder 15.08.2018 (Datum). Dies ist verständlicherweise nicht sonderlich informativ wenn die Sendungen auch noch gleich benannt sind, z.B. Arte Journal o.ä.. 

Optimal wäre dieses Beispiel: 10.08.2018 (oder 2018-08-15), 19:20, Arte Journal

Ist so etwas in Planung @tuxpoldo ?

**Comment by tuxpoldo** [comment]
Hallo @x2k13 ,

ich befürchte, dass man da nicht viel machen kann, weil die Möglichkeiten diese Listen und die Anzeigen zu beeinflussen für ein Plugin sehr begrenzt sind, und in erster Linie vom Skin beeinflusst werden. Bevor ich das Issue schließe, werde ich es mir aber nochmals in Ruhe anschauen. Vielleicht gibt es ja doch die eine oder andere Möglichkeit.

**Comment by x2k13** [comment]
Die Datenbank gäbe das jedenfalls her, die Uhrzeit ist ja vorhanden. Schau mal was da evtl. gehen könnte, vorerst würde es ja mit dem Standard Kodi Skin reichen. Danke.

**Comment by tuxpoldo** [comment]
Kodi aber nicht. Der kann echt nur nach Datum sortieren. In der [Dokumentation](https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcplugin.html#ga85b3bff796fd644fb28f87b136025f40) von `xbmcplugin.addSortMethod` kann man es nachlesen.

**Comment by tuxpoldo** [comment]
Addendum: das `listitem` kann auch nur wenige Info-Labels die etwas mit Zeit zu tun haben, und die beinhalten nur das Datum:

Info Label |Description
-- | --
date | string (d.m.Y / 01.01.2009) - file date
aired | string (2008-12-07)

Ich setze beide. Quelle: [Dokumentation](https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14) von `ListItem. setInfo`

**Comment by tuxpoldo** [comment]
Das einzige was mir im Moment als Möglichkeit einfällt, ist eine Option zu machen, die einen genauen Timestamp (sagen wir mal 2018-08-18 17:54:00) vor dem Titel stellt - Diese Option sollte natürlich einfach ein und abschaltbar sein... z.B. über das Kontextmenü....

**Comment by x2k13** [comment]
Die Idee hört sich gut an, das wäre dann sozusagen ein select aus aired und title, statt nur title.
Bin gespannt!

**Comment by codingPF** [comment]
In Kodi kann man nach dem DateAdded sortieren. Dieses ist ein voller Timestamp (mit Stunden) und enthält die Daten aus AirDate schon.

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4
